In [2]:
# Data handling
import pandas as pd
import numpy as np

# Visualization
import matplotlib.pyplot as plt
import seaborn as sns

# Machine Learning
from sklearn.preprocessing import StandardScaler, LabelEncoder
from sklearn.cluster import KMeans
from sklearn.decomposition import PCA
from sklearn.metrics import silhouette_score

# NLP
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.feature_extraction.text import CountVectorizer

import warnings
warnings.filterwarnings('ignore')# Load CSV file

In [3]:
# Load CSV file
df = pd.read_csv("Airline Delay.csv")

# Display first rows
df.head()

,year,month,carrier,carrier_name,airport,airport_name,arr_flights,arr_del15,carrier_ct,weather_ct,...,security_ct,late_aircraft_ct,arr_cancelled,arr_diverted,arr_delay,carrier_delay,weather_delay,nas_delay,security_delay,late_aircraft_delay
0,2020,12,9E,Endeavor Air Inc.,ABE,"Allentown/Bethlehem/Easton, PA: Lehigh Valley ...",44.0,3.0,1.63,0.0,...,0.0,1.25,0.0,1.0,89.0,56.0,0.0,3.0,0.0,30.0
1,2020,12,9E,Endeavor Air Inc.,ABY,"Albany, GA: Southwest Georgia Regional",90.0,1.0,0.96,0.0,...,0.0,0.00,0.0,0.0,23.0,22.0,0.0,1.0,0.0,0.0
2,2020,12,9E,Endeavor Air Inc.,AEX,"Alexandria, LA: Alexandria International",88.0,8.0,5.75,0.0,...,0.0,0.65,0.0,1.0,338.0,265.0,0.0,45.0,0.0,28.0
3,2020,12,9E,Endeavor Air Inc.,AGS,"Augusta, GA: Augusta Regional at Bush Field",184.0,9.0,4.17,0.0,...,0.0,3.00,0.0,0.0,508.0,192.0,0.0,92.0,0.0,224.0
4,2020,12,9E,Endeavor Air Inc.,ALB,"Albany, NY: Albany International",76.0,11.0,4.78,0.0,...,0.0,1.00,1.0,0.0,692.0,398.0,0.0,178.0,0.0,116.0

In [4]:
# Dataset information
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 3351 entries, 0 to 3350
Data columns (total 21 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   year                 3351 non-null   int64
 1   month                3351 non-null   int64
 2   carrier              3351 non-null   str
 3   carrier_name         3351 non-null   str
 4   airport              3351 non-null   str
 5   airport_name         3351 non-null   str
 6   arr_flights          3343 non-null   float64
 7   arr_del15            3343 non-null   float64
 8   carrier_ct           3343 non-null   float64
 9   weather_ct           3343 non-null   float64
 10  nas_ct               3343 non-null   float64
 11  security_ct          3343 non-null   float64
 12  late_aircraft_ct     3343 non-null   float64
 13  arr_cancelled        3343 non-null   float64
 14  arr_diverted         3343 non-null   float64
 15  arr_delay            3343 non-null   float64
 16  carrier_delay        3343 non-null   float64
 17  weather_delay        3343 non-null   float64
 18  nas_delay            3343 non-null   float64
 19  security_delay       3343 non-null   float64
 20  late_aircraft_delay  3343 non-null   float64
dtypes: float64(15), int64(2), str(4)
memory usage: 762.7 KB

In [5]:
df.columns

Index(['year', 'month', 'carrier', 'carrier_name', 'airport', 'airport_name',
       'arr_flights', 'arr_del15', 'carrier_ct', 'weather_ct', 'nas_ct',
       'security_ct', 'late_aircraft_ct', 'arr_cancelled', 'arr_diverted',
       'arr_delay', 'carrier_delay', 'weather_delay', 'nas_delay',
       'security_delay', 'late_aircraft_delay'],
      dtype='str')

In [7]:
print(locals().keys())

dict_keys(['__name__', '__doc__', '__package__', '__loader__', '__spec__', '__builtin__', '__builtins__', '_ih', '_oh', '_dh', 'In', 'Out', 'get_ipython', 'exit', 'quit', 'open', '_', '__', '___', '__session__', '_i', '_ii', '_iii', '_i1', 'pd', 'np', 'plt', 'sns', 'StandardScaler', 'LabelEncoder', 'KMeans', 'PCA', 'silhouette_score', 'TfidfVectorizer', 'CountVectorizer', 'warnings', '_i2', '_i3', 'df', '_3', '_i4', '_i5', '_5', '_i6', '_i7'])

In [9]:
print(df.head())

   year  month carrier       carrier_name airport  \
0  2020     12      9E  Endeavor Air Inc.     ABE
1  2020     12      9E  Endeavor Air Inc.     ABY
2  2020     12      9E  Endeavor Air Inc.     AEX
3  2020     12      9E  Endeavor Air Inc.     AGS
4  2020     12      9E  Endeavor Air Inc.     ALB

                                        airport_name  arr_flights  arr_del15  \
0  Allentown/Bethlehem/Easton, PA: Lehigh Valley ...         44.0        3.0
1             Albany, GA: Southwest Georgia Regional         90.0        1.0
2           Alexandria, LA: Alexandria International         88.0        8.0
3        Augusta, GA: Augusta Regional at Bush Field        184.0        9.0
4                   Albany, NY: Albany International         76.0       11.0

   carrier_ct  weather_ct  ...  security_ct  late_aircraft_ct  arr_cancelled  \
0        1.63         0.0  ...          0.0              1.25            0.0
1        0.96         0.0  ...          0.0              0.00            0.0
2        5.75         0.0  ...          0.0              0.65            0.0
3        4.17         0.0  ...          0.0              3.00            0.0
4        4.78         0.0  ...          0.0              1.00            1.0

   arr_diverted  arr_delay  carrier_delay  weather_delay  nas_delay  \
0           1.0       89.0           56.0            0.0        3.0
1           0.0       23.0           22.0            0.0        1.0
2           1.0      338.0          265.0            0.0       45.0
3           0.0      508.0          192.0            0.0       92.0
4           0.0      692.0          398.0            0.0      178.0

   security_delay  late_aircraft_delay
0             0.0                 30.0
1             0.0                  0.0
2             0.0                 28.0
3             0.0                224.0
4             0.0                116.0

[5 rows x 21 columns]

In [10]:
df.head()

,year,month,carrier,carrier_name,airport,airport_name,arr_flights,arr_del15,carrier_ct,weather_ct,...,security_ct,late_aircraft_ct,arr_cancelled,arr_diverted,arr_delay,carrier_delay,weather_delay,nas_delay,security_delay,late_aircraft_delay
0,2020,12,9E,Endeavor Air Inc.,ABE,"Allentown/Bethlehem/Easton, PA: Lehigh Valley ...",44.0,3.0,1.63,0.0,...,0.0,1.25,0.0,1.0,89.0,56.0,0.0,3.0,0.0,30.0
1,2020,12,9E,Endeavor Air Inc.,ABY,"Albany, GA: Southwest Georgia Regional",90.0,1.0,0.96,0.0,...,0.0,0.00,0.0,0.0,23.0,22.0,0.0,1.0,0.0,0.0
2,2020,12,9E,Endeavor Air Inc.,AEX,"Alexandria, LA: Alexandria International",88.0,8.0,5.75,0.0,...,0.0,0.65,0.0,1.0,338.0,265.0,0.0,45.0,0.0,28.0
3,2020,12,9E,Endeavor Air Inc.,AGS,"Augusta, GA: Augusta Regional at Bush Field",184.0,9.0,4.17,0.0,...,0.0,3.00,0.0,0.0,508.0,192.0,0.0,92.0,0.0,224.0
4,2020,12,9E,Endeavor Air Inc.,ALB,"Albany, NY: Albany International",76.0,11.0,4.78,0.0,...,0.0,1.00,1.0,0.0,692.0,398.0,0.0,178.0,0.0,116.0

In [11]:
df.to_csv(
    "Airline_Delay_KMeans_NLP_Result.csv",
    index=False
)