In [1]:
# Data handling
import pandas as pd
import numpy as np

# NLP
import nltk
import re
from nltk.corpus import stopwords
from nltk.stem import WordNetLemmatizer

# Machine Learning
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.cluster import KMeans
from sklearn.decomposition import PCA

# Visualization
import matplotlib.pyplot as plt

# Download NLP resources
nltk.download('stopwords')
nltk.download('wordnet')

[nltk_data] Downloading package stopwords to
[nltk_data]     /Users/adnanaltimeemy/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!
[nltk_data] Downloading package wordnet to
[nltk_data]     /Users/adnanaltimeemy/nltk_data...
[nltk_data]   Package wordnet is already up-to-date!

True

In [2]:
# Load dataset
df = pd.read_csv("Authors_List.csv")

# Display first rows
df.head()

    Anthony Coburn
0     Terry Nation
1   David Whitaker
2   John Lucarotti
3  Peter R. Newman
4   Dennis Spooner

In [4]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 102 entries, 0 to 101
Data columns (total 1 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   Anthony Coburn  102 non-null    str
dtypes: str(1)
memory usage: 2.2 KB

In [5]:
df.head()

    Anthony Coburn
0     Terry Nation
1   David Whitaker
2   John Lucarotti
3  Peter R. Newman
4   Dennis Spooner

In [7]:
print(df.columns.tolist())

['Anthony Coburn']

In [9]:
print(df.columns.tolist())
print(df.head())

['Anthony Coburn']
    Anthony Coburn
0     Terry Nation
1   David Whitaker
2   John Lucarotti
3  Peter R. Newman
4   Dennis Spooner

In [10]:
df.head()

    Anthony Coburn
0     Terry Nation
1   David Whitaker
2   John Lucarotti
3  Peter R. Newman
4   Dennis Spooner

In [11]:
df.to_csv(
    "Authors_List_clustered.csv",
    index=False
)

print("Saved successfully!")

Saved successfully!