In [1]:
# Data handling
import pandas as pd
import numpy as np

# Visualization
import matplotlib.pyplot as plt
import seaborn as sns

# Machine Learning
from sklearn.preprocessing import StandardScaler
from sklearn.cluster import KMeans
from sklearn.model_selection import train_test_split
from sklearn.metrics import mean_absolute_error, mean_squared_error

# NLP
import nltk
from nltk.sentiment import SentimentIntensityAnalyzer

# Prediction model
from sklearn.ensemble import RandomForestRegressor

import warnings
warnings.filterwarnings('ignore')

In [2]:
df = pd.read_csv("BitcoinPricePrediction.csv")

# Display first rows
df.head()

,Date,opening_price,highest_price,lowest_price,closing_price,transactions_in_blockchain,avg_block_size,sent_by_adress,avg_mining_difficulty,avg_hashrate,...,avg_transaction_value,median_transaction_value,tweets,google_trends,active_addresses,top100_to_total_percentage,avg_fee_to_reward,number_of_coins_in_circulation,miner_revenue,next_day_closing_price
0,2013-04-01,93.0,106.0,92.2,104.0,52572,139256,48809,6695826,6.550211e+13,...,2592.0,64.987,8193.0,15.248,75756.0,19.962,0.867,10975275.0,481891.360000,118.0
1,2013-04-02,104.0,118.4,99.0,118.0,63095,175443,62276,6695826,6.184560e+13,...,4400.0,94.955,8193.0,17.192,91875.0,20.024,1.338,10988125.0,531299.503749,135.0
2,2013-04-03,118.0,147.0,110.0,135.0,63766,184209,69174,6695826,6.027037e+13,...,4478.0,102.533,8193.0,26.608,107142.0,19.987,1.596,10986575.0,538423.880210,132.1
3,2013-04-04,135.0,142.1,116.4,132.1,66738,221568,71753,6695826,5.527246e+13,...,4249.0,123.314,8193.0,24.681,108890.0,19.990,1.948,10995725.0,525157.600000,142.3
4,2013-04-05,132.1,144.9,130.2,142.3,61215,190067,69310,7005058,5.181545e+13,...,4348.0,125.183,8193.0,20.514,100034.0,19.833,1.432,10999925.0,606454.781556,142.6

In [3]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 3093 entries, 0 to 3092
Data columns (total 25 columns):
 #   Column                          Non-Null Count  Dtype
---  ------                          --------------  -----
 0   Date                            3093 non-null   str
 1   opening_price                   3093 non-null   float64
 2   highest_price                   3093 non-null   float64
 3   lowest_price                    3093 non-null   float64
 4   closing_price                   3093 non-null   float64
 5   transactions_in_blockchain      3093 non-null   int64
 6   avg_block_size                  3093 non-null   int64
 7   sent_by_adress                  3093 non-null   int64
 8   avg_mining_difficulty           3093 non-null   int64
 9   avg_hashrate                    3093 non-null   float64
 10  mining_profitability            3093 non-null   float64
 11  sent_coins_in_usd               3093 non-null   int64
 12  avg_transaction_fees            3093 non-null   float64
 13  median_transaction_fees         3093 non-null   float64
 14  avg_block_time                  3093 non-null   float64
 15  avg_transaction_value           3093 non-null   float64
 16  median_transaction_value        3093 non-null   float64
 17  tweets                          3093 non-null   float64
 18  google_trends                   3093 non-null   float64
 19  active_addresses                3093 non-null   float64
 20  top100_to_total_percentage      3093 non-null   float64
 21  avg_fee_to_reward               3093 non-null   float64
 22  number_of_coins_in_circulation  3093 non-null   float64
 23  miner_revenue                   3093 non-null   float64
 24  next_day_closing_price          3093 non-null   float64
dtypes: float64(19), int64(5), str(1)
memory usage: 634.4 KB

In [4]:
df['Date'] = pd.to_datetime(df['Date'])

df = df.sort_values('Date')

df.head()

,Date,opening_price,highest_price,lowest_price,closing_price,transactions_in_blockchain,avg_block_size,sent_by_adress,avg_mining_difficulty,avg_hashrate,...,avg_transaction_value,median_transaction_value,tweets,google_trends,active_addresses,top100_to_total_percentage,avg_fee_to_reward,number_of_coins_in_circulation,miner_revenue,next_day_closing_price
0,2013-04-01,93.0,106.0,92.2,104.0,52572,139256,48809,6695826,6.550211e+13,...,2592.0,64.987,8193.0,15.248,75756.0,19.962,0.867,10975275.0,481891.360000,118.0
1,2013-04-02,104.0,118.4,99.0,118.0,63095,175443,62276,6695826,6.184560e+13,...,4400.0,94.955,8193.0,17.192,91875.0,20.024,1.338,10988125.0,531299.503749,135.0
2,2013-04-03,118.0,147.0,110.0,135.0,63766,184209,69174,6695826,6.027037e+13,...,4478.0,102.533,8193.0,26.608,107142.0,19.987,1.596,10986575.0,538423.880210,132.1
3,2013-04-04,135.0,142.1,116.4,132.1,66738,221568,71753,6695826,5.527246e+13,...,4249.0,123.314,8193.0,24.681,108890.0,19.990,1.948,10995725.0,525157.600000,142.3
4,2013-04-05,132.1,144.9,130.2,142.3,61215,190067,69310,7005058,5.181545e+13,...,4348.0,125.183,8193.0,20.514,100034.0,19.833,1.432,10999925.0,606454.781556,142.6

In [8]:
df.head()

,Date,opening_price,highest_price,lowest_price,closing_price,transactions_in_blockchain,avg_block_size,sent_by_adress,avg_mining_difficulty,avg_hashrate,...,avg_transaction_value,median_transaction_value,tweets,google_trends,active_addresses,top100_to_total_percentage,avg_fee_to_reward,number_of_coins_in_circulation,miner_revenue,next_day_closing_price
0,2013-04-01,93.0,106.0,92.2,104.0,52572,139256,48809,6695826,6.550211e+13,...,2592.0,64.987,8193.0,15.248,75756.0,19.962,0.867,10975275.0,481891.360000,118.0
1,2013-04-02,104.0,118.4,99.0,118.0,63095,175443,62276,6695826,6.184560e+13,...,4400.0,94.955,8193.0,17.192,91875.0,20.024,1.338,10988125.0,531299.503749,135.0
2,2013-04-03,118.0,147.0,110.0,135.0,63766,184209,69174,6695826,6.027037e+13,...,4478.0,102.533,8193.0,26.608,107142.0,19.987,1.596,10986575.0,538423.880210,132.1
3,2013-04-04,135.0,142.1,116.4,132.1,66738,221568,71753,6695826,5.527246e+13,...,4249.0,123.314,8193.0,24.681,108890.0,19.990,1.948,10995725.0,525157.600000,142.3
4,2013-04-05,132.1,144.9,130.2,142.3,61215,190067,69310,7005058,5.181545e+13,...,4348.0,125.183,8193.0,20.514,100034.0,19.833,1.432,10999925.0,606454.781556,142.6

In [12]:

dir()

['In',
 'KMeans',
 'Out',
 'RandomForestRegressor',
 'SentimentIntensityAnalyzer',
 'StandardScaler',
 '_',
 '_2',
 '_4',
 '_8',
 '__',
 '___',
 '__builtin__',
 '__builtins__',
 '__doc__',
 '__loader__',
 '__name__',
 '__package__',
 '__session__',
 '__spec__',
 '_dh',
 '_i',
 '_i1',
 '_i10',
 '_i11',
 '_i12',
 '_i2',
 '_i3',
 '_i4',
 '_i5',
 '_i6',
 '_i7',
 '_i8',
 '_i9',
 '_ih',
 '_ii',
 '_iii',
 '_oh',
 'df',
 'exit',
 'features',
 'get_ipython',
 'mean_absolute_error',
 'mean_squared_error',
 'nltk',
 'np',
 'open',
 'pd',
 'plt',
 'quit',
 'scaler',
 'sns',
 'train_test_split',
 'warnings']