In [1]:
import pandas as pd
import numpy as np

from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder, StandardScaler
from sklearn.linear_model import LogisticRegression
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix

In [2]:
df = pd.read_csv("Cars93_miss.csv")

df.head()

,Manufacturer,Model,Type,Min.Price,Price,Max.Price,MPG.city,MPG.highway,AirBags,DriveTrain,...,Passengers,Length,Wheelbase,Width,Turn.circle,Rear.seat.room,Luggage.room,Weight,Origin,Make
0,Acura,Integra,Small,12.9,15.9,18.8,25.0,31.0,NaN,Front,...,5.0,177.0,102.0,68.0,37.0,26.5,NaN,2705.0,non-USA,Acura Integra
1,NaN,Legend,Midsize,29.2,33.9,38.7,18.0,25.0,Driver & Passenger,Front,...,5.0,195.0,115.0,71.0,38.0,30.0,15.0,3560.0,non-USA,Acura Legend
2,Audi,90,Compact,25.9,29.1,32.3,20.0,26.0,Driver only,Front,...,5.0,180.0,102.0,67.0,37.0,28.0,14.0,3375.0,non-USA,Audi 90
3,Audi,100,Midsize,NaN,37.7,44.6,19.0,26.0,Driver & Passenger,NaN,...,6.0,193.0,106.0,NaN,37.0,31.0,17.0,3405.0,non-USA,Audi 100
4,BMW,535i,Midsize,NaN,30.0,NaN,22.0,30.0,NaN,Rear,...,4.0,186.0,109.0,69.0,39.0,27.0,13.0,3640.0,non-USA,BMW 535i

In [3]:
print(df.shape)
print(df.info())
print(df.isnull().sum())

(93, 27)
<class 'pandas.DataFrame'>
RangeIndex: 93 entries, 0 to 92
Data columns (total 27 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   Manufacturer        89 non-null     str
 1   Model               92 non-null     str
 2   Type                90 non-null     str
 3   Min.Price           86 non-null     float64
 4   Price               91 non-null     float64
 5   Max.Price           88 non-null     float64
 6   MPG.city            84 non-null     float64
 7   MPG.highway         91 non-null     float64
 8   AirBags             55 non-null     str
 9   DriveTrain          86 non-null     str
 10  Cylinders           88 non-null     str
 11  EngineSize          91 non-null     float64
 12  Horsepower          86 non-null     float64
 13  RPM                 90 non-null     float64
 14  Rev.per.mile        87 non-null     float64
 15  Man.trans.avail     88 non-null     str
 16  Fuel.tank.capacity  85 non-null     float64
 17  Passengers          91 non-null     float64
 18  Length              89 non-null     float64
 19  Wheelbase           92 non-null     float64
 20  Width               87 non-null     float64
 21  Turn.circle         88 non-null     float64
 22  Rear.seat.room      89 non-null     float64
 23  Luggage.room        74 non-null     float64
 24  Weight              86 non-null     float64
 25  Origin              88 non-null     str
 26  Make                90 non-null     str
dtypes: float64(18), str(9)
memory usage: 24.5 KB
None
Manufacturer           4
Model                  1
Type                   3
Min.Price              7
Price                  2
Max.Price              5
MPG.city               9
MPG.highway            2
AirBags               38
DriveTrain             7
Cylinders              5
EngineSize             2
Horsepower             7
RPM                    3
Rev.per.mile           6
Man.trans.avail        5
Fuel.tank.capacity     8
Passengers             2
Length                 4
Wheelbase              1
Width                  6
Turn.circle            5
Rear.seat.room         4
Luggage.room          19
Weight                 7
Origin                 5
Make                   3
dtype: int64

In [5]:
df.select_dtypes(include="object")

/var/folders/88/w4w1n8l12kd_z42_6mrnndmw0000gn/T/ipykernel_5263/755674511.py:1: Pandas4Warning: For backward compatibility, 'str' dtypes are included by select_dtypes when 'object' dtype is specified. This behavior is deprecated and will be removed in a future version. Explicitly pass 'str' to `include` to select them, or to `exclude` to remove them and silence this warning.
See https://pandas.pydata.org/docs/user_guide/migration-3-strings.html#string-migration-select-dtypes for details on how to write code that works with pandas 2 and 3.
  df.select_dtypes(include="object")

,Manufacturer,Model,Type,AirBags,DriveTrain,Cylinders,Man.trans.avail,Origin,Make
0,Acura,Integra,Small,NaN,Front,4,Yes,non-USA,Acura Integra
1,NaN,Legend,Midsize,Driver & Passenger,Front,6,Yes,non-USA,Acura Legend
2,Audi,90,Compact,Driver only,Front,6,Yes,non-USA,Audi 90
3,Audi,100,Midsize,Driver & Passenger,NaN,6,NaN,non-USA,Audi 100
4,BMW,535i,Midsize,NaN,Rear,4,Yes,non-USA,BMW 535i
...,...,...,...,...,...,...,...,...,...
88,Volkswagen,Eurovan,Van,NaN,Front,5,Yes,NaN,Volkswagen Eurovan
89,Volkswagen,Passat,Compact,NaN,Front,4,Yes,non-USA,Volkswagen Passat
90,Volkswagen,Corrado,Sporty,NaN,Front,6,Yes,non-USA,Volkswagen Corrado
91,Volvo,240,Compact,Driver only,Rear,NaN,Yes,non-USA,Volvo 240
92,NaN,850,Midsize,Driver & Passenger,Front,5,Yes,non-USA,Volvo 850

In [6]:
df["HighPrice"] = (df["Price"] > df["Price"].median()).astype(int)

In [9]:
df.head()

,Manufacturer,Model,Type,Min.Price,Price,Max.Price,MPG.city,MPG.highway,AirBags,DriveTrain,...,Length,Wheelbase,Width,Turn.circle,Rear.seat.room,Luggage.room,Weight,Origin,Make,HighPrice
0,0,47,3,12.9,15.9,18.8,25.0,31.0,2,1,...,177.0,102.0,68.0,37.0,26.5,NaN,2705.0,1,0,0
1,31,54,2,29.2,33.9,38.7,18.0,25.0,0,1,...,195.0,115.0,71.0,38.0,30.0,15.0,3560.0,1,1,1
2,1,8,0,25.9,29.1,32.3,20.0,26.0,1,1,...,180.0,102.0,67.0,37.0,28.0,14.0,3375.0,1,3,1
3,1,0,2,NaN,37.7,44.6,19.0,26.0,0,3,...,193.0,106.0,NaN,37.0,31.0,17.0,3405.0,1,2,1
4,2,5,2,NaN,30.0,NaN,22.0,30.0,2,2,...,186.0,109.0,69.0,39.0,27.0,13.0,3640.0,1,4,1

In [10]:
X = df.drop(columns=["HighPrice"])
y = df["HighPrice"]

In [11]:
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42
)

In [12]:
scaler = StandardScaler()

X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)

In [14]:
print(df.isnull().sum())

Manufacturer           0
Model                  0
Type                   0
Min.Price              7
Price                  2
Max.Price              5
MPG.city               9
MPG.highway            2
AirBags                0
DriveTrain             0
Cylinders              0
EngineSize             2
Horsepower             7
RPM                    3
Rev.per.mile           6
Man.trans.avail        0
Fuel.tank.capacity     8
Passengers             2
Length                 4
Wheelbase              1
Width                  6
Turn.circle            5
Rear.seat.room         4
Luggage.room          19
Weight                 7
Origin                 0
Make                   0
HighPrice              0
dtype: int64