In [1]:
!pip install pandas numpy matplotlib seaborn scikit-learn nltk wordcloud

import pandas as pd
import numpy as np

import matplotlib.pyplot as plt
import seaborn as sns

from sklearn.cluster import KMeans
from sklearn.preprocessing import StandardScaler
from sklearn.feature_extraction.text import TfidfVectorizer

from nltk.corpus import stopwords
import nltk
nltk.download('stopwords')

from wordcloud import WordCloud

Requirement already satisfied: pandas in ./miniconda3/envs/coding/lib/python3.12/site-packages (3.0.3)
Requirement already satisfied: numpy in ./miniconda3/envs/coding/lib/python3.12/site-packages (2.5.0)
Requirement already satisfied: matplotlib in ./miniconda3/envs/coding/lib/python3.12/site-packages (3.11.0)
Requirement already satisfied: seaborn in ./miniconda3/envs/coding/lib/python3.12/site-packages (0.13.2)
Requirement already satisfied: scikit-learn in ./miniconda3/envs/coding/lib/python3.12/site-packages (1.9.0)
Requirement already satisfied: nltk in ./miniconda3/envs/coding/lib/python3.12/site-packages (3.9.2)
Requirement already satisfied: wordcloud in ./miniconda3/envs/coding/lib/python3.12/site-packages (1.9.6)
Requirement already satisfied: python-dateutil>=2.8.2 in ./miniconda3/envs/coding/lib/python3.12/site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: contourpy>=1.0.1 in ./miniconda3/envs/coding/lib/python3.12/site-packages (from matplotlib) (1.3.3)
Requirement already satisfied: cycler>=0.10 in ./miniconda3/envs/coding/lib/python3.12/site-packages (from matplotlib) (0.12.1)
Requirement already satisfied: fonttools>=4.22.0 in ./miniconda3/envs/coding/lib/python3.12/site-packages (from matplotlib) (4.63.0)
Requirement already satisfied: kiwisolver>=1.3.1 in ./miniconda3/envs/coding/lib/python3.12/site-packages (from matplotlib) (1.5.0)
Requirement already satisfied: packaging>=20.0 in ./miniconda3/envs/coding/lib/python3.12/site-packages (from matplotlib) (26.2)
Requirement already satisfied: pillow>=9 in ./miniconda3/envs/coding/lib/python3.12/site-packages (from matplotlib) (12.2.0)
Requirement already satisfied: pyparsing>=3 in ./miniconda3/envs/coding/lib/python3.12/site-packages (from matplotlib) (3.3.2)
Requirement already satisfied: scipy>=1.10.0 in ./miniconda3/envs/coding/lib/python3.12/site-packages (from scikit-learn) (1.18.0)
Requirement already satisfied: joblib>=1.4.0 in ./miniconda3/envs/coding/lib/python3.12/site-packages (from scikit-learn) (1.5.3)
Requirement already satisfied: narwhals>=2.0.1 in ./miniconda3/envs/coding/lib/python3.12/site-packages (from scikit-learn) (2.22.1)
Requirement already satisfied: threadpoolctl>=3.5.0 in ./miniconda3/envs/coding/lib/python3.12/site-packages (from scikit-learn) (3.6.0)
Requirement already satisfied: click in ./miniconda3/envs/coding/lib/python3.12/site-packages (from nltk) (8.1.8)
Requirement already satisfied: regex>=2021.8.3 in ./miniconda3/envs/coding/lib/python3.12/site-packages (from nltk) (2025.10.23)
Requirement already satisfied: tqdm in ./miniconda3/envs/coding/lib/python3.12/site-packages (from nltk) (4.67.1)
Requirement already satisfied: six>=1.5 in ./miniconda3/envs/coding/lib/python3.12/site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)

[nltk_data] Downloading package stopwords to
[nltk_data]     /Users/adnanaltimeemy/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!

In [2]:
df = pd.read_csv("Chennai_Zomato_Data-scraped.csv")

df.head()

,Zomato URL,Name of Restaurant,Address,Location,Cuisine,Top Dishes,Price for 2,Ratings,No of Votes
0,https://www.zomato.com/chennai/the-black-pearl...,The Black Pearl,"Plot 155, 292/132, Ground Floor, Rajiv Gandhi...",Sholinganallur,"North Indian, European, Mediterranean, Contine...","Fish,Pizza,Prawn,Jalebi,Pav Bhaji,Chaat,Mocktails",1500,4.9,2857
1,https://www.zomato.com/chennai/coal-barbecues-...,Coal Barbecues,"40, 2nd Floor, Bazullah Road, T. Nagar, Chennai",T. Nagar,"North Indian, Mediterranean, Asian, Arabian, BBQ","Chicken Honey,Pizza,Fish,Kulfi,Chicken Wings,P...",1400,4.9,7320
2,https://www.zomato.com/chennai/palmshore-medav...,Palmshore,"4/581 A, Velachery Main Road, Senthamizh Naga...",Medavakkam,"North Indian, Chinese, Arabian","Biryani,Faluda,Fish,Bbq Chicken,Mutton Mandi,B...",700,4.5,441
3,https://www.zomato.com/chennai/fromage-mrc-nagar,Fromage,"Somerset Greenway, Lords Avenue, MRC Nagar, C...",MRC Nagar,"Cafe, Italian, French, European","Pasta,Pork Ribs,Chicken Steak,Chocolate Cake,B...",1000,4.5,1073
4,https://www.zomato.com/chennai/savoury-sea-she...,Savoury Sea Shell,"3, E Block, 3rd Avenue, Anna Nagar East, Chennai",Anna Nagar East,"Arabian, Chinese, North Indian, Lebanese, Salad","Shawarma,Chicken Grill,Brownie,Sea Food,Bbq Ch...",1400,4.1,2446

In [3]:
df.info()

# remove duplicates
df = df.drop_duplicates()

# check missing values
df.isnull().sum()

<class 'pandas.DataFrame'>
RangeIndex: 7442 entries, 0 to 7441
Data columns (total 9 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   Zomato URL          7442 non-null   str
 1   Name of Restaurant  7442 non-null   str
 2   Address             7442 non-null   str
 3   Location            7442 non-null   str
 4   Cuisine             7442 non-null   str
 5   Top Dishes          7442 non-null   str
 6   Price for 2         7442 non-null   int64
 7   Ratings             7442 non-null   str
 8   No of Votes         7442 non-null   str
dtypes: int64(1), str(8)
memory usage: 1.9 MB

Zomato URL            0
Name of Restaurant    0
Address               0
Location              0
Cuisine               0
Top Dishes            0
Price for 2           0
Ratings               0
No of Votes           0
dtype: int64

In [5]:

df.head()

,Zomato URL,Name of Restaurant,Address,Location,Cuisine,Top Dishes,Price for 2,Ratings,No of Votes
0,https://www.zomato.com/chennai/the-black-pearl...,The Black Pearl,"Plot 155, 292/132, Ground Floor, Rajiv Gandhi...",Sholinganallur,"North Indian, European, Mediterranean, Contine...","Fish,Pizza,Prawn,Jalebi,Pav Bhaji,Chaat,Mocktails",1500,4.9,2857
1,https://www.zomato.com/chennai/coal-barbecues-...,Coal Barbecues,"40, 2nd Floor, Bazullah Road, T. Nagar, Chennai",T. Nagar,"North Indian, Mediterranean, Asian, Arabian, BBQ","Chicken Honey,Pizza,Fish,Kulfi,Chicken Wings,P...",1400,4.9,7320
2,https://www.zomato.com/chennai/palmshore-medav...,Palmshore,"4/581 A, Velachery Main Road, Senthamizh Naga...",Medavakkam,"North Indian, Chinese, Arabian","Biryani,Faluda,Fish,Bbq Chicken,Mutton Mandi,B...",700,4.5,441
3,https://www.zomato.com/chennai/fromage-mrc-nagar,Fromage,"Somerset Greenway, Lords Avenue, MRC Nagar, C...",MRC Nagar,"Cafe, Italian, French, European","Pasta,Pork Ribs,Chicken Steak,Chocolate Cake,B...",1000,4.5,1073
4,https://www.zomato.com/chennai/savoury-sea-she...,Savoury Sea Shell,"3, E Block, 3rd Avenue, Anna Nagar East, Chennai",Anna Nagar East,"Arabian, Chinese, North Indian, Lebanese, Salad","Shawarma,Chicken Grill,Brownie,Sea Food,Bbq Ch...",1400,4.1,2446

In [7]:
print(df.columns)

Index(['Zomato URL', 'Name of Restaurant', 'Address', 'Location', 'Cuisine',
       'Top Dishes', 'Price for 2', 'Ratings', 'No of Votes'],
      dtype='str')

In [9]:
print(df.columns.tolist())

['Zomato URL', 'Name of Restaurant', 'Address', 'Location', 'Cuisine', 'Top Dishes', 'Price for 2', 'Ratings', 'No of Votes']

In [11]:
for col in df.columns:
    print(repr(col))

'Zomato URL'
'Name of Restaurant'
'Address'
'Location'
'Cuisine'
'Top Dishes'
'Price for 2'
'Ratings'
'No of Votes'

In [13]:
print(df.columns.tolist())

['Zomato URL', 'Name of Restaurant', 'Address', 'Location', 'Cuisine', 'Top Dishes', 'Price for 2', 'Ratings', 'No of Votes']