In [1]:
import pandas as pd
import numpy as np

from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier

from sklearn.metrics import accuracy_score, classification_report, confusion_matrix
import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
df = pd.read_csv("chocolates.csv")

df.head()

,Name,MFR,Country,Type,Calories,CalFat,TotFat,SatFat,Chol,Na,Carbs,Fiber,Sugars,Protein
0,Noir 86% Cacao,Cote D'Or,Belgium,Dark,460.000000,380.000000,44.000000,26.000000,0.0,0.000000,28.000000,10.000000,10.000000,8.000000
1,70% Cocoa,Cote D'Or,Belgium,Dark,600.000000,432.000000,48.000000,30.000000,10.0,0.000000,42.000000,10.000000,28.000000,8.000000
2,Solid Dark Chocolate Bar,Godiva,Belgium,Dark,534.883721,302.325581,32.558140,20.930233,0.0,0.000000,60.465116,9.302326,46.511628,6.976744
3,72% Extra Dark Chocolate,Godiva,Belgium,Dark,534.883721,348.837209,39.534884,20.930233,0.0,81.395349,41.860465,13.953488,27.906977,9.302326
4,Extra Dark Chocolate Bar,Guylian,Belgium,Dark,575.757576,333.333333,39.393939,24.242424,0.0,90.909091,48.484848,12.121212,33.333333,9.090909

In [3]:
print(df.shape)
print(df.info())
print(df.describe())
print(df.isnull().sum())

(88, 14)
<class 'pandas.DataFrame'>
RangeIndex: 88 entries, 0 to 87
Data columns (total 14 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   Name      88 non-null     str
 1   MFR       88 non-null     str
 2   Country   88 non-null     str
 3   Type      88 non-null     str
 4   Calories  88 non-null     float64
 5   CalFat    88 non-null     float64
 6   TotFat    88 non-null     float64
 7   SatFat    88 non-null     float64
 8   Chol      88 non-null     float64
 9   Na        88 non-null     float64
 10  Carbs     88 non-null     float64
 11  Fiber     88 non-null     float64
 12  Sugars    88 non-null     float64
 13  Protein   88 non-null     float64
dtypes: float64(10), str(4)
memory usage: 13.2 KB
None
         Calories      CalFat     TotFat     SatFat       Chol          Na  \
count   88.000000   88.000000  88.000000  88.000000  88.000000   88.000000
mean   542.187749  326.182592  36.892248  21.083966   8.154445   40.633854
std     61.659179   75.675020   7.608446   7.224589   9.434814   44.524722
min    270.000000    0.000000  16.500000   0.000000   0.000000    0.000000
25%    511.627907  284.738676  31.926829  18.536822   0.000000    0.000000
50%    546.060606  325.000000  36.181818  21.083966   6.516247   32.593376
75%    575.757576  370.500000  42.000000  25.581395  13.522669   72.321429
max    744.186047  550.000000  62.500000  35.000000  34.883721  191.326531

           Carbs      Fiber     Sugars    Protein
count  88.000000  88.000000  88.000000  88.000000
mean   49.924797   5.539874  37.414004   7.233327
std    13.388882   4.044959  17.367156   1.797007
min     4.000000   0.000000   0.000000   4.000000
25%    44.052632   2.277904  27.066667   5.928571
50%    52.631579   5.320957  44.868421   7.050000
75%    58.541667   9.143763  51.219512   8.156081
max    74.418605  16.279070  70.731707  11.627907
Name        0
MFR         0
Country     0
Type        0
Calories    0
CalFat      0
TotFat      0
SatFat      0
Chol        0
Na          0
Carbs       0
Fiber       0
Sugars      0
Protein     0
dtype: int64

In [4]:
df = df.dropna()

In [6]:
[target for target in df.columns if "target" in target.lower()]

[]

In [8]:
df.head()

,Name,MFR,Country,Type,Calories,CalFat,TotFat,SatFat,Chol,Na,Carbs,Fiber,Sugars,Protein
0,Noir 86% Cacao,Cote D'Or,Belgium,Dark,460.000000,380.000000,44.000000,26.000000,0.0,0.000000,28.000000,10.000000,10.000000,8.000000
1,70% Cocoa,Cote D'Or,Belgium,Dark,600.000000,432.000000,48.000000,30.000000,10.0,0.000000,42.000000,10.000000,28.000000,8.000000
2,Solid Dark Chocolate Bar,Godiva,Belgium,Dark,534.883721,302.325581,32.558140,20.930233,0.0,0.000000,60.465116,9.302326,46.511628,6.976744
3,72% Extra Dark Chocolate,Godiva,Belgium,Dark,534.883721,348.837209,39.534884,20.930233,0.0,81.395349,41.860465,13.953488,27.906977,9.302326
4,Extra Dark Chocolate Bar,Guylian,Belgium,Dark,575.757576,333.333333,39.393939,24.242424,0.0,90.909091,48.484848,12.121212,33.333333,9.090909

In [11]:
'rf_model' in globals()

False