In [1]:
import pandas as pd
import numpy as np

import matplotlib.pyplot as plt
import seaborn as sns

from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.linear_model import LogisticRegression
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix

In [2]:
df = pd.read_csv("Coca-Cola_stock_history.csv")

df.head()

         Date  Adj Close     Close      High       Low      Open   Volume
0  1962-01-02   0.044744  0.263021  0.270182  0.263021  0.263021   806400
1  1962-01-03   0.043747  0.257161  0.259115  0.253255  0.259115  1574400
2  1962-01-04   0.044080  0.259115  0.261068  0.257813  0.257813   844800
3  1962-01-05   0.043083  0.253255  0.262370  0.252604  0.259115  1420800
4  1962-01-08   0.042640  0.250651  0.251302  0.245768  0.251302  2035200

In [3]:
# Check missing values
print(df.isnull().sum())

# Convert Date column if exists
if 'Date' in df.columns:
    df['Date'] = pd.to_datetime(df['Date'])
    df = df.sort_values('Date')

Date         0
Adj Close    0
Close        0
High         0
Low          0
Open         0
Volume       0
dtype: int64

In [4]:
df['Target'] = (df['Close'].shift(-1) > df['Close']).astype(int)

df = df.dropna()
df.head()

,Date,Adj Close,Close,High,Low,Open,Volume,Target
0,1962-01-02,0.044744,0.263021,0.270182,0.263021,0.263021,806400,0
1,1962-01-03,0.043747,0.257161,0.259115,0.253255,0.259115,1574400,1
2,1962-01-04,0.044080,0.259115,0.261068,0.257813,0.257813,844800,0
3,1962-01-05,0.043083,0.253255,0.262370,0.252604,0.259115,1420800,0
4,1962-01-08,0.042640,0.250651,0.251302,0.245768,0.251302,2035200,1

In [5]:
features = ['Open', 'High', 'Low', 'Close', 'Volume']

X = df[features]
y = df['Target']

In [6]:
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42, shuffle=False
)

In [7]:
scaler = StandardScaler()

X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)

In [8]:
log_model = LogisticRegression()
log_model.fit(X_train_scaled, y_train)

y_pred_log = log_model.predict(X_test_scaled)

print("Logistic Regression Accuracy:", accuracy_score(y_test, y_pred_log))
print(classification_report(y_test, y_pred_log))

Logistic Regression Accuracy: 0.5210135970333746
              precision    recall  f1-score   support

           0       0.55      0.03      0.05      1558
           1       0.52      0.98      0.68      1678

    accuracy                           0.52      3236
   macro avg       0.54      0.50      0.36      3236
weighted avg       0.54      0.52      0.38      3236

In [10]:
features = ['Open', 'High', 'Low', 'Close', 'Volume', 'Return', 'Lag1', 'Lag2']