In [1]:
import pandas as pd
import numpy as np

from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder
from sklearn.tree import DecisionTreeRegressor
from sklearn.ensemble import RandomForestRegressor

from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score

In [2]:
df = pd.read_csv("Cubitthouse.csv")

df.head()

          site  ...                                    web
0  Cubitthouse  ...           https://www.theorange.co.uk/
1  Cubitthouse  ...      https://www.thegrazinggoat.co.uk/
2  Cubitthouse  ...   https://www.thealfredtennyson.co.uk/
3  Cubitthouse  ...     https://www.thebeaubrummell.co.uk/
4  Cubitthouse  ...  https://www.thecoachmakersarms.co.uk/

[5 rows x 9 columns]

In [3]:
print(df.shape)
print(df.info())
print(df.describe())
print(df.isnull().sum())

(9, 9)
<class 'pandas.DataFrame'>
RangeIndex: 9 entries, 0 to 8
Data columns (total 9 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   site     9 non-null      str
 1   lat      9 non-null      float64
 2   lng      9 non-null      float64
 3   zip      0 non-null      float64
 4   name     9 non-null      str
 5   address  9 non-null      str
 6   phone    9 non-null      str
 7   email    9 non-null      str
 8   web      9 non-null      str
dtypes: float64(3), str(6)
memory usage: 2.1 KB
None
             lat       lng  zip
count   9.000000  9.000000  0.0
mean   51.504786 -0.157151  NaN
std     0.011494  0.016614  NaN
min    51.489194 -0.194173  NaN
25%    51.493714 -0.158179  NaN
50%    51.509026 -0.152355  NaN
75%    51.515275 -0.150826  NaN
max    51.517134 -0.133079  NaN
site       0
lat        0
lng        0
zip        9
name       0
address    0
phone      0
email      0
web        0
dtype: int64

In [5]:
cat_cols = df.select_dtypes(include=["object", "string"]).columns

In [7]:
df.select_dtypes(include="object")

Empty DataFrame
Columns: []
Index: [0, 1, 2, 3, 4, 5, 6, 7, 8]

In [10]:
df.head()

   site        lat       lng  zip  name  address  phone  email  web
0     0  51.490630 -0.152355  NaN     6        3      4      7    7
1     0  51.515275 -0.158179  NaN     5        6      1      6    6
2     0  51.499574 -0.156376  NaN     0        0      3      2    2
3     0  51.509026 -0.133079  NaN     2        2      5      3    3
4     0  51.517134 -0.150695  NaN     4        8      0      5    5

In [12]:
print(locals().keys())

dict_keys(['__name__', '__doc__', '__package__', '__loader__', '__spec__', '__builtin__', '__builtins__', '_ih', '_oh', '_dh', 'In', 'Out', 'get_ipython', 'exit', 'quit', 'open', '_', '__', '___', '__session__', '_i', '_ii', '_iii', '_i1', 'pd', 'np', 'train_test_split', 'LabelEncoder', 'DecisionTreeRegressor', 'RandomForestRegressor', 'mean_absolute_error', 'mean_squared_error', 'r2_score', '_i2', 'df', '_2', '_i3', '_i4', 'col', '_i5', 'cat_cols', '_i6', 'label_encoders', 'le', '_i7', '_7', '_i8', '_i9', '_i10', '_10', '_i11', 'dt_model', '_i12'])

In [15]:
df.head()
df.columns

Index(['site', 'lat', 'lng', 'zip', 'name', 'address', 'phone', 'email',
       'web'],
      dtype='str')

In [17]:
df.head()
df.columns

Index(['site', 'lat', 'lng', 'zip', 'name', 'address', 'phone', 'email',
       'web'],
      dtype='str')

In [20]:
print("y_test exists:", "y_test" in globals())
print("dt_preds exists:", "dt_preds" in globals())
print("rf_preds exists:", "rf_preds" in globals())

y_test exists: False
dt_preds exists: False
rf_preds exists: False