In [1]:
import pandas as pd
import numpy as np

from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier

from sklearn.metrics import accuracy_score, classification_report, confusion_matrix

In [2]:
df = pd.read_csv("DirtyMartini.csv")

df.head()

           site        lat  ...                              email web
0  DirtyMartini  51.517163  ...    bishopsgate@dirtymartini.uk.com NaN
1  DirtyMartini  51.512164  ...   coventgarden@dirtymartini.uk.com NaN
2  DirtyMartini  51.514467  ...  hanoversquare@dirtymartini.uk.com NaN
3  DirtyMartini  51.536304  ...      islington@dirtymartini.uk.com NaN
4  DirtyMartini  51.510443  ...       monument@dirtymartini.uk.com NaN

[5 rows x 9 columns]

In [3]:
print(df.shape)
print(df.info())
print(df.describe())
print(df.isnull().sum())

(11, 9)
<class 'pandas.DataFrame'>
RangeIndex: 11 entries, 0 to 10
Data columns (total 9 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   site     11 non-null     str
 1   lat      11 non-null     float64
 2   lng      11 non-null     float64
 3   zip      11 non-null     str
 4   name     11 non-null     str
 5   address  11 non-null     str
 6   phone    11 non-null     str
 7   email    11 non-null     str
 8   web      0 non-null      float64
dtypes: float64(3), str(6)
memory usage: 2.3 KB
None
             lat        lng  web
count  11.000000  11.000000  0.0
mean   51.981182  -1.100206  NaN
std     0.872511   1.210887  NaN
min    51.454559  -3.177346  NaN
25%    51.511303  -2.076147  NaN
50%    51.514547  -0.143416  NaN
75%    52.008306  -0.099248  NaN
max    53.797751  -0.080695  NaN
site        0
lat         0
lng         0
zip         0
name        0
address     0
phone       0
email       0
web        11
dtype: int64

In [11]:
import numpy as np
import pandas as pd

num_cols = df.select_dtypes(include=["number"]).columns
cat_cols = df.select_dtypes(include=["object", "string"]).columns

In [13]:
df = df.convert_dtypes()

In [15]:
df.columns = df.columns.str.strip()

In [18]:
df.head()
df.columns

Index(['site', 'lat', 'lng', 'zip', 'name', 'address', 'phone', 'email',
       'web'],
      dtype='str')

In [20]:
df.head()
df.columns

Index(['site', 'lat', 'lng', 'zip', 'name', 'address', 'phone', 'email',
       'web'],
      dtype='str')

In [23]:
target_column = "Survived"

In [25]:
df.head()

   site        lat       lng  zip  name  address  phone  email   web
0     0  51.517163 -0.080695    3     0        4      4      2  <NA>
1     0  51.512164 -0.121796   10     3        6      6      4  <NA>
2     0  51.514467 -0.143416    9     4        7      5      5  <NA>
3     0  51.536304 -0.103841    8     5        8      8      6  <NA>
4     0  51.510443  -0.08396    5     6        9      7      9  <NA>