In [1]:
import pandas as pd
import numpy as np

from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder, OneHotEncoder
from sklearn.compose import ColumnTransformer
from sklearn.pipeline import Pipeline

from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier

from sklearn.metrics import accuracy_score, classification_report, confusion_matrix

In [2]:
df = pd.read_csv("disney_movie_data_final.csv")

df.head()

   Unnamed: 0                            title  ... Traditional Simplified
0           0          Academy Award Review of  ...         NaN        NaN
1           1  Snow White and the Seven Dwarfs  ...         NaN        NaN
2           2                        Pinocchio  ...         NaN        NaN
3           3                         Fantasia  ...         NaN        NaN
4           4             The Reluctant Dragon  ...         NaN        NaN

[5 rows x 32 columns]

In [3]:
print(df.shape)
print(df.info())
print(df.isnull().sum())

(432, 32)
<class 'pandas.DataFrame'>
RangeIndex: 432 entries, 0 to 431
Data columns (total 32 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   Unnamed: 0               432 non-null    int64
 1   title                    432 non-null    str
 2   Production company       392 non-null    str
 3   Release date             431 non-null    str
 4   Running time             422 non-null    str
 5   Country                  428 non-null    str
 6   Language                 430 non-null    str
 7   Running time (int)       422 non-null    float64
 8   Budget (float)           273 non-null    float64
 9   Box office (float)       355 non-null    float64
 10  Release date (datetime)  428 non-null    str
 11  imdb                     416 non-null    float64
 12  metascore                283 non-null    float64
 13  rotten_tomatoes          361 non-null    str
 14  Directed by              431 non-null    str
 15  Produced by              422 non-null    str
 16  Written by               203 non-null    str
 17  Based on                 211 non-null    str
 18  Starring                 398 non-null    str
 19  Music by                 422 non-null    str
 20  Distributed by           429 non-null    str
 21  Budget                   276 non-null    str
 22  Box office               359 non-null    str
 23  Story by                 139 non-null    str
 24  Narrated by              55 non-null     str
 25  Cinematography           342 non-null    str
 26  Edited by                395 non-null    str
 27  Screenplay by            191 non-null    str
 28  Production companies     39 non-null     str
 29  Adaptation by            1 non-null      str
 30  Traditional              1 non-null      str
 31  Simplified               1 non-null      str
dtypes: float64(5), int64(1), str(26)
memory usage: 311.6 KB
None
Unnamed: 0                   0
title                        0
Production company          40
Release date                 1
Running time                10
Country                      4
Language                     2
Running time (int)          10
Budget (float)             159
Box office (float)          77
Release date (datetime)      4
imdb                        16
metascore                  149
rotten_tomatoes             71
Directed by                  1
Produced by                 10
Written by                 229
Based on                   221
Starring                    34
Music by                    10
Distributed by               3
Budget                     156
Box office                  73
Story by                   293
Narrated by                377
Cinematography              90
Edited by                   37
Screenplay by              241
Production companies       393
Adaptation by              431
Traditional                431
Simplified                 431
dtype: int64

In [5]:
num_cols = df.select_dtypes(include="number").columns
df[num_cols] = df[num_cols].fillna(df[num_cols].median())

cat_cols = df.select_dtypes(include=["object", "string"]).columns
df[cat_cols] = df[cat_cols].fillna(df[cat_cols].mode().iloc[0])

In [9]:
print(df.head())
print(df.columns)

   Unnamed: 0                            title  ... Traditional Simplified
0           0          Academy Award Review of  ...     我們誕生在中國    我们诞生在中国
1           1  Snow White and the Seven Dwarfs  ...     我們誕生在中國    我们诞生在中国
2           2                        Pinocchio  ...     我們誕生在中國    我们诞生在中国
3           3                         Fantasia  ...     我們誕生在中國    我们诞生在中国
4           4             The Reluctant Dragon  ...     我們誕生在中國    我们诞生在中国

[5 rows x 32 columns]
Index(['Unnamed: 0', 'title', 'Production company', 'Release date',
       'Running time', 'Country', 'Language', 'Running time (int)',
       'Budget (float)', 'Box office (float)', 'Release date (datetime)',
       'imdb', 'metascore', 'rotten_tomatoes', 'Directed by', 'Produced by',
       'Written by', 'Based on', 'Starring', 'Music by', 'Distributed by',
       'Budget', 'Box office', 'Story by', 'Narrated by', 'Cinematography',
       'Edited by', 'Screenplay by', 'Production companies', 'Adaptation by',
       'Traditional', 'Simplified'],
      dtype='str')

In [11]:
print(df.columns)
print(df.head())

Index(['Unnamed: 0', 'title', 'Production company', 'Release date',
       'Running time', 'Country', 'Language', 'Running time (int)',
       'Budget (float)', 'Box office (float)', 'Release date (datetime)',
       'imdb', 'metascore', 'rotten_tomatoes', 'Directed by', 'Produced by',
       'Written by', 'Based on', 'Starring', 'Music by', 'Distributed by',
       'Budget', 'Box office', 'Story by', 'Narrated by', 'Cinematography',
       'Edited by', 'Screenplay by', 'Production companies', 'Adaptation by',
       'Traditional', 'Simplified'],
      dtype='str')
   Unnamed: 0                            title  ... Traditional Simplified
0           0          Academy Award Review of  ...     我們誕生在中國    我们诞生在中国
1           1  Snow White and the Seven Dwarfs  ...     我們誕生在中國    我们诞生在中国
2           2                        Pinocchio  ...     我們誕生在中國    我们诞生在中国
3           3                         Fantasia  ...     我們誕生在中國    我们诞生在中国
4           4             The Reluctant Dragon  ...     我們誕生在中國    我们诞生在中国

[5 rows x 32 columns]

In [16]:
df.columns

Index(['Unnamed: 0', 'title', 'Production company', 'Release date',
       'Running time', 'Country', 'Language', 'Running time (int)',
       'Budget (float)', 'Box office (float)', 'Release date (datetime)',
       'imdb', 'metascore', 'rotten_tomatoes', 'Directed by', 'Produced by',
       'Written by', 'Based on', 'Starring', 'Music by', 'Distributed by',
       'Budget', 'Box office', 'Story by', 'Narrated by', 'Cinematography',
       'Edited by', 'Screenplay by', 'Production companies', 'Adaptation by',
       'Traditional', 'Simplified'],
      dtype='str')

In [20]:
df.head()

   Unnamed: 0                            title  ... Traditional Simplified
0           0          Academy Award Review of  ...     我們誕生在中國    我们诞生在中国
1           1  Snow White and the Seven Dwarfs  ...     我們誕生在中國    我们诞生在中国
2           2                        Pinocchio  ...     我們誕生在中國    我们诞生在中国
3           3                         Fantasia  ...     我們誕生在中國    我们诞生在中国
4           4             The Reluctant Dragon  ...     我們誕生在中國    我们诞生在中国

[5 rows x 32 columns]