In [3]:
import pandas as pd
import numpy as np

from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier

from sklearn.metrics import accuracy_score, classification_report, confusion_matrix
import matplotlib.pyplot as plt
import seaborn as sns

In [4]:
df = pd.read_csv("HRDataset_v9.csv")

df.head()

,Employee Name,Employee Number,MarriedID,MaritalStatusID,GenderID,EmpStatus_ID,DeptID,Perf_ScoreID,Age,Pay Rate,...,Date of Hire,Days Employed,Date of Termination,Reason For Term,Employment Status,Department,Position,Manager Name,Employee Source,Performance Score
0,"Brown, Mia",1103024456,1,1,0,1,1,3,30,28.50,...,10/27/2008,3317,NaN,N/A - still employed,Active,Admin Offices,Accountant I,Brandon R. LeBlanc,Diversity Job Fair,Fully Meets
1,"LaRotonda, William",1106026572,0,2,1,1,1,3,34,23.00,...,1/6/2014,1420,NaN,N/A - still employed,Active,Admin Offices,Accountant I,Brandon R. LeBlanc,Website Banner Ads,Fully Meets
2,"Steans, Tyrone",1302053333,0,0,1,1,1,3,31,29.00,...,9/29/2014,1154,NaN,N/A - still employed,Active,Admin Offices,Accountant I,Brandon R. LeBlanc,Internet Search,Fully Meets
3,"Howard, Estelle",1211050782,1,1,0,1,1,9,32,21.50,...,2/16/2015,58,4/15/2015,N/A - still employed,Active,Admin Offices,Administrative Assistant,Brandon R. LeBlanc,Pay Per Click - Google,N/A- too early to review
4,"Singh, Nan",1307059817,0,0,0,1,1,9,30,16.56,...,5/1/2015,940,NaN,N/A - still employed,Active,Admin Offices,Administrative Assistant,Brandon R. LeBlanc,Website Banner Ads,N/A- too early to review

In [5]:
print(df.shape)
print(df.info())
print(df.describe(include='all'))

(310, 28)
<class 'pandas.DataFrame'>
RangeIndex: 310 entries, 0 to 309
Data columns (total 28 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   Employee Name        310 non-null    str
 1   Employee Number      310 non-null    int64
 2   MarriedID            310 non-null    int64
 3   MaritalStatusID      310 non-null    int64
 4   GenderID             310 non-null    int64
 5   EmpStatus_ID         310 non-null    int64
 6   DeptID               310 non-null    int64
 7   Perf_ScoreID         310 non-null    int64
 8   Age                  310 non-null    int64
 9   Pay Rate             310 non-null    float64
 10  State                310 non-null    str
 11  Zip                  310 non-null    int64
 12  DOB                  310 non-null    str
 13  Sex                  310 non-null    str
 14  MaritalDesc          310 non-null    str
 15  CitizenDesc          310 non-null    str
 16  Hispanic/Latino      310 non-null    str
 17  RaceDesc             310 non-null    str
 18  Date of Hire         310 non-null    str
 19  Days Employed        310 non-null    int64
 20  Date of Termination  103 non-null    str
 21  Reason For Term      310 non-null    str
 22  Employment Status    310 non-null    str
 23  Department           310 non-null    str
 24  Position             310 non-null    str
 25  Manager Name         310 non-null    str
 26  Employee Source      310 non-null    str
 27  Performance Score    310 non-null    str
dtypes: float64(1), int64(10), str(17)
memory usage: 121.9 KB
None
       Employee Name  Employee Number   MarriedID  MaritalStatusID  \
count            310     3.100000e+02  310.000000       310.000000
unique           310              NaN         NaN              NaN
top       Brown, Mia              NaN         NaN              NaN
freq               1              NaN         NaN              NaN
mean             NaN     1.199745e+09    0.396774         0.809677
std              NaN     1.829600e+08    0.490019         0.944702
min              NaN     6.020003e+08    0.000000         0.000000
25%              NaN     1.101024e+09    0.000000         0.000000
50%              NaN     1.203032e+09    0.000000         1.000000
75%              NaN     1.378814e+09    1.000000         1.000000
max              NaN     1.988300e+09    1.000000         4.000000

          GenderID  EmpStatus_ID      DeptID  Perf_ScoreID         Age  \
count   310.000000    310.000000  310.000000    310.000000  310.000000
unique         NaN           NaN         NaN           NaN         NaN
top            NaN           NaN         NaN           NaN         NaN
freq           NaN           NaN         NaN           NaN         NaN
mean      0.429032      2.396774    4.606452      3.458065   38.867742
std       0.495738      1.795533    1.082349      2.318460    8.922459
min       0.000000      1.000000    1.000000      0.000000   25.000000
25%       0.000000      1.000000    5.000000      3.000000   32.000000
50%       0.000000      1.000000    5.000000      3.000000   37.000000
75%       1.000000      5.000000    5.000000      3.000000   44.000000
max       1.000000      5.000000    6.000000      9.000000   67.000000

          Pay Rate  ... Date of Hire  Days Employed Date of Termination  \
count   310.000000  ...          310     310.000000                 103
unique         NaN  ...           99            NaN                  93
top            NaN  ...    1/10/2011            NaN            5/1/2016
freq           NaN  ...           14            NaN                   2
mean     31.284806  ...          NaN    1296.080645                 NaN
std      15.383615  ...          NaN     769.491382                 NaN
min      14.000000  ...          NaN       2.000000                 NaN
25%      20.000000  ...          NaN     766.250000                 NaN
50%      24.000000  ...          NaN    1238.000000                 NaN
75%      45.315000  ...          NaN    1732.750000                 NaN
max      80.000000  ...          NaN    4339.000000                 NaN

             Reason For Term Employment Status         Department  \
count                    310               310                310
unique                    17                 5                  6
top     N/A - still employed            Active  Production
freq                     197               183                208
mean                     NaN               NaN                NaN
std                      NaN               NaN                NaN
min                      NaN               NaN                NaN
25%                      NaN               NaN                NaN
50%                      NaN               NaN                NaN
75%                      NaN               NaN                NaN
max                      NaN               NaN                NaN

                       Position    Manager Name    Employee Source  \
count                       310             310                310
unique                       28              21                 23
top     Production Technician I  Michael Albert  Employee Referral
freq                        136              22                 31
mean                        NaN             NaN                NaN
std                         NaN             NaN                NaN
min                         NaN             NaN                NaN
25%                         NaN             NaN                NaN
50%                         NaN             NaN                NaN
75%                         NaN             NaN                NaN
max                         NaN             NaN                NaN

        Performance Score
count                 310
unique                  7
top           Fully Meets
freq                  181
mean                  NaN
std                   NaN
min                   NaN
25%                   NaN
50%                   NaN
75%                   NaN
max                   NaN

[11 rows x 28 columns]

In [6]:
print(df.isnull().sum())

Employee Name            0
Employee Number          0
MarriedID                0
MaritalStatusID          0
GenderID                 0
EmpStatus_ID             0
DeptID                   0
Perf_ScoreID             0
Age                      0
Pay Rate                 0
State                    0
Zip                      0
DOB                      0
Sex                      0
MaritalDesc              0
CitizenDesc              0
Hispanic/Latino          0
RaceDesc                 0
Date of Hire             0
Days Employed            0
Date of Termination    207
Reason For Term          0
Employment Status        0
Department               0
Position                 0
Manager Name             0
Employee Source          0
Performance Score        0
dtype: int64

In [7]:
df.head()

,Employee Name,Employee Number,MarriedID,MaritalStatusID,GenderID,EmpStatus_ID,DeptID,Perf_ScoreID,Age,Pay Rate,...,Date of Hire,Days Employed,Date of Termination,Reason For Term,Employment Status,Department,Position,Manager Name,Employee Source,Performance Score
0,"Brown, Mia",1103024456,1,1,0,1,1,3,30,28.50,...,10/27/2008,3317,NaN,N/A - still employed,Active,Admin Offices,Accountant I,Brandon R. LeBlanc,Diversity Job Fair,Fully Meets
1,"LaRotonda, William",1106026572,0,2,1,1,1,3,34,23.00,...,1/6/2014,1420,NaN,N/A - still employed,Active,Admin Offices,Accountant I,Brandon R. LeBlanc,Website Banner Ads,Fully Meets
2,"Steans, Tyrone",1302053333,0,0,1,1,1,3,31,29.00,...,9/29/2014,1154,NaN,N/A - still employed,Active,Admin Offices,Accountant I,Brandon R. LeBlanc,Internet Search,Fully Meets
3,"Howard, Estelle",1211050782,1,1,0,1,1,9,32,21.50,...,2/16/2015,58,4/15/2015,N/A - still employed,Active,Admin Offices,Administrative Assistant,Brandon R. LeBlanc,Pay Per Click - Google,N/A- too early to review
4,"Singh, Nan",1307059817,0,0,0,1,1,9,30,16.56,...,5/1/2015,940,NaN,N/A - still employed,Active,Admin Offices,Administrative Assistant,Brandon R. LeBlanc,Website Banner Ads,N/A- too early to review

In [9]:
[col for col in df.columns if "term" in col.lower()]

['Date of Termination', 'Reason For Term']

In [15]:
 df.columns

Index(['Employee Name', 'Employee Number', 'MarriedID', 'MaritalStatusID',
       'GenderID', 'EmpStatus_ID', 'DeptID', 'Perf_ScoreID', 'Age', 'Pay Rate',
       'State', 'Zip', 'DOB', 'Sex', 'MaritalDesc', 'CitizenDesc',
       'Hispanic/Latino', 'RaceDesc', 'Date of Hire', 'Days Employed',
       'Date of Termination', 'Reason For Term', 'Employment Status',
       'Department', 'Position', 'Manager Name', 'Employee Source',
       'Performance Score'],
      dtype='str')