In [1]:
import pandas as pd
import numpy as np

from sklearn.model_selection import train_test_split
from sklearn.tree import DecisionTreeRegressor, DecisionTreeClassifier
from sklearn.ensemble import RandomForestRegressor, RandomForestClassifier

from sklearn.metrics import mean_squared_error, accuracy_score, classification_report
from sklearn.preprocessing import LabelEncoder
import matplotlib.pyplot as plt

In [2]:
df = pd.read_csv("energy_dataset.csv")

df.head()

,time,generation biomass,generation fossil brown coal/lignite,generation fossil coal-derived gas,generation fossil gas,generation fossil hard coal,generation fossil oil,generation fossil oil shale,generation fossil peat,generation geothermal,...,generation waste,generation wind offshore,generation wind onshore,forecast solar day ahead,forecast wind offshore eday ahead,forecast wind onshore day ahead,total load forecast,total load actual,price day ahead,price actual
0,2015-01-01 00:00:00+01:00,447.0,329.0,0.0,4844.0,4821.0,162.0,0.0,0.0,0.0,...,196.0,0.0,6378.0,17.0,NaN,6436.0,26118.0,25385.0,50.10,65.41
1,2015-01-01 01:00:00+01:00,449.0,328.0,0.0,5196.0,4755.0,158.0,0.0,0.0,0.0,...,195.0,0.0,5890.0,16.0,NaN,5856.0,24934.0,24382.0,48.10,64.92
2,2015-01-01 02:00:00+01:00,448.0,323.0,0.0,4857.0,4581.0,157.0,0.0,0.0,0.0,...,196.0,0.0,5461.0,8.0,NaN,5454.0,23515.0,22734.0,47.33,64.48
3,2015-01-01 03:00:00+01:00,438.0,254.0,0.0,4314.0,4131.0,160.0,0.0,0.0,0.0,...,191.0,0.0,5238.0,2.0,NaN,5151.0,22642.0,21286.0,42.27,59.32
4,2015-01-01 04:00:00+01:00,428.0,187.0,0.0,4130.0,3840.0,156.0,0.0,0.0,0.0,...,189.0,0.0,4935.0,9.0,NaN,4861.0,21785.0,20264.0,38.41,56.04

In [3]:
print(df.shape)
print(df.info())
print(df.describe())

(35064, 29)
<class 'pandas.DataFrame'>
RangeIndex: 35064 entries, 0 to 35063
Data columns (total 29 columns):
 #   Column                                       Non-Null Count  Dtype
---  ------                                       --------------  -----
 0   time                                         35064 non-null  str
 1   generation biomass                           35045 non-null  float64
 2   generation fossil brown coal/lignite         35046 non-null  float64
 3   generation fossil coal-derived gas           35046 non-null  float64
 4   generation fossil gas                        35046 non-null  float64
 5   generation fossil hard coal                  35046 non-null  float64
 6   generation fossil oil                        35045 non-null  float64
 7   generation fossil oil shale                  35046 non-null  float64
 8   generation fossil peat                       35046 non-null  float64
 9   generation geothermal                        35046 non-null  float64
 10  generation hydro pumped storage aggregated   0 non-null      float64
 11  generation hydro pumped storage consumption  35045 non-null  float64
 12  generation hydro run-of-river and poundage   35045 non-null  float64
 13  generation hydro water reservoir             35046 non-null  float64
 14  generation marine                            35045 non-null  float64
 15  generation nuclear                           35047 non-null  float64
 16  generation other                             35046 non-null  float64
 17  generation other renewable                   35046 non-null  float64
 18  generation solar                             35046 non-null  float64
 19  generation waste                             35045 non-null  float64
 20  generation wind offshore                     35046 non-null  float64
 21  generation wind onshore                      35046 non-null  float64
 22  forecast solar day ahead                     35064 non-null  float64
 23  forecast wind offshore eday ahead            0 non-null      float64
 24  forecast wind onshore day ahead              35064 non-null  float64
 25  total load forecast                          35064 non-null  float64
 26  total load actual                            35028 non-null  float64
 27  price day ahead                              35064 non-null  float64
 28  price actual                                 35064 non-null  float64
dtypes: float64(28), str(1)
memory usage: 8.6 MB
None
       generation biomass  generation fossil brown coal/lignite  \
count        35045.000000                          35046.000000
mean           383.513540                            448.059208
std             85.353943                            354.568590
min              0.000000                              0.000000
25%            333.000000                              0.000000
50%            367.000000                            509.000000
75%            433.000000                            757.000000
max            592.000000                            999.000000

       generation fossil coal-derived gas  generation fossil gas  \
count                             35046.0           35046.000000
mean                                  0.0            5622.737488
std                                   0.0            2201.830478
min                                   0.0               0.000000
25%                                   0.0            4126.000000
50%                                   0.0            4969.000000
75%                                   0.0            6429.000000
max                                   0.0           20034.000000

       generation fossil hard coal  generation fossil oil  \
count                 35046.000000           35045.000000
mean                   4256.065742             298.319789
std                    1961.601013              52.520673
min                       0.000000               0.000000
25%                    2527.000000             263.000000
50%                    4474.000000             300.000000
75%                    5838.750000             330.000000
max                    8359.000000             449.000000

       generation fossil oil shale  generation fossil peat  \
count                      35046.0                 35046.0
mean                           0.0                     0.0
std                            0.0                     0.0
min                            0.0                     0.0
25%                            0.0                     0.0
50%                            0.0                     0.0
75%                            0.0                     0.0
max                            0.0                     0.0

       generation geothermal  generation hydro pumped storage aggregated  ...  \
count                35046.0                                         0.0  ...
mean                     0.0                                         NaN  ...
std                      0.0                                         NaN  ...
min                      0.0                                         NaN  ...
25%                      0.0                                         NaN  ...
50%                      0.0                                         NaN  ...
75%                      0.0                                         NaN  ...
max                      0.0                                         NaN  ...

       generation waste  generation wind offshore  generation wind onshore  \
count      35045.000000                   35046.0             35046.000000
mean         269.452133                       0.0              5464.479769
std           50.195536                       0.0              3213.691587
min            0.000000                       0.0                 0.000000
25%          240.000000                       0.0              2933.000000
50%          279.000000                       0.0              4849.000000
75%          310.000000                       0.0              7398.000000
max          357.000000                       0.0             17436.000000

       forecast solar day ahead  forecast wind offshore eday ahead  \
count              35064.000000                                0.0
mean                1439.066735                                NaN
std                 1677.703355                                NaN
min                    0.000000                                NaN
25%                   69.000000                                NaN
50%                  576.000000                                NaN
75%                 2636.000000                                NaN
max                 5836.000000                                NaN

       forecast wind onshore day ahead  total load forecast  \
count                     35064.000000         35064.000000
mean                       5471.216689         28712.129962
std                        3176.312853          4594.100854
min                         237.000000         18105.000000
25%                        2979.000000         24793.750000
50%                        4855.000000         28906.000000
75%                        7353.000000         32263.250000
max                       17430.000000         41390.000000

       total load actual  price day ahead  price actual
count       35028.000000     35064.000000  35064.000000
mean        28696.939905        49.874341     57.884023
std          4574.987950        14.618900     14.204083
min         18041.000000         2.060000      9.330000
25%         24807.750000        41.490000     49.347500
50%         28901.000000        50.520000     58.020000
75%         32192.000000        60.530000     68.010000
max         41015.000000       101.990000    116.800000

[8 rows x 28 columns]

In [4]:
df = df.dropna()   # simple approach (you can also impute if needed)

In [5]:
print(df.columns)

Index(['time', 'generation biomass', 'generation fossil brown coal/lignite',
       'generation fossil coal-derived gas', 'generation fossil gas',
       'generation fossil hard coal', 'generation fossil oil',
       'generation fossil oil shale', 'generation fossil peat',
       'generation geothermal', 'generation hydro pumped storage aggregated',
       'generation hydro pumped storage consumption',
       'generation hydro run-of-river and poundage',
       'generation hydro water reservoir', 'generation marine',
       'generation nuclear', 'generation other', 'generation other renewable',
       'generation solar', 'generation waste', 'generation wind offshore',
       'generation wind onshore', 'forecast solar day ahead',
       'forecast wind offshore eday ahead', 'forecast wind onshore day ahead',
       'total load forecast', 'total load actual', 'price day ahead',
       'price actual'],
      dtype='str')

In [7]:
from sklearn.preprocessing import LabelEncoder

label_encoders = {}

for col in df.select_dtypes(include=["object", "string"]).columns:
    le = LabelEncoder()
    df[col] = le.fit_transform(df[col].astype(str))
    label_encoders[col] = le

In [9]:
print(df.columns)

Index(['time', 'generation biomass', 'generation fossil brown coal/lignite',
       'generation fossil coal-derived gas', 'generation fossil gas',
       'generation fossil hard coal', 'generation fossil oil',
       'generation fossil oil shale', 'generation fossil peat',
       'generation geothermal', 'generation hydro pumped storage aggregated',
       'generation hydro pumped storage consumption',
       'generation hydro run-of-river and poundage',
       'generation hydro water reservoir', 'generation marine',
       'generation nuclear', 'generation other', 'generation other renewable',
       'generation solar', 'generation waste', 'generation wind offshore',
       'generation wind onshore', 'forecast solar day ahead',
       'forecast wind offshore eday ahead', 'forecast wind onshore day ahead',
       'total load forecast', 'total load actual', 'price day ahead',
       'price actual'],
      dtype='str')

In [12]:
print(df.columns)

Index(['time', 'generation biomass', 'generation fossil brown coal/lignite',
       'generation fossil coal-derived gas', 'generation fossil gas',
       'generation fossil hard coal', 'generation fossil oil',
       'generation fossil oil shale', 'generation fossil peat',
       'generation geothermal', 'generation hydro pumped storage aggregated',
       'generation hydro pumped storage consumption',
       'generation hydro run-of-river and poundage',
       'generation hydro water reservoir', 'generation marine',
       'generation nuclear', 'generation other', 'generation other renewable',
       'generation solar', 'generation waste', 'generation wind offshore',
       'generation wind onshore', 'forecast solar day ahead',
       'forecast wind offshore eday ahead', 'forecast wind onshore day ahead',
       'total load forecast', 'total load actual', 'price day ahead',
       'price actual'],
      dtype='str')

In [14]:
df.head()

Empty DataFrame
Columns: [time, generation biomass, generation fossil brown coal/lignite, generation fossil coal-derived gas, generation fossil gas, generation fossil hard coal, generation fossil oil, generation fossil oil shale, generation fossil peat, generation geothermal, generation hydro pumped storage aggregated, generation hydro pumped storage consumption, generation hydro run-of-river and poundage, generation hydro water reservoir, generation marine, generation nuclear, generation other, generation other renewable, generation solar, generation waste, generation wind offshore, generation wind onshore, forecast solar day ahead, forecast wind offshore eday ahead, forecast wind onshore day ahead, total load forecast, total load actual, price day ahead, price actual]
Index: []

[0 rows x 29 columns]

In [17]:
df.head()
df.columns

Index(['time', 'generation biomass', 'generation fossil brown coal/lignite',
       'generation fossil coal-derived gas', 'generation fossil gas',
       'generation fossil hard coal', 'generation fossil oil',
       'generation fossil oil shale', 'generation fossil peat',
       'generation geothermal', 'generation hydro pumped storage aggregated',
       'generation hydro pumped storage consumption',
       'generation hydro run-of-river and poundage',
       'generation hydro water reservoir', 'generation marine',
       'generation nuclear', 'generation other', 'generation other renewable',
       'generation solar', 'generation waste', 'generation wind offshore',
       'generation wind onshore', 'forecast solar day ahead',
       'forecast wind offshore eday ahead', 'forecast wind onshore day ahead',
       'total load forecast', 'total load actual', 'price day ahead',
       'price actual'],
      dtype='str')