In [1]:
# Data handling
import pandas as pd
import numpy as np

# Visualisation
import matplotlib.pyplot as plt
import seaborn as sns

# NLP
from sklearn.feature_extraction.text import TfidfVectorizer
from nltk.corpus import stopwords
import nltk

# Machine Learning
from sklearn.preprocessing import StandardScaler
from sklearn.cluster import KMeans
from sklearn.decomposition import PCA

# Metrics
from sklearn.metrics import silhouette_score

import warnings
warnings.filterwarnings("ignore")

nltk.download('stopwords')

[nltk_data] Downloading package stopwords to
[nltk_data]     /Users/adnanaltimeemy/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!

True

In [2]:
# Load CSV file

df = pd.read_csv("Energy Level.csv")

# Display first rows

df.head()

   Group A  Group B
0        3        2
1        4        1
2        0        1
3        8        2
4        6        6

In [3]:
# Dataset shape

print(df.shape)


# Column information

df.info()


# Missing values

df.isnull().sum()

(100, 2)
<class 'pandas.DataFrame'>
RangeIndex: 100 entries, 0 to 99
Data columns (total 2 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   Group A  100 non-null    int64
 1   Group B  100 non-null    int64
dtypes: int64(2)
memory usage: 1.7 KB

Group A    0
Group B    0
dtype: int64

In [4]:
# Remove duplicate rows

df.drop_duplicates(inplace=True)


# Fill missing values

for col in df.columns:
    if df[col].dtype == "object":
        df[col].fillna("unknown", inplace=True)
    else:
        df[col].fillna(df[col].median(), inplace=True)


df.head()

   Group A  Group B
0        3        2
1        4        1
2        0        1
3        8        2
4        6        6

In [5]:
# Numerical columns

numeric_columns = df.select_dtypes(
    include=['int64','float64']
).columns


print("Numerical Columns:")
print(list(numeric_columns))


# Text columns

text_columns = df.select_dtypes(
    include=['object']
).columns


print("\nText Columns:")
print(list(text_columns))

Numerical Columns:
['Group A', 'Group B']

Text Columns:
[]

In [6]:
# Combine all text columns

df["text_data"] = df[text_columns].astype(str).agg(
    " ".join,
    axis=1
)


df["text_data"].head()

0
1
2
3
4
Name: text_data, dtype: str

In [7]:
scaler = StandardScaler()


numeric_features = scaler.fit_transform(
    df[numeric_columns]
)


numeric_features.shape

(64, 2)

In [10]:
df.to_csv(
    "Energy_Level_KMeans_NLP_Result.csv",
    index=False
)

print(
    "File saved successfully!"
)

File saved successfully!