In [1]:
# Data handling
import pandas as pd
import numpy as np

# Visualisation
import matplotlib.pyplot as plt
import seaborn as sns

# Machine Learning
from sklearn.preprocessing import StandardScaler
from sklearn.cluster import KMeans
from sklearn.decomposition import PCA
from sklearn.metrics import silhouette_score

# NLP
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.cluster import KMeans as TextKMeans

import warnings
warnings.filterwarnings("ignore")

In [2]:
# Load CSV file
df = pd.read_csv("ExoPlanets-data.csv")

# Display first rows
df.head()

,pl_name,hostname,sy_snum,sy_pnum,discoverymethod,disc_year,disc_facility,pl_controv_flag,pl_orbper,pl_orbpererr1,...,sy_disterr2,sy_vmag,sy_vmagerr1,sy_vmagerr2,sy_kmag,sy_kmagerr1,sy_kmagerr2,sy_gaiamag,sy_gaiamagerr1,sy_gaiamagerr2
0,11 Com b,11 Com,2,1,Radial Velocity,2007,Xinglong Station,0,323.21000,0.06000,...,-1.9238,4.72307,0.023,-0.023,2.282,0.346,-0.346,4.44038,0.003848,-0.003848
1,11 UMi b,11 UMi,1,1,Radial Velocity,2009,Thueringer Landessternwarte Tautenburg,0,516.21997,3.20000,...,-1.9765,5.01300,0.005,-0.005,1.939,0.270,-0.270,4.56216,0.003903,-0.003903
2,14 And b,14 And,1,1,Radial Velocity,2008,Okayama Astrophysical Observatory,0,186.76000,0.11000,...,-0.7140,5.23133,0.023,-0.023,2.331,0.240,-0.240,4.91781,0.002826,-0.002826
3,14 Her b,14 Her,1,2,Radial Velocity,2002,W. M. Keck Observatory,0,1765.03890,1.67709,...,-0.0073,6.61935,0.023,-0.023,4.714,0.016,-0.016,6.38300,0.000351,-0.000351
4,16 Cyg B b,16 Cyg B,3,1,Radial Velocity,1996,Multiple Observatories,0,798.50000,1.00000,...,-0.0111,6.21500,0.016,-0.016,4.651,0.016,-0.016,6.06428,0.000603,-0.000603

In [3]:
# Dataset information
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 5759 entries, 0 to 5758
Data columns (total 84 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   pl_name          5759 non-null   str
 1   hostname         5759 non-null   str
 2   sy_snum          5759 non-null   int64
 3   sy_pnum          5759 non-null   int64
 4   discoverymethod  5759 non-null   str
 5   disc_year        5759 non-null   int64
 6   disc_facility    5759 non-null   str
 7   pl_controv_flag  5759 non-null   int64
 8   pl_orbper        5483 non-null   float64
 9   pl_orbpererr1    4982 non-null   float64
 10  pl_orbpererr2    4982 non-null   float64
 11  pl_orbperlim     5483 non-null   float64
 12  pl_orbsmax       5478 non-null   float64
 13  pl_orbsmaxerr1   2866 non-null   float64
 14  pl_orbsmaxerr2   2866 non-null   float64
 15  pl_orbsmaxlim    5479 non-null   float64
 16  pl_rade          5738 non-null   float64
 17  pl_radeerr1      3982 non-null   float64
 18  pl_radeerr2      3982 non-null   float64
 19  pl_radelim       5738 non-null   float64
 20  pl_radj          5737 non-null   float64
 21  pl_radjerr1      3911 non-null   float64
 22  pl_radjerr2      3911 non-null   float64
 23  pl_radjlim       5737 non-null   float64
 24  pl_bmasse        5736 non-null   float64
 25  pl_bmasseerr1    2649 non-null   float64
 26  pl_bmasseerr2    2649 non-null   float64
 27  pl_bmasselim     5736 non-null   float64
 28  pl_bmassj        5736 non-null   float64
 29  pl_bmassjerr1    2649 non-null   float64
 30  pl_bmassjerr2    2649 non-null   float64
 31  pl_bmassjlim     5736 non-null   float64
 32  pl_bmassprov     5759 non-null   str
 33  pl_orbeccen      4937 non-null   float64
 34  pl_orbeccenerr1  1670 non-null   float64
 35  pl_orbeccenerr2  1670 non-null   float64
 36  pl_orbeccenlim   4937 non-null   float64
 37  pl_insol         4018 non-null   float64
 38  pl_insolerr1     3406 non-null   float64
 39  pl_insolerr2     3406 non-null   float64
 40  pl_insollim      4018 non-null   float64
 41  pl_eqt           4279 non-null   float64
 42  pl_eqterr1       1531 non-null   float64
 43  pl_eqterr2       1531 non-null   float64
 44  pl_eqtlim        4279 non-null   float64
 45  ttv_flag         5759 non-null   int64
 46  st_spectype      2058 non-null   str
 47  st_teff          5520 non-null   float64
 48  st_tefferr1      5321 non-null   float64
 49  st_tefferr2      5297 non-null   float64
 50  st_tefflim       5520 non-null   float64
 51  st_rad           5498 non-null   float64
 52  st_raderr1       5336 non-null   float64
 53  st_raderr2       5318 non-null   float64
 54  st_radlim        5498 non-null   float64
 55  st_mass          5752 non-null   float64
 56  st_masserr1      5474 non-null   float64
 57  st_masserr2      5453 non-null   float64
 58  st_masslim       5752 non-null   float64
 59  st_met           5287 non-null   float64
 60  st_meterr1       4988 non-null   float64
 61  st_meterr2       4988 non-null   float64
 62  st_metlim        5287 non-null   float64
 63  st_metratio      5261 non-null   str
 64  st_logg          5492 non-null   float64
 65  st_loggerr1      5310 non-null   float64
 66  st_loggerr2      5310 non-null   float64
 67  st_logglim       5492 non-null   float64
 68  rastr            5759 non-null   str
 69  ra               5759 non-null   float64
 70  decstr           5759 non-null   str
 71  dec              5759 non-null   float64
 72  sy_dist          5734 non-null   float64
 73  sy_disterr1      5628 non-null   float64
 74  sy_disterr2      5628 non-null   float64
 75  sy_vmag          5520 non-null   float64
 76  sy_vmagerr1      5512 non-null   float64
 77  sy_vmagerr2      5506 non-null   float64
 78  sy_kmag          5529 non-null   float64
 79  sy_kmagerr1      5493 non-null   float64
 80  sy_kmagerr2      5481 non-null   float64
 81  sy_gaiamag       5472 non-null   float64
 82  sy_gaiamagerr1   5470 non-null   float64
 83  sy_gaiamagerr2   5470 non-null   float64
dtypes: float64(70), int64(5), str(9)
memory usage: 4.2 MB

In [4]:
df = df.drop_duplicates()

In [5]:
# Select useful numerical features
features = df.select_dtypes(
    include=['float64','int64']
)

features.head()

,sy_snum,sy_pnum,disc_year,pl_controv_flag,pl_orbper,pl_orbpererr1,pl_orbpererr2,pl_orbperlim,pl_orbsmax,pl_orbsmaxerr1,...,sy_disterr2,sy_vmag,sy_vmagerr1,sy_vmagerr2,sy_kmag,sy_kmagerr1,sy_kmagerr2,sy_gaiamag,sy_gaiamagerr1,sy_gaiamagerr2
0,2,1,2007,0,323.21000,0.06000,-0.05000,0.0,1.178,0.000,...,-1.9238,4.72307,0.023,-0.023,2.282,0.346,-0.346,4.44038,0.003848,-0.003848
1,1,1,2009,0,516.21997,3.20000,-3.20000,0.0,1.530,0.070,...,-1.9765,5.01300,0.005,-0.005,1.939,0.270,-0.270,4.56216,0.003903,-0.003903
2,1,1,2008,0,186.76000,0.11000,-0.12000,0.0,0.775,0.000,...,-0.7140,5.23133,0.023,-0.023,2.331,0.240,-0.240,4.91781,0.002826,-0.002826
3,1,2,2002,0,1765.03890,1.67709,-1.87256,0.0,2.774,0.109,...,-0.0073,6.61935,0.023,-0.023,4.714,0.016,-0.016,6.38300,0.000351,-0.000351
4,3,1,1996,0,798.50000,1.00000,-1.00000,0.0,1.660,0.030,...,-0.0111,6.21500,0.016,-0.016,4.651,0.016,-0.016,6.06428,0.000603,-0.000603

In [6]:
scaler = StandardScaler()

X_scaled = scaler.fit_transform(features)

X_scaled[:5]

array([[ 2.60232813, -0.6656698 , -2.0241983 , -0.07236378, -0.01430422,
        -0.01442719,  0.01546393,  0.01910228, -0.04129209, -0.0241643 ,
         0.03111018,  0.02340609,  1.21892569,         nan,         nan,
         0.02641199,  1.22852449,         nan,         nan,  0.0264143 ,
         2.00275952, -0.21538322,  0.22852794, -0.14587259,  2.00230112,
        -0.21516314,  0.22866291, -0.14587259,  1.07020308, -0.96911188,
         0.89196478, -0.22809753,         nan,         nan,         nan,
                nan,         nan,         nan,         nan,         nan,
        -0.26353782, -0.30745891,         nan,         nan, -0.01346077,
         2.94725108,  1.56043811, -2.49903952,  0.        ,  2.71136311,
         1.84841271, -1.85364293,  0.        , -1.48182711, -0.06196085,
         0.14361187,  0.00794051, -4.39227504, -0.04203292,  0.18335446,
         0.01908661, -0.55030213, -0.0422734 , -0.53328534, -0.23990544,
         0.22424543, -2.55358843, -0.55994568,  0.3827966 , -2.7079035 ,
         1.16271494, -1.13606779, -2.64017213,  1.76036879, -1.76036879],
       [-0.30209197, -0.6656698 , -1.59443395, -0.07236378, -0.01426868,
        -0.01442672,  0.01546171,  0.01910228, -0.04031349, -0.02344572,
         0.02931544,  0.02340609,  1.23771827,         nan,         nan,
         0.02641199,  1.22852449,         nan,         nan,  0.0264143 ,
         1.89984358,  1.01244886, -1.7509477 , -0.14587259,  1.899396  ,
         1.01007285, -1.75122136, -0.14587259,  0.02327856, -0.60512625,
         0.47799244, -0.22809753,         nan,         nan,         nan,
                nan,         nan,         nan,         nan,         nan,
        -0.26353782, -0.68105525, -0.74240385,  0.7198789 , -0.01346077,
         6.81087518,  1.55455619, -2.92345244,  0.        ,  4.34710302,
         2.01683679, -2.05761454,  0.        , -0.18274016,         nan,
                nan,  0.00794051, -5.57591821, -0.16514093,  0.28076438,
         0.01908661, -0.06506008,  1.4479899 , -0.50482545, -0.23965919,
         0.22404016, -2.45967982, -0.68972525,  0.46972203, -2.82142202,
         0.87148361, -0.85149047, -2.59937199,  1.79090169, -1.79090169],
       [-0.30209197, -0.6656698 , -1.80931612, -0.07236378, -0.01432935,
        -0.01442718,  0.01546388,  0.01910228, -0.04241247, -0.0241643 ,
         0.03111018,  0.02340609,  1.38805894,         nan,         nan,
         0.02641199,  1.37659324,         nan,         nan,  0.0264143 ,
         0.31030207, -0.22003211,  0.2310283 , -0.14587259,  0.31019419,
        -0.21980223,  0.23116382, -0.14587259, -0.50680981,         nan,
                nan, -0.22809753,         nan,         nan,         nan,
                nan,         nan,         nan,         nan,         nan,
        -0.26353782, -0.29954613,         nan,         nan, -0.01346077,
         2.41458675,  0.54286609, -0.38785728,  0.        ,  1.97646547,
         1.14103159, -0.69780383,  0.        , -1.211184  , -0.06196085,
         0.14361187,  0.00794051, -4.16465136, -0.28824893,  0.28076438,
         0.01908661,  1.29451199,  0.54915153, -0.5490006 , -0.24555838,
         0.22895776, -2.38896252, -0.55994568,  0.3827966 , -2.69168657,
         0.75652387, -0.73915732, -2.48021802,  1.19929922, -1.19929922],
       [-0.30209197,  0.20362552, -3.09860917, -0.07236378, -0.01403874,
        -0.01442695,  0.01546264,  0.01910228, -0.03685502, -0.02304538,
         0.02803349,  0.02340609,  1.29409602,         nan,         nan,
         0.02641199,  1.29198253,         nan,         nan,  0.0264143 ,
         0.94918521,  0.56408201, -0.403234  , -0.14587259,  0.94894501,
         0.56265811, -0.40323278, -0.14587259,  1.9647272 , -0.95328641,
         0.90996358, -0.22809753,         nan,         nan,         nan,
                nan,         nan,         nan,         nan,         nan,
        -0.26353782, -0.04520671, -1.03913091,  1.00234382, -0.01346077,
        -0.14509435, -0.11002694,  0.15626185,  0.        , -0.08598919,
         0.06311749, -0.08588902,  0.        ,  2.11772633, -0.85346688,
         0.86120708,  0.00794051,  0.16019867, -0.78068095,  0.76781399,
         0.01908661,  0.08159933,  0.67549063, -0.59992851, -0.24886053,
         0.23171044, -1.9393815 , -0.55994568,  0.3827966 , -1.9030142 ,
        -0.10184216,  0.09959687, -1.98933314, -0.15985434,  0.15985434],
       [ 5.50674822, -0.6656698 , -4.38790222, -0.07236378, -0.01421671,
        -0.01442705,  0.01546326,  0.01910228, -0.03995207, -0.02385634,
         0.03034101,  0.02340609,  1.46322927,         nan,         nan,
         0.02641199,  1.46120395,         nan,         nan,  0.0264143 ,
         0.05739433, -0.23759441,  0.26603326, -0.14587259,  0.05733756,
        -0.23732769,  0.26617651, -0.14587259,  3.99894131, -0.76338087,
         0.65798041, -0.22809753,         nan,         nan,         nan,
                nan,         nan,         nan,         nan,         nan,
        -0.26353782,  0.18765515, -1.27933852,  1.2310059 , -0.01346077,
        -0.09688943, -0.11002694,  0.15626185,  0.        ,  0.31701919,
        -0.17267622,  0.15207786,  0.        ,  0.25028883,         nan,
                nan,  0.00794051, -0.04466265, -0.90378895,  0.86522391,
         0.01908661,  0.66332376,  0.86030138, -0.59708805, -0.24884324,
         0.23169564, -2.07035086, -0.61041552,  0.41660094, -1.92386454,
        -0.10184216,  0.09959687, -2.0961144 , -0.02163254,  0.02163254]])

In [8]:
df.head()

,pl_name,hostname,sy_snum,sy_pnum,discoverymethod,disc_year,disc_facility,pl_controv_flag,pl_orbper,pl_orbpererr1,...,sy_disterr2,sy_vmag,sy_vmagerr1,sy_vmagerr2,sy_kmag,sy_kmagerr1,sy_kmagerr2,sy_gaiamag,sy_gaiamagerr1,sy_gaiamagerr2
0,11 Com b,11 Com,2,1,Radial Velocity,2007,Xinglong Station,0,323.21000,0.06000,...,-1.9238,4.72307,0.023,-0.023,2.282,0.346,-0.346,4.44038,0.003848,-0.003848
1,11 UMi b,11 UMi,1,1,Radial Velocity,2009,Thueringer Landessternwarte Tautenburg,0,516.21997,3.20000,...,-1.9765,5.01300,0.005,-0.005,1.939,0.270,-0.270,4.56216,0.003903,-0.003903
2,14 And b,14 And,1,1,Radial Velocity,2008,Okayama Astrophysical Observatory,0,186.76000,0.11000,...,-0.7140,5.23133,0.023,-0.023,2.331,0.240,-0.240,4.91781,0.002826,-0.002826
3,14 Her b,14 Her,1,2,Radial Velocity,2002,W. M. Keck Observatory,0,1765.03890,1.67709,...,-0.0073,6.61935,0.023,-0.023,4.714,0.016,-0.016,6.38300,0.000351,-0.000351
4,16 Cyg B b,16 Cyg B,3,1,Radial Velocity,1996,Multiple Observatories,0,798.50000,1.00000,...,-0.0111,6.21500,0.016,-0.016,4.651,0.016,-0.016,6.06428,0.000603,-0.000603

In [9]:
df.to_csv(
    "Exoplanets_clustered_results.csv",
    index=False
)

print("File saved successfully")

File saved successfully