In [1]:
# Data handling
import pandas as pd
import numpy as np

# NLP
import re
import nltk
from nltk.corpus import stopwords
from nltk.stem import WordNetLemmatizer

# Vectorization
from sklearn.feature_extraction.text import TfidfVectorizer

# K-means
from sklearn.cluster import KMeans

# Evaluation and visualization
from sklearn.decomposition import PCA
import matplotlib.pyplot as plt
from sklearn.metrics import silhouette_score

# Download NLP resources
nltk.download('stopwords')
nltk.download('wordnet')

[nltk_data] Downloading package stopwords to
[nltk_data]     /Users/adnanaltimeemy/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!
[nltk_data] Downloading package wordnet to
[nltk_data]     /Users/adnanaltimeemy/nltk_data...
[nltk_data]   Package wordnet is already up-to-date!

True

In [2]:
# Load CSV file
df = pd.read_csv("fp7-golden-dataset-new.csv")

# Display first rows
df.head()

,acronym,title,projectUrl,Unnamed: 3
0,FAMILIESANDSOCIETIES,Changing families and sustainable societies: P...,http://www.familiesandsocieties.eu/,NaN
1,HLEG,High Level Expert Group on European Low Dose R...,http://www.hleg.de,NaN
2,NOTOX,Predicting long-term toxic effects using compu...,http://www.notox-sb.eu,NaN
3,HEAR-EU,High-resolution image-based computational inne...,http://www.hear-eu.eu,NaN
4,GAMMA,Global ATM security management,http://www.gamma-project.eu/,NaN

In [4]:
df.columns

Index(['acronym', 'title', 'projectUrl', 'Unnamed: 3'], dtype='str')

In [6]:


df.head()

,acronym,title,projectUrl,Unnamed: 3
0,FAMILIESANDSOCIETIES,Changing families and sustainable societies: P...,http://www.familiesandsocieties.eu/,NaN
1,HLEG,High Level Expert Group on European Low Dose R...,http://www.hleg.de,NaN
2,NOTOX,Predicting long-term toxic effects using compu...,http://www.notox-sb.eu,NaN
3,HEAR-EU,High-resolution image-based computational inne...,http://www.hear-eu.eu,NaN
4,GAMMA,Global ATM security management,http://www.gamma-project.eu/,NaN

In [7]:
df.head()

,acronym,title,projectUrl,Unnamed: 3
0,FAMILIESANDSOCIETIES,Changing families and sustainable societies: P...,http://www.familiesandsocieties.eu/,NaN
1,HLEG,High Level Expert Group on European Low Dose R...,http://www.hleg.de,NaN
2,NOTOX,Predicting long-term toxic effects using compu...,http://www.notox-sb.eu,NaN
3,HEAR-EU,High-resolution image-based computational inne...,http://www.hear-eu.eu,NaN
4,GAMMA,Global ATM security management,http://www.gamma-project.eu/,NaN

In [9]:
print(df.head())
print(df.columns.tolist())
print(df.info())

                acronym                                              title  \
0  FAMILIESANDSOCIETIES  Changing families and sustainable societies: P...
1                  HLEG  High Level Expert Group on European Low Dose R...
2                 NOTOX  Predicting long-term toxic effects using compu...
3               HEAR-EU  High-resolution image-based computational inne...
4                 GAMMA                     Global ATM security management

                            projectUrl Unnamed: 3
0  http://www.familiesandsocieties.eu/        NaN
1                   http://www.hleg.de        NaN
2               http://www.notox-sb.eu        NaN
3                http://www.hear-eu.eu        NaN
4         http://www.gamma-project.eu/        NaN
['acronym', 'title', 'projectUrl', 'Unnamed: 3']
<class 'pandas.DataFrame'>
RangeIndex: 2020 entries, 0 to 2019
Data columns (total 4 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   acronym     2020 non-null   str
 1   title       2020 non-null   str
 2   projectUrl  2020 non-null   str
 3   Unnamed: 3  1 non-null      str
dtypes: str(4)
memory usage: 313.1 KB
None

In [11]:
df.head()

,acronym,title,projectUrl,Unnamed: 3
0,FAMILIESANDSOCIETIES,Changing families and sustainable societies: P...,http://www.familiesandsocieties.eu/,NaN
1,HLEG,High Level Expert Group on European Low Dose R...,http://www.hleg.de,NaN
2,NOTOX,Predicting long-term toxic effects using compu...,http://www.notox-sb.eu,NaN
3,HEAR-EU,High-resolution image-based computational inne...,http://www.hear-eu.eu,NaN
4,GAMMA,Global ATM security management,http://www.gamma-project.eu/,NaN

In [12]:
df.columns

Index(['acronym', 'title', 'projectUrl', 'Unnamed: 3'], dtype='str')

In [13]:
df.to_csv(
    "fp7_golden_dataset_kmeans_clusters.csv",
    index=False
)

print("Saved successfully")

Saved successfully