In [1]:
import pandas as pd
import numpy as np

import nltk
import re

from nltk.corpus import stopwords
from nltk.stem import WordNetLemmatizer

from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.cluster import KMeans
from sklearn.decomposition import PCA

import matplotlib.pyplot as plt
import seaborn as sns

nltk.download("stopwords")
nltk.download("wordnet")

[nltk_data] Downloading package stopwords to
[nltk_data]     /Users/adnanaltimeemy/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!
[nltk_data] Downloading package wordnet to
[nltk_data]     /Users/adnanaltimeemy/nltk_data...
[nltk_data]   Package wordnet is already up-to-date!

True

In [2]:
df = pd.read_csv("gantt_example.csv")

df.head()

    Task                Start               Finish  Complete Resource
0  Job A           2009-01-01           2009-02-26        23        A
1  Job B           2009-03-05           2009-04-15        55        A
2  Job C  2009-02-20 12:40:00  2009-05-30 15:12:44        97        C
3  Job D           2009-03-10           2009-04-30        11        B
4  Job E           2009-02-25           2009-06-30        14        A

In [3]:
stop_words = set(stopwords.words("english"))
lemmatizer = WordNetLemmatizer()


def clean_text(text):
    text = str(text).lower()

    # remove special characters
    text = re.sub(r"[^a-zA-Z\s]", "", text)

    # tokenize
    words = text.split()

    # remove stopwords and lemmatize
    words = [
        lemmatizer.lemmatize(word)
        for word in words
        if word not in stop_words
    ]

    return " ".join(words)


df["Task_clean"] = df["Task"].apply(clean_text)

df[["Task","Task_clean"]].head()

    Task Task_clean
0  Job A        job
1  Job B      job b
2  Job C      job c
3  Job D        job
4  Job E      job e

In [4]:
vectorizer = TfidfVectorizer(
    max_features=1000,
    ngram_range=(1,2)
)

X = vectorizer.fit_transform(df["Task_clean"])

X.shape

(5, 1)

In [7]:
print("Shape:", X.shape)
print(X.toarray())

Shape: (5, 1)
[[1.]
 [1.]
 [1.]
 [1.]
 [1.]]

In [8]:

df.head()

,Task,Start,Finish,Complete,Resource,Task_clean
0,Job A,2009-01-01,2009-02-26,23,A,job
1,Job B,2009-03-05,2009-04-15,55,A,job b
2,Job C,2009-02-20 12:40:00,2009-05-30 15:12:44,97,C,job c
3,Job D,2009-03-10,2009-04-30,11,B,job
4,Job E,2009-02-25,2009-06-30,14,A,job e

In [10]:
df.to_csv(
    "gantt_example_clustered.csv",
    index=False
)

print("Saved successfully")

Saved successfully