In [1]:
import pandas as pd
import numpy as np

from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder
from sklearn.tree import DecisionTreeClassifier, DecisionTreeRegressor
from sklearn.ensemble import RandomForestClassifier, RandomForestRegressor

from sklearn.metrics import accuracy_score, classification_report, mean_squared_error, r2_score

In [2]:
df = pd.read_csv("gasNYC.csv")

df.head()

           Date  Weekly New York City Regular All Formulations Retail Gasoline Prices  (Dollars per Gallon)
0  Jun 05, 2000                                              1.610
1  Jun 12, 2000                                              1.650
2  Jun 19, 2000                                              1.686
3  Jun 26, 2000                                              1.705
4  Jul 03, 2000                                              1.711

In [3]:
print(df.shape)
print(df.info())
print(df.describe())

print(df.isnull().sum())

(902, 2)
<class 'pandas.DataFrame'>
RangeIndex: 902 entries, 0 to 901
Data columns (total 2 columns):
 #   Column                                                                                      Non-Null Count  Dtype
---  ------                                                                                      --------------  -----
 0   Date                                                                                        901 non-null    str
 1   Weekly New York City Regular All Formulations Retail Gasoline Prices  (Dollars per Gallon)  901 non-null    float64
dtypes: float64(1), str(1)
memory usage: 24.9 KB
None
       Weekly New York City Regular All Formulations Retail Gasoline Prices  (Dollars per Gallon)
count                                         901.000000
mean                                            2.554057
std                                             0.792808
min                                             1.131000
25%                                             1.880000
50%                                             2.442000
75%                                             3.208000
max                                             4.179000
Date                                                                                          1
Weekly New York City Regular All Formulations Retail Gasoline Prices  (Dollars per Gallon)    1
dtype: int64

In [4]:
df = df.dropna()  # or use imputation if neededb

In [6]:
df.select_dtypes(include=['object'], exclude=['string'])

Empty DataFrame
Columns: []
Index: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99, ...]

[901 rows x 0 columns]

In [8]:
print(df.columns)

Index(['Date', 'Weekly New York City Regular All Formulations Retail Gasoline Prices  (Dollars per Gallon)'], dtype='str')

In [12]:
print(df.columns)

Index(['Date', 'Weekly New York City Regular All Formulations Retail Gasoline Prices  (Dollars per Gallon)'], dtype='str')

In [15]:
print(df.columns)

Index(['Date', 'Weekly New York City Regular All Formulations Retail Gasoline Prices  (Dollars per Gallon)'], dtype='str')

In [18]:
df.head()
df.columns

Index(['Date', 'Weekly New York City Regular All Formulations Retail Gasoline Prices  (Dollars per Gallon)'], dtype='str')

In [21]:
print("X exists:", "X" in globals())
print("y exists:", "y" in globals())
print("X_train exists:", "X_train" in globals())

X exists: False
y exists: False
X_train exists: False

In [23]:
globals().keys()

dict_keys(['__name__', '__doc__', '__package__', '__loader__', '__spec__', '__builtin__', '__builtins__', '_ih', '_oh', '_dh', 'In', 'Out', 'get_ipython', 'exit', 'quit', 'open', '_', '__', '___', '__session__', '_i', '_ii', '_iii', '_i1', 'pd', 'np', 'train_test_split', 'LabelEncoder', 'DecisionTreeClassifier', 'DecisionTreeRegressor', 'RandomForestClassifier', 'RandomForestRegressor', 'accuracy_score', 'classification_report', 'mean_squared_error', 'r2_score', '_i2', 'df', '_2', '_i3', '_i4', '_i5', 'label_encoders', 'col', 'le', '_i6', '_6', '_i7', '_i8', '_i9', '_i10', '_i11', '_i12', '_i13', 'dt_model', '_i14', '_i15', '_i16', '_i17', '_i18', '_18', '_i19', 'rf_model', '_i20', '_i21', '_i22', '_i23'])

In [25]:
print(globals().keys())

dict_keys(['__name__', '__doc__', '__package__', '__loader__', '__spec__', '__builtin__', '__builtins__', '_ih', '_oh', '_dh', 'In', 'Out', 'get_ipython', 'exit', 'quit', 'open', '_', '__', '___', '__session__', '_i', '_ii', '_iii', '_i1', 'pd', 'np', 'train_test_split', 'LabelEncoder', 'DecisionTreeClassifier', 'DecisionTreeRegressor', 'RandomForestClassifier', 'RandomForestRegressor', 'accuracy_score', 'classification_report', 'mean_squared_error', 'r2_score', '_i2', 'df', '_2', '_i3', '_i4', '_i5', 'label_encoders', 'col', 'le', '_i6', '_6', '_i7', '_i8', '_i9', '_i10', '_i11', '_i12', '_i13', 'dt_model', '_i14', '_i15', '_i16', '_i17', '_i18', '_18', '_i19', 'rf_model', '_i20', '_i21', '_i22', '_i23', '_23', '_i24', '_i25'])