In [1]:
import pandas as pd
import numpy as np

from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier

from sklearn.metrics import accuracy_score, classification_report, confusion_matrix

In [2]:
df = pd.read_csv("grades204.csv")

df.head()

            name            email    Q1    Q2  ...  final   HW1   HW2   HW3
0    Bruce Wayne   bwayne@stu.edu  74.5  67.8  ...   58.8  80.7  76.1  79.2
1     Kathy Kane    kkane@byu.edu  71.0  85.9  ...   77.3  98.5  56.0  96.2
2    Dinah Lance   dlance@mit.edu  91.5  88.9  ...   85.7  93.3  55.1  75.2
3  Steven Rogers  srogers@rit.edu  70.9  59.6  ...   98.0  58.2  76.5  61.3
4    Selina Kyle    skyle@aol.com  70.8  85.2  ...   68.7  69.4  87.5  84.3

[5 rows x 14 columns]

In [3]:
print(df.shape)
print(df.info())
print(df.isnull().sum())

(15, 14)
<class 'pandas.DataFrame'>
RangeIndex: 15 entries, 0 to 14
Data columns (total 14 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   name    15 non-null     str
 1   email   15 non-null     str
 2   Q1      15 non-null     float64
 3   Q2      15 non-null     float64
 4   Q3      15 non-null     float64
 5   Q4      15 non-null     float64
 6   Ex1     15 non-null     float64
 7   Ex2     15 non-null     float64
 8   Ex3     15 non-null     float64
 9   Ex4     15 non-null     float64
 10  final   15 non-null     float64
 11  HW1     15 non-null     float64
 12  HW2     15 non-null     float64
 13  HW3     15 non-null     float64
dtypes: float64(12), str(2)
memory usage: 2.2 KB
None
name     0
email    0
Q1       0
Q2       0
Q3       0
Q4       0
Ex1      0
Ex2      0
Ex3      0
Ex4      0
final    0
HW1      0
HW2      0
HW3      0
dtype: int64

In [4]:
df = df.dropna()   # simple approach (you can also impute if needed)

In [5]:
X = df.iloc[:, :-1]
y = df.iloc[:, -1]

In [6]:
le = LabelEncoder()

# Encode target if it's categorical
if y.dtype == 'object':
    y = le.fit_transform(y)

# Encode categorical features
for col in X.columns:
    if X[col].dtype == 'object':
        X[col] = le.fit_transform(X[col])

In [7]:
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42
)

In [9]:
X_train.head()

              name              email    Q1    Q2  ...   Ex4  final   HW1   HW2
13      Donna Troy     dtroy@yale.edu  87.0  75.2  ...  73.3   71.1  65.7  80.1
5     Victor Stone   vstone@gmail.com  91.3  67.5  ...  64.5   95.0  89.7  61.1
8   Cindy Reynolds  creynolds@mtv.com  59.0  85.4  ...  81.5   88.7  86.6  61.6
2      Dinah Lance     dlance@mit.edu  91.5  88.9  ...  97.5   85.7  93.3  55.1
1       Kathy Kane      kkane@byu.edu  71.0  85.9  ...  68.3   77.3  98.5  56.0

[5 rows x 13 columns]

In [11]:
X_train.head()
X_train.dtypes

name         str
email        str
Q1       float64
Q2       float64
Q3       float64
Q4       float64
Ex1      float64
Ex2      float64
Ex3      float64
Ex4      float64
final    float64
HW1      float64
HW2      float64
dtype: object

In [14]:
y_train.head()
y_train.nunique()
y_train.dtype

dtype('float64')