In [1]:
import pandas as pd
import numpy as np

from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier

from sklearn.metrics import accuracy_score, classification_report, confusion_matrix
import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
df = pd.read_csv("grammyDB.csv")

df.head()

,annualGrammy,category,awardType,awardFor,name
0,1,Record Of The Year,Individual,Nel Blu Dipinto Di Blu (Volare),Nel Blu Dipinto Di Blu (Volare)
1,1,Album Of The Year,Work,The Music From Peter Gunn,Henry Mancini
2,1,Song Of The Year,Individual,Nel Blu Dipinto Di Blu (Volare),Nel Blu Dipinto Di Blu (Volare)
3,1,"Best Vocal Performance, Female",Work,Ella Fitzgerald Sings The Irving Berlin Song Book,Ella Fitzgerald
4,1,"Best Vocal Performance, Male",Individual,Catch A Falling Star,Catch A Falling Star

In [5]:
print(df.shape)
print(df.info())
print(df.describe(include='all'))

(4178, 5)
<class 'pandas.DataFrame'>
RangeIndex: 4178 entries, 0 to 4177
Data columns (total 5 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   annualGrammy  4178 non-null   int64
 1   category      4178 non-null   str
 2   awardType     4178 non-null   str
 3   awardFor      4172 non-null   str
 4   name          4173 non-null   str
dtypes: int64(1), str(4)
memory usage: 499.7 KB
None
        annualGrammy            category   awardType  \
count    4178.000000                4178        4178
unique           NaN                 636           2
top              NaN  Record Of The Year  Individual
freq             NaN                  59        3009
mean       35.264481                 NaN         NaN
std        15.772827                 NaN         NaN
min         1.000000                 NaN         NaN
25%        24.000000                 NaN         NaN
50%        38.000000                 NaN         NaN
75%        48.000000                 NaN         NaN
max        59.000000                 NaN         NaN

                          awardFor         name
count                         4172         4173
unique                        3589         2909
top     Bridge Over Troubled Water  Georg Solti
freq                             7           31
mean                           NaN          NaN
std                            NaN          NaN
min                            NaN          NaN
25%                            NaN          NaN
50%                            NaN          NaN
75%                            NaN          NaN
max                            NaN          NaN

In [6]:
from pandas.api.types import is_numeric_dtype

for col in df.columns:
    fill_value = (
        df[col].median()
        if is_numeric_dtype(df[col])
        else df[col].mode().iloc[0]
    )

    df[col] = df[col].fillna(fill_value)

In [8]:
for col in df.select_dtypes(include=['object', 'string']).columns:
    df[col] = df[col].fillna(df[col].mode().iloc[0])

In [10]:
print(df.columns.tolist())

['annualGrammy', 'category', 'awardType', 'awardFor', 'name']

In [12]:
df.head()

   annualGrammy  category  awardType  awardFor  name
0             1       630          0      2136  1759
1             1         2          1      3088  1107
2             1       634          0      2136  1759
3             1       614          1      1027   848
4             1       615          0       665   550

In [15]:
print("X_train exists?", "X_train" in globals())
print("y_train exists?", "y_train" in globals())

X_train exists? False
y_train exists? False

In [19]:
print(df.columns)

Index(['annualGrammy', 'category', 'awardType', 'awardFor', 'name'], dtype='str')

In [22]:
print("X_train exists:", "X_train" in globals())
print("rf_model exists:", "rf_model" in globals())
print("feat_df exists:", "feat_df" in globals())

X_train exists: False
rf_model exists: True
feat_df exists: False