In [1]:
# ==========================================
# Guns Polls Dataset
# Logistic Regression & Decision Tree
# ==========================================

# Import libraries

import pandas as pd
import numpy as np

import matplotlib.pyplot as plt
import seaborn as sns

from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder, StandardScaler

from sklearn.linear_model import LogisticRegression
from sklearn.tree import DecisionTreeClassifier, plot_tree

from sklearn.metrics import (
    accuracy_score,
    classification_report,
    confusion_matrix
)

# ==========================================
# 1. Load Dataset
# ==========================================

df = pd.read_csv("guns-polls.csv")

# Display first rows

df.head()

,Question,Start,End,Pollster,Population,Support,Republican Support,Democratic Support,URL
0,age-21,2/20/18,2/23/18,CNN/SSRS,Registered Voters,72,61,86,http://cdn.cnn.com/cnn/2018/images/02/25/rel3a...
1,age-21,2/27/18,2/28/18,NPR/Ipsos,Adults,82,72,92,https://www.ipsos.com/en-us/npripsos-poll-majo...
2,age-21,3/1/18,3/4/18,Rasmussen,Adults,67,59,76,http://www.rasmussenreports.com/public_content...
3,age-21,2/22/18,2/26/18,Harris Interactive,Registered Voters,84,77,92,http://thehill.com/opinion/civil-rights/375993...
4,age-21,3/3/18,3/5/18,Quinnipiac,Registered Voters,78,63,93,https://poll.qu.edu/national/release-detail?Re...

In [2]:
# Dataset information

df.info()

<class 'pandas.DataFrame'>
RangeIndex: 57 entries, 0 to 56
Data columns (total 9 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   Question            57 non-null     str
 1   Start               57 non-null     str
 2   End                 57 non-null     str
 3   Pollster            57 non-null     str
 4   Population          57 non-null     str
 5   Support             57 non-null     int64
 6   Republican Support  57 non-null     int64
 7   Democratic Support  57 non-null     int64
 8   URL                 57 non-null     str
dtypes: int64(3), str(6)
memory usage: 12.3 KB

In [3]:
# Statistical summary

df.describe(include="all")

,Question,Start,End,Pollster,Population,Support,Republican Support,Democratic Support,URL
count,57,57,57,57,57,57.000000,57.000000,57.000000,57
unique,8,12,13,14,2,NaN,NaN,NaN,20
top,ban-assault-weapons,2/20/18,3/5/18,YouGov,Registered Voters,NaN,NaN,NaN,https://www.ipsos.com/en-us/npripsos-poll-majo...
freq,12,12,11,12,44,NaN,NaN,NaN,7
mean,NaN,NaN,NaN,NaN,NaN,67.771930,59.684211,77.228070,NaN
std,NaN,NaN,NaN,NaN,NaN,16.040148,19.802740,23.659804,NaN
min,NaN,NaN,NaN,NaN,NaN,10.000000,5.000000,10.000000,NaN
25%,NaN,NaN,NaN,NaN,NaN,61.000000,43.000000,80.000000,NaN
50%,NaN,NaN,NaN,NaN,NaN,68.000000,59.000000,85.000000,NaN
75%,NaN,NaN,NaN,NaN,NaN,76.000000,76.000000,90.000000,NaN
max,NaN,NaN,NaN,NaN,NaN,97.000000,97.000000,99.000000,NaN

In [4]:
# Remove duplicate rows

df = df.drop_duplicates()

df.shape

(57, 9)

In [5]:
# Label Encoding

encoder = LabelEncoder()

for col in df.select_dtypes(include="object").columns:
    df[col] = encoder.fit_transform(df[col])


df.head()

/var/folders/88/w4w1n8l12kd_z42_6mrnndmw0000gn/T/ipykernel_5483/2443501933.py:5: Pandas4Warning: For backward compatibility, 'str' dtypes are included by select_dtypes when 'object' dtype is specified. This behavior is deprecated and will be removed in a future version. Explicitly pass 'str' to `include` to select them, or to `exclude` to remove them and silence this warning.
See https://pandas.pydata.org/docs/user_guide/migration-3-strings.html#string-migration-select-dtypes for details on how to write code that works with pandas 2 and 3.
  for col in df.select_dtypes(include="object").columns:

,Question,Start,End,Pollster,Population,Support,Republican Support,Democratic Support,URL
0,0,3,4,2,1,72,61,86,1
1,0,8,9,7,0,82,72,92,17
2,0,9,10,9,0,67,59,76,5
3,0,4,7,3,1,84,77,92,4
4,0,10,11,8,1,78,63,93,16

In [6]:
df.columns

Index(['Question', 'Start', 'End', 'Pollster', 'Population', 'Support',
       'Republican Support', 'Democratic Support', 'URL'],
      dtype='str')

In [7]:
# Fill missing values

for col in df.columns:
    if df[col].dtype == "object":
        df[col] = df[col].fillna(df[col].mode()[0])
    else:
        df[col] = df[col].fillna(df[col].median())

df.isnull().sum()

Question              0
Start                 0
End                   0
Pollster              0
Population            0
Support               0
Republican Support    0
Democratic Support    0
URL                   0
dtype: int64