In [3]:
# Data handling
import pandas as pd
import numpy as np

# Visualization
import matplotlib.pyplot as plt
import seaborn as sns

# Machine Learning
from sklearn.preprocessing import StandardScaler
from sklearn.cluster import KMeans
from sklearn.metrics import silhouette_score

# NLP
import re
from sklearn.feature_extraction.text import TfidfVectorizer

# Ignore warnings
import warnings
warnings.filterwarnings("ignore")

In [4]:
# Load dataset
df = pd.read_csv("Nashville Housing Data for Data Cleaning.csv")

# Display first rows
df.head()

,UniqueID,ParcelID,LandUse,PropertyAddress,SaleDate,SalePrice,LegalReference,SoldAsVacant,OwnerName,OwnerAddress,Acreage,TaxDistrict,LandValue,BuildingValue,TotalValue,YearBuilt,Bedrooms,FullBath,HalfBath
0,2045,007 00 0 125.00,SINGLE FAMILY,"1808 FOX CHASE DR, GOODLETTSVILLE","April 9, 2013",240000,20130412-0036474,No,"FRAZIER, CYRENTHA LYNETTE","1808 FOX CHASE DR, GOODLETTSVILLE, TN",2.3,GENERAL SERVICES DISTRICT,50000.0,168200.0,235700.0,1986.0,3.0,3.0,0.0
1,16918,007 00 0 130.00,SINGLE FAMILY,"1832 FOX CHASE DR, GOODLETTSVILLE","June 10, 2014",366000,20140619-0053768,No,"BONER, CHARLES & LESLIE","1832 FOX CHASE DR, GOODLETTSVILLE, TN",3.5,GENERAL SERVICES DISTRICT,50000.0,264100.0,319000.0,1998.0,3.0,3.0,2.0
2,54582,007 00 0 138.00,SINGLE FAMILY,"1864 FOX CHASE DR, GOODLETTSVILLE","September 26, 2016",435000,20160927-0101718,No,"WILSON, JAMES E. & JOANNE","1864 FOX CHASE DR, GOODLETTSVILLE, TN",2.9,GENERAL SERVICES DISTRICT,50000.0,216200.0,298000.0,1987.0,4.0,3.0,0.0
3,43070,007 00 0 143.00,SINGLE FAMILY,"1853 FOX CHASE DR, GOODLETTSVILLE","January 29, 2016",255000,20160129-0008913,No,"BAKER, JAY K. & SUSAN E.","1853 FOX CHASE DR, GOODLETTSVILLE, TN",2.6,GENERAL SERVICES DISTRICT,50000.0,147300.0,197300.0,1985.0,3.0,3.0,0.0
4,22714,007 00 0 149.00,SINGLE FAMILY,"1829 FOX CHASE DR, GOODLETTSVILLE","October 10, 2014",278000,20141015-0095255,No,"POST, CHRISTOPHER M. & SAMANTHA C.","1829 FOX CHASE DR, GOODLETTSVILLE, TN",2.0,GENERAL SERVICES DISTRICT,50000.0,152300.0,202300.0,1984.0,4.0,3.0,0.0

In [5]:
# Dataset information
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 56477 entries, 0 to 56476
Data columns (total 19 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   UniqueID         56477 non-null  int64
 1   ParcelID         56477 non-null  str
 2   LandUse          56477 non-null  str
 3   PropertyAddress  56448 non-null  str
 4   SaleDate         56477 non-null  str
 5   SalePrice        56477 non-null  str
 6   LegalReference   56477 non-null  str
 7   SoldAsVacant     56477 non-null  str
 8   OwnerName        25261 non-null  str
 9   OwnerAddress     26015 non-null  str
 10  Acreage          26015 non-null  float64
 11  TaxDistrict      26015 non-null  str
 12  LandValue        26015 non-null  float64
 13  BuildingValue    26015 non-null  float64
 14  TotalValue       26015 non-null  float64
 15  YearBuilt        24163 non-null  float64
 16  Bedrooms         24157 non-null  float64
 17  FullBath         24275 non-null  float64
 18  HalfBath         24144 non-null  float64
dtypes: float64(8), int64(1), str(10)
memory usage: 15.4 MB

In [6]:
df.drop_duplicates(inplace=True)

df.shape

(56477, 19)

In [7]:
def clean_text(text):
    text = str(text).lower()
    text = re.sub(r'[^a-zA-Z ]', '', text)
    return text


df['Clean_Address'] = df['PropertyAddress'].apply(clean_text)

df[['PropertyAddress','Clean_Address']].head()

                      PropertyAddress                  Clean_Address
0  1808  FOX CHASE DR, GOODLETTSVILLE    fox chase dr goodlettsville
1  1832  FOX CHASE DR, GOODLETTSVILLE    fox chase dr goodlettsville
2  1864 FOX CHASE  DR, GOODLETTSVILLE   fox chase  dr goodlettsville
3  1853  FOX CHASE DR, GOODLETTSVILLE    fox chase dr goodlettsville
4  1829  FOX CHASE DR, GOODLETTSVILLE    fox chase dr goodlettsville

In [8]:
tfidf = TfidfVectorizer(
    max_features=100
)

address_vectors = tfidf.fit_transform(
    df['Clean_Address']
)

address_vectors.shape

(56477, 100)

In [10]:
df.to_csv(
    "Nashville_Housing_Cleaned_Clusters.csv",
    index=False
)