In [1]:
import pandas as pd
import numpy as np

from sklearn.model_selection import train_test_split
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix

from sklearn.preprocessing import LabelEncoder

In [2]:
df = pd.read_csv("hp1_data.csv")

df.head()

   chapter  ...                                               text
0        1  ...  THE BOY WHO LIVED　　Mr. and Mrs. Dursley, of nu...
1        2  ...  THE VANISHING GLASS　　Nearly ten years had pass...
2        3  ...  THE LETTERS FROM NO ONE　　The escape of the Bra...
3        4  ...  THE KEEPER OF THE KEYS　　BOOM. They knocked aga...
4        5  ...  DIAGON ALLEY　　Harry woke early the next mornin...

[5 rows x 3 columns]

In [3]:
print(df.shape)
print(df.info())
print(df.describe())
print(df.isnull().sum())

(17, 3)
<class 'pandas.DataFrame'>
RangeIndex: 17 entries, 0 to 16
Data columns (total 3 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   chapter  17 non-null     int64
 1   book     17 non-null     str
 2   text     17 non-null     str
dtypes: int64(1), str(2)
memory usage: 442.1 KB
None
         chapter
count  17.000000
mean    9.000000
std     5.049752
min     1.000000
25%     5.000000
50%     9.000000
75%    13.000000
max    17.000000
chapter    0
book       0
text       0
dtype: int64

In [7]:
num_cols = df.select_dtypes(include=np.number).columns
df[num_cols] = df[num_cols].fillna(df[num_cols].median())

In [9]:
from sklearn.preprocessing import LabelEncoder

encoders = {}

for col in df.select_dtypes(include=['object', 'string']).columns:
    le = LabelEncoder()
    df[col] = le.fit_transform(df[col])
    encoders[col] = le  # store for later inverse_transform if needed

In [11]:
print(df.columns)

Index(['chapter', 'book', 'text'], dtype='str')

In [14]:
df.head()

   chapter  book  text
0        1     0     5
1        2     0    15
2        3     0     9
3        4     0     8
4        5     0     0

In [17]:
df.columns

Index(['chapter', 'book', 'text'], dtype='str')

In [19]:
print([name for name in globals() if "test" in name.lower()])

['train_test_split']

In [21]:
print(rf_model)

RandomForestClassifier(random_state=42)