In [1]:
import pandas as pd
import numpy as np

import nltk
import re

from nltk.corpus import stopwords
from nltk.tokenize import word_tokenize

from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.cluster import KMeans
from sklearn.decomposition import PCA

import matplotlib.pyplot as plt
import seaborn as sns

nltk.download('punkt')
nltk.download('stopwords')

[nltk_data] Downloading package punkt to
[nltk_data]     /Users/adnanaltimeemy/nltk_data...
[nltk_data]   Package punkt is already up-to-date!
[nltk_data] Downloading package stopwords to
[nltk_data]     /Users/adnanaltimeemy/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!

True

In [2]:
# Load dataset
df = pd.read_csv("column_heads_of_dataset.csv")

# Display first rows
df.head()

   Unnamed: 0      column_names data_type
0           0     fixed acidity   float64
1           1  volatile acidity   float64
2           2       citric acid   float64
3           3    residual sugar   float64
4           4         chlorides   float64

In [3]:
# Dataset size
print(df.shape)

# Column names
print(df.columns)

# Data types
df.info()

(12, 3)
Index(['Unnamed: 0', 'column_names', 'data_type'], dtype='str')
<class 'pandas.DataFrame'>
RangeIndex: 12 entries, 0 to 11
Data columns (total 3 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   Unnamed: 0    12 non-null     int64
 1   column_names  12 non-null     str
 2   data_type     12 non-null     str
dtypes: int64(1), str(2)
memory usage: 636.0 bytes

In [4]:
text_columns = df.select_dtypes(include=['object']).columns

print("Text columns:")
print(text_columns)

Text columns:
Index(['column_names', 'data_type'], dtype='str')

/var/folders/88/w4w1n8l12kd_z42_6mrnndmw0000gn/T/ipykernel_73777/1810837487.py:1: Pandas4Warning: For backward compatibility, 'str' dtypes are included by select_dtypes when 'object' dtype is specified. This behavior is deprecated and will be removed in a future version. Explicitly pass 'str' to `include` to select them, or to `exclude` to remove them and silence this warning.
See https://pandas.pydata.org/docs/user_guide/migration-3-strings.html#string-migration-select-dtypes for details on how to write code that works with pandas 2 and 3.
  text_columns = df.select_dtypes(include=['object']).columns

In [6]:

df.head()

   Unnamed: 0      column_names data_type
0           0     fixed acidity   float64
1           1  volatile acidity   float64
2           2       citric acid   float64
3           3    residual sugar   float64
4           4         chlorides   float64

In [7]:
df.head()

   Unnamed: 0      column_names data_type
0           0     fixed acidity   float64
1           1  volatile acidity   float64
2           2       citric acid   float64
3           3    residual sugar   float64
4           4         chlorides   float64

In [8]:
df.to_csv(
    "kmeans_nlp_clustered_dataset.csv",
    index=False
)

print("Saved successfully!")

Saved successfully!