In [1]:
import pandas as pd
import numpy as np

from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.cluster import KMeans
from sklearn.metrics import silhouette_score

import matplotlib.pyplot as plt

In [2]:
df = pd.read_csv("lastfm.csv")

df.head()

   user                   artist sex  country
0     1    red hot chili peppers   f  Germany
1     1  the black dahlia murder   f  Germany
2     1                goldfrapp   f  Germany
3     1         dropkick murphys   f  Germany
4     1                 le tigre   f  Germany

In [3]:
print(df.info())
print(df.isnull().sum())

df.head(10)

<class 'pandas.DataFrame'>
RangeIndex: 289955 entries, 0 to 289954
Data columns (total 4 columns):
 #   Column   Non-Null Count   Dtype
---  ------   --------------   -----
 0   user     289955 non-null  int64
 1   artist   289955 non-null  str
 2   sex      289955 non-null  str
 3   country  289955 non-null  str
dtypes: int64(1), str(3)
memory usage: 14.8 MB
None
user       0
artist     0
sex        0
country    0
dtype: int64

   user                   artist sex  country
0     1    red hot chili peppers   f  Germany
1     1  the black dahlia murder   f  Germany
2     1                goldfrapp   f  Germany
3     1         dropkick murphys   f  Germany
4     1                 le tigre   f  Germany
5     1               schandmaul   f  Germany
6     1                    edguy   f  Germany
7     1             jack johnson   f  Germany
8     1                eluveitie   f  Germany
9     1              the killers   f  Germany

In [6]:
print(df.columns)

Index(['user', 'artist', 'sex', 'country'], dtype='str')

In [8]:
print(df.columns.tolist())

['user', 'artist', 'sex', 'country']

In [10]:
print(df.columns.tolist())

['user', 'artist', 'sex', 'country']

In [11]:
df.head()

   user                   artist sex  country
0     1    red hot chili peppers   f  Germany
1     1  the black dahlia murder   f  Germany
2     1                goldfrapp   f  Germany
3     1         dropkick murphys   f  Germany
4     1                 le tigre   f  Germany

In [13]:
print(df.columns.tolist())

['user', 'artist', 'sex', 'country']

In [16]:
df.head()

   user                   artist sex  country
0     1    red hot chili peppers   f  Germany
1     1  the black dahlia murder   f  Germany
2     1                goldfrapp   f  Germany
3     1         dropkick murphys   f  Germany
4     1                 le tigre   f  Germany