In [1]:
import pandas as pd
import numpy as np

from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder
from sklearn.tree import DecisionTreeClassifier, plot_tree
from sklearn.ensemble import RandomForestClassifier

from sklearn.metrics import accuracy_score, classification_report, confusion_matrix

import matplotlib.pyplot as plt

In [2]:
df = pd.read_csv("LovelyPubs.csv")

df.head()

,site,lat,lng,zip,name,address,phone,email,web
0,LovelyPubs,NaN,NaN,B93 0BN,The Orange Tree,"Warwick Road, Solihull, B93 0BN, United Kingdom",NaN,NaN,NaN
1,LovelyPubs,NaN,NaN,B94 6JU,The Boot,"Old Warwick Road, Solihull, B94 6JU, United Ki...",NaN,NaN,NaN
2,LovelyPubs,NaN,NaN,B90 1UB,Mortons,"Main Street, Solihull, B90 1UB, United Kingdom",NaN,NaN,NaN
3,LovelyPubs,NaN,NaN,B90 4EH,The Farm,"Farmhouse Way, Solihull, B90 4EH, United Kingdom",NaN,NaN,NaN
4,LovelyPubs,NaN,NaN,B60 3,The Queen's Head,"Sugarbrook Lane, Bromsgrove, B60 3, United Kin...",NaN,NaN,NaN

In [3]:
print(df.info())
print(df.describe())
print(df.isnull().sum())

<class 'pandas.DataFrame'>
RangeIndex: 7 entries, 0 to 6
Data columns (total 9 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   site     7 non-null      str
 1   lat      0 non-null      float64
 2   lng      0 non-null      float64
 3   zip      7 non-null      str
 4   name     7 non-null      str
 5   address  7 non-null      str
 6   phone    0 non-null      float64
 7   email    0 non-null      float64
 8   web      0 non-null      float64
dtypes: float64(5), str(4)
memory usage: 1.2 KB
None
       lat  lng  phone  email  web
count  0.0  0.0    0.0    0.0  0.0
mean   NaN  NaN    NaN    NaN  NaN
std    NaN  NaN    NaN    NaN  NaN
min    NaN  NaN    NaN    NaN  NaN
25%    NaN  NaN    NaN    NaN  NaN
50%    NaN  NaN    NaN    NaN  NaN
75%    NaN  NaN    NaN    NaN  NaN
max    NaN  NaN    NaN    NaN  NaN
site       0
lat        7
lng        7
zip        0
name       0
address    0
phone      7
email      7
web        7
dtype: int64

In [7]:
df = df.fillna(df.median(numeric_only=True))

In [9]:
df.select_dtypes(include=["object", "string"])

Empty DataFrame
Columns: []
Index: [0, 1, 2, 3, 4, 5, 6]

In [12]:
df.drop("zip", axis=1)

   site  lat  lng  name  address  phone  email  web
0     0  NaN  NaN     5        6    NaN    NaN  NaN
1     0  NaN  NaN     2        3    NaN    NaN  NaN
2     0  NaN  NaN     1        2    NaN    NaN  NaN
3     0  NaN  NaN     3        1    NaN    NaN  NaN
4     0  NaN  NaN     6        5    NaN    NaN  NaN
5     0  NaN  NaN     4        0    NaN    NaN  NaN
6     0  NaN  NaN     0        4    NaN    NaN  NaN

In [15]:
df.head()

   site  lat  lng  zip  name  address  phone  email  web
0     0  NaN  NaN    4     5        6    NaN    NaN  NaN
1     0  NaN  NaN    5     2        3    NaN    NaN  NaN
2     0  NaN  NaN    2     1        2    NaN    NaN  NaN
3     0  NaN  NaN    3     3        1    NaN    NaN  NaN
4     0  NaN  NaN    1     6        5    NaN    NaN  NaN

In [19]:
print(df.columns)

Index(['site', 'lat', 'lng', 'zip', 'name', 'address', 'phone', 'email',
       'web'],
      dtype='str')

In [21]:
df.head()
df.columns

Index(['site', 'lat', 'lng', 'zip', 'name', 'address', 'phone', 'email',
       'web'],
      dtype='str')

In [23]:
df.columns
df.head()

   site  lat  lng  zip  name  address  phone  email  web
0     0  NaN  NaN    4     5        6    NaN    NaN  NaN
1     0  NaN  NaN    5     2        3    NaN    NaN  NaN
2     0  NaN  NaN    2     1        2    NaN    NaN  NaN
3     0  NaN  NaN    3     3        1    NaN    NaN  NaN
4     0  NaN  NaN    1     6        5    NaN    NaN  NaN