In [1]:
# Data handling
import pandas as pd
import numpy as np

# NLP
import nltk
from nltk.corpus import stopwords
from nltk.tokenize import word_tokenize
from sklearn.feature_extraction.text import TfidfVectorizer

# Machine Learning
from sklearn.cluster import KMeans
from sklearn.decomposition import PCA
from sklearn.metrics import silhouette_score

# Visualisation
import matplotlib.pyplot as plt

import warnings
warnings.filterwarnings("ignore")

In [2]:
nltk.download('punkt')
nltk.download('stopwords')

[nltk_data] Downloading package punkt to
[nltk_data]     /Users/adnanaltimeemy/nltk_data...
[nltk_data]   Package punkt is already up-to-date!
[nltk_data] Downloading package stopwords to
[nltk_data]     /Users/adnanaltimeemy/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!

True

In [3]:
# Load dataset
df = pd.read_csv("MLS_Cup.csv")

# Display first rows
df.head()

,Name,Year,Teams,Total Posts,Total Comments,Total Scores,Avg Sentiment (TextBlob),Avg Sentiment (Vader),Viewers (Millions)
0,MLS Cup 2023,2023,"Columbus Crew, Los Angeles FC",1,0,1,0.004167,0.00000,0.9
1,MLS Cup 2022,2022,"Los Angeles FC, Philadelphia Union",5,328,951,-0.013533,0.02574,2.2
2,MLS Cup 2021,2021,"Portland Timbers, New York City FC",5,535,189,0.092016,0.34116,1.5
3,MLS Cup 2020,2020,"Columbus Crew SC, Seattle Sounders FC",2,129,162,0.052827,0.31245,1.7
4,MLS Cup 2019,2019,"Seattle Sounders FC, Toronto FC",1,28,35,0.000000,0.00000,1.3

In [4]:
# Dataset information
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 12 entries, 0 to 11
Data columns (total 9 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   Name                      12 non-null     str
 1   Year                      12 non-null     int64
 2   Teams                     12 non-null     str
 3   Total Posts               12 non-null     int64
 4   Total Comments            12 non-null     int64
 5   Total Scores              12 non-null     int64
 6   Avg Sentiment (TextBlob)  12 non-null     float64
 7   Avg Sentiment (Vader)     12 non-null     float64
 8   Viewers (Millions)        12 non-null     float64
dtypes: float64(3), int64(4), str(2)
memory usage: 1.5 KB

In [5]:
# Select text columns
text_columns = df.select_dtypes(include=['object']).columns

text_columns

Index(['Name', 'Teams'], dtype='str')

In [6]:
# Combine all text columns into one column

df['combined_text'] = df[text_columns].fillna('').astype(str).agg(
    ' '.join, axis=1
)

df[['combined_text']].head()

                                       combined_text
0         MLS Cup 2023 Columbus Crew, Los Angeles FC
1    MLS Cup 2022 Los Angeles FC, Philadelphia Union
2    MLS Cup 2021 Portland Timbers, New York City FC
3  MLS Cup 2020 Columbus Crew SC, Seattle Sounder...
4       MLS Cup 2019 Seattle Sounders FC, Toronto FC

In [7]:
stop_words = set(stopwords.words('english'))

def clean_text(text):
    tokens = word_tokenize(text.lower())
    
    cleaned = [
        word for word in tokens
        if word.isalpha() and word not in stop_words
    ]
    
    return " ".join(cleaned)


df['clean_text'] = df['combined_text'].apply(clean_text)

df[['clean_text']].head()

                                     clean_text
0          mls cup columbus crew los angeles fc
1     mls cup los angeles fc philadelphia union
2     mls cup portland timbers new york city fc
3  mls cup columbus crew sc seattle sounders fc
4        mls cup seattle sounders fc toronto fc

In [9]:


df.head()

,Name,Year,Teams,Total Posts,Total Comments,Total Scores,Avg Sentiment (TextBlob),Avg Sentiment (Vader),Viewers (Millions),combined_text,clean_text
0,MLS Cup 2023,2023,"Columbus Crew, Los Angeles FC",1,0,1,0.004167,0.00000,0.9,"MLS Cup 2023 Columbus Crew, Los Angeles FC",mls cup columbus crew los angeles fc
1,MLS Cup 2022,2022,"Los Angeles FC, Philadelphia Union",5,328,951,-0.013533,0.02574,2.2,"MLS Cup 2022 Los Angeles FC, Philadelphia Union",mls cup los angeles fc philadelphia union
2,MLS Cup 2021,2021,"Portland Timbers, New York City FC",5,535,189,0.092016,0.34116,1.5,"MLS Cup 2021 Portland Timbers, New York City FC",mls cup portland timbers new york city fc
3,MLS Cup 2020,2020,"Columbus Crew SC, Seattle Sounders FC",2,129,162,0.052827,0.31245,1.7,"MLS Cup 2020 Columbus Crew SC, Seattle Sounder...",mls cup columbus crew sc seattle sounders fc
4,MLS Cup 2019,2019,"Seattle Sounders FC, Toronto FC",1,28,35,0.000000,0.00000,1.3,"MLS Cup 2019 Seattle Sounders FC, Toronto FC",mls cup seattle sounders fc toronto fc

In [10]:
df.to_csv(
    "MLS_Cup_KMeans_NLP_results.csv",
    index=False
)