In [1]:
!pip install pandas scikit-learn nltk matplotlib seaborn

import pandas as pd
import numpy as np

from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.cluster import KMeans
from sklearn.decomposition import PCA

import matplotlib.pyplot as plt
import seaborn as sns

import nltk
nltk.download('stopwords')
from nltk.corpus import stopwords

Requirement already satisfied: pandas in ./miniconda3/envs/coding/lib/python3.12/site-packages (3.0.4)
Requirement already satisfied: scikit-learn in ./miniconda3/envs/coding/lib/python3.12/site-packages (1.9.0)
Requirement already satisfied: nltk in ./miniconda3/envs/coding/lib/python3.12/site-packages (3.9.2)
Requirement already satisfied: matplotlib in ./miniconda3/envs/coding/lib/python3.12/site-packages (3.11.0)
Requirement already satisfied: seaborn in ./miniconda3/envs/coding/lib/python3.12/site-packages (0.13.2)
Requirement already satisfied: numpy>=1.26.0 in ./miniconda3/envs/coding/lib/python3.12/site-packages (from pandas) (2.5.0)
Requirement already satisfied: python-dateutil>=2.8.2 in ./miniconda3/envs/coding/lib/python3.12/site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: scipy>=1.10.0 in ./miniconda3/envs/coding/lib/python3.12/site-packages (from scikit-learn) (1.18.0)
Requirement already satisfied: joblib>=1.4.0 in ./miniconda3/envs/coding/lib/python3.12/site-packages (from scikit-learn) (1.5.3)
Requirement already satisfied: narwhals>=2.0.1 in ./miniconda3/envs/coding/lib/python3.12/site-packages (from scikit-learn) (2.23.0)
Requirement already satisfied: threadpoolctl>=3.5.0 in ./miniconda3/envs/coding/lib/python3.12/site-packages (from scikit-learn) (3.6.0)
Requirement already satisfied: click in ./miniconda3/envs/coding/lib/python3.12/site-packages (from nltk) (8.1.8)
Requirement already satisfied: regex>=2021.8.3 in ./miniconda3/envs/coding/lib/python3.12/site-packages (from nltk) (2025.10.23)
Requirement already satisfied: tqdm in ./miniconda3/envs/coding/lib/python3.12/site-packages (from nltk) (4.67.1)
Requirement already satisfied: contourpy>=1.0.1 in ./miniconda3/envs/coding/lib/python3.12/site-packages (from matplotlib) (1.3.3)
Requirement already satisfied: cycler>=0.10 in ./miniconda3/envs/coding/lib/python3.12/site-packages (from matplotlib) (0.12.1)
Requirement already satisfied: fonttools>=4.22.0 in ./miniconda3/envs/coding/lib/python3.12/site-packages (from matplotlib) (4.63.0)
Requirement already satisfied: kiwisolver>=1.3.1 in ./miniconda3/envs/coding/lib/python3.12/site-packages (from matplotlib) (1.5.0)
Requirement already satisfied: packaging>=20.0 in ./miniconda3/envs/coding/lib/python3.12/site-packages (from matplotlib) (26.2)
Requirement already satisfied: pillow>=9 in ./miniconda3/envs/coding/lib/python3.12/site-packages (from matplotlib) (12.3.0)
Requirement already satisfied: pyparsing>=3 in ./miniconda3/envs/coding/lib/python3.12/site-packages (from matplotlib) (3.3.2)
Requirement already satisfied: six>=1.5 in ./miniconda3/envs/coding/lib/python3.12/site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)

[nltk_data] Downloading package stopwords to
[nltk_data]     /Users/adnanaltimeemy/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!

In [2]:
df = pd.read_csv("NAPTAN.csv")

df.head()

,AtcoCode,TiplocCode,CrsCode,StationName,StationNameLang,GridType,Easting,Northing,CreationDateTime,ModificationDateTime,RevisionNumber,Modification
0,9100PENZNCE,PENZNCE,PNZ,Penzance Rail Station,NaN,U,147588,30599,2003-11-04T00:00:00,2011-09-30T14:47:28,2,rev
1,9100STIVES,STIVES,SIV,St Ives (Cornwall) Rail Station,NaN,U,151947,40127,2005-04-04T00:00:00,2011-09-30T14:47:28,4,rev
2,9100CARBISB,CARBISB,CBB,Carbis Bay Rail Station,NaN,U,152930,38745,2003-11-04T00:00:00,2011-09-30T14:47:28,5,rev
3,9100STERTH,STERTH,SER,St Erth Rail Station,NaN,U,154150,35730,2003-11-04T00:00:00,2007-02-13T17:06:21,3,rev
4,9100LELANTS,LELANTS,LTS,Lelant Saltings Rail Station,NaN,U,154430,36640,2003-11-04T00:00:00,2011-09-30T14:47:28,2,rev

In [3]:
print(df.info())
print(df.columns)

# Check missing values
print(df.isnull().sum())

<class 'pandas.DataFrame'>
RangeIndex: 2627 entries, 0 to 2626
Data columns (total 12 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   AtcoCode              2627 non-null   str
 1   TiplocCode            2627 non-null   str
 2   CrsCode               2623 non-null   str
 3   StationName           2627 non-null   str
 4   StationNameLang       0 non-null      float64
 5   GridType              2626 non-null   str
 6   Easting               2627 non-null   int64
 7   Northing              2627 non-null   int64
 8   CreationDateTime      2627 non-null   str
 9   ModificationDateTime  2627 non-null   str
 10  RevisionNumber        2627 non-null   int64
 11  Modification          2627 non-null   str
dtypes: float64(1), int64(3), str(8)
memory usage: 466.5 KB
None
Index(['AtcoCode', 'TiplocCode', 'CrsCode', 'StationName', 'StationNameLang',
       'GridType', 'Easting', 'Northing', 'CreationDateTime',
       'ModificationDateTime', 'RevisionNumber', 'Modification'],
      dtype='str')
AtcoCode                   0
TiplocCode                 0
CrsCode                    4
StationName                0
StationNameLang         2627
GridType                   1
Easting                    0
Northing                   0
CreationDateTime           0
ModificationDateTime       0
RevisionNumber             0
Modification               0
dtype: int64

In [5]:
print(df.columns)

Index(['AtcoCode', 'TiplocCode', 'CrsCode', 'StationName', 'StationNameLang',
       'GridType', 'Easting', 'Northing', 'CreationDateTime',
       'ModificationDateTime', 'RevisionNumber', 'Modification'],
      dtype='str')

In [8]:
print(df.columns)

Index(['AtcoCode', 'TiplocCode', 'CrsCode', 'StationName', 'StationNameLang',
       'GridType', 'Easting', 'Northing', 'CreationDateTime',
       'ModificationDateTime', 'RevisionNumber', 'Modification'],
      dtype='str')

In [11]:
df.head()

,AtcoCode,TiplocCode,CrsCode,StationName,StationNameLang,GridType,Easting,Northing,CreationDateTime,ModificationDateTime,RevisionNumber,Modification
0,9100PENZNCE,PENZNCE,PNZ,Penzance Rail Station,NaN,U,147588,30599,2003-11-04T00:00:00,2011-09-30T14:47:28,2,rev
1,9100STIVES,STIVES,SIV,St Ives (Cornwall) Rail Station,NaN,U,151947,40127,2005-04-04T00:00:00,2011-09-30T14:47:28,4,rev
2,9100CARBISB,CARBISB,CBB,Carbis Bay Rail Station,NaN,U,152930,38745,2003-11-04T00:00:00,2011-09-30T14:47:28,5,rev
3,9100STERTH,STERTH,SER,St Erth Rail Station,NaN,U,154150,35730,2003-11-04T00:00:00,2007-02-13T17:06:21,3,rev
4,9100LELANTS,LELANTS,LTS,Lelant Saltings Rail Station,NaN,U,154430,36640,2003-11-04T00:00:00,2011-09-30T14:47:28,2,rev

In [14]:
print("X exists:", 'X' in globals())
print("coords exists:", 'coords' in globals())

X exists: False
coords exists: False

In [16]:
print(df.columns)

Index(['AtcoCode', 'TiplocCode', 'CrsCode', 'StationName', 'StationNameLang',
       'GridType', 'Easting', 'Northing', 'CreationDateTime',
       'ModificationDateTime', 'RevisionNumber', 'Modification'],
      dtype='str')

In [20]:
print("X exists:", 'X' in globals())
print("df columns:", df.columns)

X exists: False
df columns: Index(['AtcoCode', 'TiplocCode', 'CrsCode', 'StationName', 'StationNameLang',
       'GridType', 'Easting', 'Northing', 'CreationDateTime',
       'ModificationDateTime', 'RevisionNumber', 'Modification'],
      dtype='str')