In [1]:
import pandas as pd
import numpy as np

from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder, StandardScaler
from sklearn.impute import SimpleImputer

from sklearn.linear_model import LogisticRegression
from sklearn.tree import DecisionTreeClassifier

from sklearn.metrics import accuracy_score, classification_report, confusion_matrix

In [2]:
df = pd.read_csv("NBA_head_coaches.csv")

df.head()

,Name,Teams,Start season,End season,Years in rule,Birth Date,Nationality,Start season short,End season short,Num of teams
0,Rick Adelman,"POR, GOS, SAC, HOU, MIN",1988-1989,2013-2014,23,"Jun 16, 1946",United States,1988,2013,5
1,Richie Adubato,"DET, DAL, ORL",1979-1980,1996-1997,6,-,United States,1979,1996,3
2,Danny Ainge,PHX,1996-1997,1999-2000,4,"Mar 17, 1959",United States,1996,1999,1
3,Stan Albeck,"DEN, CLE, SAN, BRK, CHI",1970-1971,1985-1986,8,-,-,1970,1985,5
4,Kenny Atkinson,BRK,2016-2017,2019-2020,4,"Jun 2, 1967",United States,2016,2019,1

In [3]:
print(df.info())
print(df.describe())
print(df.isnull().sum())

<class 'pandas.DataFrame'>
RangeIndex: 280 entries, 0 to 279
Data columns (total 10 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   Name                280 non-null    str
 1   Teams               280 non-null    str
 2   Start season        280 non-null    str
 3   End season          280 non-null    str
 4   Years in rule       280 non-null    int64
 5   Birth Date          280 non-null    str
 6   Nationality         280 non-null    str
 7   Start season short  280 non-null    int64
 8   End season short    280 non-null    str
 9   Num of teams        280 non-null    int64
dtypes: int64(3), str(7)
memory usage: 37.5 KB
None
       Years in rule  Start season short  Num of teams
count     280.000000          280.000000    280.000000
mean        5.992857         1989.625000      2.014286
std         6.267623           18.067141      1.370376
min         1.000000         1947.000000      1.000000
25%         1.750000         1975.000000      1.000000
50%         4.000000         1992.000000      1.500000
75%         8.000000         2004.000000      3.000000
max        32.000000         2019.000000      9.000000
Name                  0
Teams                 0
Start season          0
End season            0
Years in rule         0
Birth Date            0
Nationality           0
Start season short    0
End season short      0
Num of teams          0
dtype: int64

In [6]:
cat_cols = df.select_dtypes(include=['string', 'category', 'object']).columns

In [7]:
label_encoders = {}

for col in cat_cols:
    le = LabelEncoder()
    df[col] = le.fit_transform(df[col])
    label_encoders[col] = le

In [9]:
df.columns

Index(['Name', 'Teams', 'Start season', 'End season', 'Years in rule',
       'Birth Date', 'Nationality', 'Start season short', 'End season short',
       'Num of teams'],
      dtype='str')

In [12]:
df.head()

,Name,Teams,Start season,End season,Years in rule,Birth Date,Nationality,Start season short,End season short,Num of teams
0,237,144,37,53,23.0,64,3,1988.0,53,5.0
1,235,57,28,36,6.0,0,3,1979.0,36,3.0
2,50,135,45,39,4.0,75,3,1996.0,39,1.0
3,255,52,19,25,8.0,0,0,1970.0,25,5.0
4,163,18,65,58,4.0,66,3,2016.0,58,1.0