In [1]:
# Data handling
import pandas as pd
import numpy as np

# Visualisation
import matplotlib.pyplot as plt
import seaborn as sns

# NLP
import nltk
import re
import string

from nltk.corpus import stopwords
from nltk.stem import PorterStemmer

# Machine Learning
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.cluster import KMeans
from sklearn.preprocessing import StandardScaler
from sklearn.decomposition import PCA
from sklearn.metrics import silhouette_score

import warnings
warnings.filterwarnings("ignore")

In [2]:
df = pd.read_csv("netflix_genres.csv")

df.head()

   movieId                        genres
0        1  Documentary|Animation|Family
1        3           Crime|Drama|Mystery
2        4                        Family
3        5             Documentary|Sport
4        6                   Documentary

In [3]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 12279 entries, 0 to 12278
Data columns (total 2 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   movieId  12279 non-null  int64
 1   genres   12279 non-null  str
dtypes: int64(1), str(1)
memory usage: 417.5 KB

In [4]:
df = df.dropna()

df.shape

(12279, 2)

In [6]:
df.columns

Index(['movieId', 'genres'], dtype='str')

In [7]:
df.head()

   movieId                        genres
0        1  Documentary|Animation|Family
1        3           Crime|Drama|Mystery
2        4                        Family
3        5             Documentary|Sport
4        6                   Documentary

In [8]:
df.to_csv(
    "Netflix_Genres_KMeans_Clusters.csv",
    index=False
)