In [1]:
import pandas as pd
import numpy as np

from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder
from sklearn.impute import SimpleImputer

from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier

from sklearn.metrics import accuracy_score, classification_report, confusion_matrix

In [2]:
df = pd.read_csv("NETFLIX MOVIES AND TV SHOWS CLUSTERING.csv")

df.head()

  show_id  ...                                        description
0      s1  ...  In a future where the elite inhabit an island ...
1      s2  ...  After a devastating earthquake hits Mexico Cit...
2      s3  ...  When an army recruit is found dead, his fellow...
3      s4  ...  In a postapocalyptic world, rag-doll robots hi...
4      s5  ...  A brilliant group of students become card-coun...

[5 rows x 12 columns]

In [3]:
print(df.shape)
print(df.info())
print(df.isnull().sum())

(7787, 12)
<class 'pandas.DataFrame'>
RangeIndex: 7787 entries, 0 to 7786
Data columns (total 12 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   show_id       7787 non-null   str
 1   type          7787 non-null   str
 2   title         7787 non-null   str
 3   director      5398 non-null   str
 4   cast          7069 non-null   str
 5   country       7280 non-null   str
 6   date_added    7777 non-null   str
 7   release_year  7787 non-null   int64
 8   rating        7780 non-null   str
 9   duration      7787 non-null   str
 10  listed_in     7787 non-null   str
 11  description   7787 non-null   str
dtypes: int64(1), str(11)
memory usage: 3.4 MB
None
show_id            0
type               0
title              0
director        2389
cast             718
country          507
date_added        10
release_year       0
rating             7
duration           0
listed_in          0
description        0
dtype: int64

In [4]:
target = "type"  # Movie / TV Show

In [5]:
df = df.dropna(subset=[target])

In [6]:
label_encoders = {}

for col in df.columns:
    if df[col].dtype == "object":
        le = LabelEncoder()
        df[col] = df[col].astype(str)
        df[col] = le.fit_transform(df[col])
        label_encoders[col] = le

In [7]:
X = df.drop(columns=[target])
y = df[target]

In [8]:
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42
)

In [11]:
for col in X_train.columns:
    if X_train[col].astype(str).str.contains('s905', na=False).any():
        print(col)

show_id

In [14]:
X_train.head()

     show_id  ...                                        description
904     s905  ...  A tenderfoot and two gamblers seeking their fo...
1446   s1447  ...  In a city where super-powered people are ostra...
7300   s7301  ...  All the flavor. None of the BS. Star chef Davi...
2650   s2651  ...  Stories of personal victories coincide with Te...
5856   s5857  ...  Artists in LA discover the work of forgotten P...

[5 rows x 11 columns]

In [16]:
dir()

['ColumnTransformer',
 'DecisionTreeClassifier',
 'In',
 'LabelEncoder',
 'OneHotEncoder',
 'Out',
 'Pipeline',
 'RandomForestClassifier',
 'SimpleImputer',
 'X',
 'X_test',
 'X_train',
 '_',
 '_10',
 '_14',
 '_2',
 '__',
 '___',
 '__builtin__',
 '__builtins__',
 '__doc__',
 '__loader__',
 '__name__',
 '__package__',
 '__session__',
 '__spec__',
 '_dh',
 '_i',
 '_i1',
 '_i10',
 '_i11',
 '_i12',
 '_i13',
 '_i14',
 '_i15',
 '_i16',
 '_i2',
 '_i3',
 '_i4',
 '_i5',
 '_i6',
 '_i7',
 '_i8',
 '_i9',
 '_ih',
 '_ii',
 '_iii',
 '_oh',
 'accuracy_score',
 'categorical_cols',
 'classification_report',
 'col',
 'confusion_matrix',
 'df',
 'dt_model',
 'exit',
 'get_ipython',
 'label_encoders',
 'model',
 'np',
 'numeric_cols',
 'open',
 'pd',
 'preprocessor',
 'quit',
 'rf_model',
 'target',
 'train_test_split',
 'y',
 'y_test',
 'y_train']

In [18]:
print(type(rf_model))
print(hasattr(rf_model, "estimators_"))

<class 'sklearn.ensemble._forest.RandomForestClassifier'>
False