In [1]:
import pandas as pd
import numpy as np

from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier

from sklearn.metrics import accuracy_score, classification_report, confusion_matrix

In [2]:
df = pd.read_csv("pc.csv")

# Preview data
df.head()

,title,released,gf_score,metascore,genre,description,cover_art_url
0,The Witcher 3: Wild Hunt,2015-05-19,4.54,93.0,Role-Playing - Action RPG,The Witcher 3: Wild Hunt is a 2015 action role...,https://i.postimg.cc/kMcpCbwb/31921342-b7f6-40...
1,Cave Story,2004-12-20,4.48,NaN,Action - Platformer - 2D,Cave Story is a Metroidvania platform-adventur...,https://i.postimg.cc/0ymGkgxB/0fac2729-9161-43...
2,Baldur's Gate II: Shadows of Amn,2000-09-24,4.48,95.0,Role-Playing - Western-Style,Baldur's Gate II: Shadows of Amn is a role-pla...,https://i.postimg.cc/hGBLhCtP/5afe2f73-e642-4e...
3,Planescape: Torment,1999-12-14,4.43,95.0,Role-Playing - Western-Style,Planescape: Torment is a role-playing video ga...,https://i.postimg.cc/nLpmnC3X/e5d58395-00f6-49...
4,Portal 2,2011-04-19,4.43,91.0,Action - Shooter - First-Person - Arcade,Portal 2 is a first-person puzzle-platform vid...,https://images.launchbox-app.com/5aa7e40a-e9be...

In [3]:
print(df.shape)
print(df.info())
print(df.describe())
print(df.isnull().sum())

(2142, 7)
<class 'pandas.DataFrame'>
RangeIndex: 2142 entries, 0 to 2141
Data columns (total 7 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   title          2142 non-null   str
 1   released       2141 non-null   str
 2   gf_score       2139 non-null   float64
 3   metascore      1408 non-null   float64
 4   genre          2142 non-null   str
 5   description    2109 non-null   str
 6   cover_art_url  1966 non-null   str
dtypes: float64(2), str(5)
memory usage: 1.4 MB
None
          gf_score    metascore
count  2139.000000  1408.000000
mean      3.766718    77.226562
std       0.380558    10.055875
min       0.870000     8.000000
25%       3.560000    72.000000
50%       3.810000    79.000000
75%       4.030000    84.000000
max       4.610000    99.000000
title              0
released           1
gf_score           3
metascore        734
genre              0
description       33
cover_art_url    176
dtype: int64

In [6]:
cat_cols = df.select_dtypes(include=['object', 'string']).columns

In [9]:
df.columns

Index(['title', 'released', 'gf_score', 'metascore', 'genre', 'description',
       'cover_art_url'],
      dtype='str')

In [12]:
print(list(df.columns))

['title', 'released', 'gf_score', 'metascore', 'genre', 'description', 'cover_art_url']

In [14]:
df.head()

,title,released,gf_score,metascore,genre,description,cover_art_url
0,The Witcher 3: Wild Hunt,2015-05-19,4.54,93.0,Role-Playing - Action RPG,The Witcher 3: Wild Hunt is a 2015 action role...,https://i.postimg.cc/kMcpCbwb/31921342-b7f6-40...
1,Cave Story,2004-12-20,4.48,79.0,Action - Platformer - 2D,Cave Story is a Metroidvania platform-adventur...,https://i.postimg.cc/0ymGkgxB/0fac2729-9161-43...
2,Baldur's Gate II: Shadows of Amn,2000-09-24,4.48,95.0,Role-Playing - Western-Style,Baldur's Gate II: Shadows of Amn is a role-pla...,https://i.postimg.cc/hGBLhCtP/5afe2f73-e642-4e...
3,Planescape: Torment,1999-12-14,4.43,95.0,Role-Playing - Western-Style,Planescape: Torment is a role-playing video ga...,https://i.postimg.cc/nLpmnC3X/e5d58395-00f6-49...
4,Portal 2,2011-04-19,4.43,91.0,Action - Shooter - First-Person - Arcade,Portal 2 is a first-person puzzle-platform vid...,https://images.launchbox-app.com/5aa7e40a-e9be...

In [16]:
df.head()
df.columns

Index(['title', 'released', 'gf_score', 'metascore', 'genre', 'description',
       'cover_art_url'],
      dtype='str')

In [18]:
(df.columns)

Index(['title', 'released', 'gf_score', 'metascore', 'genre', 'description',
       'cover_art_url'],
      dtype='str')

In [20]:
df.head()
df.columns

Index(['title', 'released', 'gf_score', 'metascore', 'genre', 'description',
       'cover_art_url'],
      dtype='str')