In [1]:
import pandas as pd
import numpy as np

from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier

from sklearn.metrics import accuracy_score, classification_report, confusion_matrix

In [2]:
df = pd.read_csv("PitcherPaino.csv")

df.head()

           site        lat  ...                           email web
0  PitcherPaino  52.478423  ...  birmingham@pitcherandpiano.com NaN
1  PitcherPaino  51.449818  ...     bristol@pitcherandpiano.com NaN
2  PitcherPaino  53.991741  ...   harrogate@pitcherandpiano.com NaN
3  PitcherPaino  51.947574  ...     hitchin@pitcherandpiano.com NaN
4  PitcherPaino  51.513178  ...    cornhill@pitcherandpiano.com NaN

[5 rows x 9 columns]

In [3]:
print(df.shape)
print(df.info())
print(df.describe())
print(df.isnull().sum())

(15, 9)
<class 'pandas.DataFrame'>
RangeIndex: 15 entries, 0 to 14
Data columns (total 9 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   site     15 non-null     str
 1   lat      15 non-null     float64
 2   lng      15 non-null     float64
 3   zip      15 non-null     str
 4   name     15 non-null     str
 5   address  15 non-null     str
 6   phone    15 non-null     str
 7   email    15 non-null     str
 8   web      0 non-null      float64
dtypes: float64(3), str(6)
memory usage: 2.6 KB
None
             lat        lng  web
count  15.000000  15.000000  0.0
mean   52.244185  -1.236228  NaN
std     1.301784   0.908727  NaN
min    50.897422  -3.104173  NaN
25%    51.291026  -1.570192  NaN
50%    51.513178  -1.310906  NaN
75%    53.165816  -0.639096  NaN
max    54.970525   0.261607  NaN
site        0
lat         0
lng         0
zip         0
name        0
address     0
phone       0
email       0
web        15
dtype: int64

In [8]:
import numpy as np

df[df.select_dtypes(include=np.number).columns] = df.select_dtypes(include=np.number).fillna(
    df.select_dtypes(include=np.number).median()
)

for col in df.select_dtypes(include=["object", "string"]).columns:
    df[col] = df[col].fillna(df[col].mode()[0])

In [10]:
df.select_dtypes(include='object')

Empty DataFrame
Columns: []
Index: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14]

In [12]:
print(df.index)

RangeIndex(start=0, stop=15, step=1)

In [15]:
print(df.columns)

Index(['site', 'lat', 'lng', 'zip', 'name', 'address', 'phone', 'email',
       'web'],
      dtype='str')

In [17]:
df.head()
df.columns

Index(['site', 'lat', 'lng', 'zip', 'name', 'address', 'phone', 'email',
       'web'],
      dtype='str')

In [19]:
df.isnull().sum()

site        0
lat         0
lng         0
zip         0
name        0
address     0
phone       0
email       0
web        15
dtype: int64

In [21]:
print(locals().keys())

dict_keys(['__name__', '__doc__', '__package__', '__loader__', '__spec__', '__builtin__', '__builtins__', '_ih', '_oh', '_dh', 'In', 'Out', 'get_ipython', 'exit', 'quit', 'open', '_', '__', '___', '__session__', '_i', '_ii', '_iii', '_i1', 'pd', 'np', 'train_test_split', 'LabelEncoder', 'DecisionTreeClassifier', 'RandomForestClassifier', 'accuracy_score', 'classification_report', 'confusion_matrix', '_i2', 'df', '_2', '_i3', '_i4', 'col', '_i5', '_5', '_i6', '_i7', '_i8', '_i9', 'label_encoders', 'le', '_i10', '_10', '_i11', '_i12', '_i13', '_i14', '_i15', '_i16', 'dt_model', '_i17', '_17', '_i18', 'rf_model', '_i19', '_19', '_i20', '_i21'])

In [24]:
print(globals().keys())

dict_keys(['__name__', '__doc__', '__package__', '__loader__', '__spec__', '__builtin__', '__builtins__', '_ih', '_oh', '_dh', 'In', 'Out', 'get_ipython', 'exit', 'quit', 'open', '_', '__', '___', '__session__', '_i', '_ii', '_iii', '_i1', 'pd', 'np', 'train_test_split', 'LabelEncoder', 'DecisionTreeClassifier', 'RandomForestClassifier', 'accuracy_score', 'classification_report', 'confusion_matrix', '_i2', 'df', '_2', '_i3', '_i4', 'col', '_i5', '_5', '_i6', '_i7', '_i8', '_i9', 'label_encoders', 'le', '_i10', '_10', '_i11', '_i12', '_i13', '_i14', '_i15', '_i16', 'dt_model', '_i17', '_17', '_i18', 'rf_model', '_i19', '_19', '_i20', '_i21', '_i22', 'plt', '_i23', '_i24'])