In [1]:
import pandas as pd
import numpy as np

from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix

In [2]:
df = pd.read_csv("playstation.csv")

# View first rows
df.head()

,title,released,gf_score,metascore,genre,description,cover_art_url
0,Castlevania: Symphony of the Night,1997-10-02,4.60,93.0,Role Playing » Action RPG,Castlevania: Symphony of the Night is a platfo...,https://gamesdb-images.launchbox.gg/r2_280ac27...
1,Metal Gear Solid,1998-09-03,4.57,94.0,Action Adventure » General,"You are Snake, a government agent on a mission...",https://i.postimg.cc/gkN0CvMQ/5e05d377-f292-41...
2,Suikoden II,1998-12-17,4.55,82.0,Role-Playing » Japanese-Style,Sequel to the early PlayStation RPG. As a memb...,https://i.postimg.cc/xTTf3X0R/df590b33-d911-41...
3,Final Fantasy VII,1997-01-31,4.49,92.0,Role-Playing » Japanese-Style,Final Fantasy VII is a role-playing game devel...,https://images.launchbox-app.com//734efb56-900...
4,Chrono Trigger,1999-11-11,4.43,NaN,Role-Playing » Japanese-Style,CHRONO TRIGGER has been hailed as one of the g...,https://i.postimg.cc/cJQGSWxC/10941-chrono-tri...

In [3]:
df.info()
df.describe()
df.isnull().sum()

<class 'pandas.DataFrame'>
RangeIndex: 600 entries, 0 to 599
Data columns (total 7 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   title          600 non-null    str
 1   released       556 non-null    str
 2   gf_score       600 non-null    float64
 3   metascore      153 non-null    float64
 4   genre          599 non-null    str
 5   description    600 non-null    str
 6   cover_art_url  598 non-null    str
dtypes: float64(2), str(5)
memory usage: 342.9 KB

title              0
released          44
gf_score           0
metascore        447
genre              1
description        0
cover_art_url      2
dtype: int64

In [4]:
df = df.dropna()  # or use fillna() depending on dataset

In [6]:
if target in df.columns:
    X = df.drop(columns=[target])
    y = df[target]
else:
    print("Target column not found. Available columns:", df.columns)

Target column not found. Available columns: Index(['title', 'released', 'gf_score', 'metascore', 'genre', 'description',
       'cover_art_url'],
      dtype='str')

In [8]:
df.head()

,title,released,gf_score,metascore,genre,description,cover_art_url
0,Castlevania: Symphony of the Night,1997-10-02,4.60,93.0,Role Playing » Action RPG,Castlevania: Symphony of the Night is a platfo...,https://gamesdb-images.launchbox.gg/r2_280ac27...
1,Metal Gear Solid,1998-09-03,4.57,94.0,Action Adventure » General,"You are Snake, a government agent on a mission...",https://i.postimg.cc/gkN0CvMQ/5e05d377-f292-41...
2,Suikoden II,1998-12-17,4.55,82.0,Role-Playing » Japanese-Style,Sequel to the early PlayStation RPG. As a memb...,https://i.postimg.cc/xTTf3X0R/df590b33-d911-41...
3,Final Fantasy VII,1997-01-31,4.49,92.0,Role-Playing » Japanese-Style,Final Fantasy VII is a role-playing game devel...,https://images.launchbox-app.com//734efb56-900...
5,Final Fantasy Tactics,1998-01-28,4.41,83.0,Strategy » Turn-Based » Tactics,Final Fantasy Tactics is a tactical role-playi...,https://i.postimg.cc/85487brV/fftacticspsx-Cas...

In [10]:
df.columns

Index(['title', 'released', 'gf_score', 'metascore', 'genre', 'description',
       'cover_art_url'],
      dtype='str')