In [1]:
import pandas as pd
import numpy as np

from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier

from sklearn.metrics import accuracy_score, classification_report, confusion_matrix

In [2]:
df = pd.read_csv("products.csv")

df.head()

   product_id  ...  price
0           1  ...  12.56
1           2  ...  28.86
2           3  ...  25.67
3           4  ...  39.60
4           5  ...  42.96

[5 rows x 5 columns]

In [3]:
df.info()
df.describe()
df.isnull().sum()

<class 'pandas.DataFrame'>
RangeIndex: 999 entries, 0 to 998
Data columns (total 5 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   product_id     999 non-null    int64
 1   product_name   999 non-null    str
 2   aisle_id       999 non-null    int64
 3   department_id  999 non-null    int64
 4   price          999 non-null    float64
dtypes: float64(1), int64(3), str(1)
memory usage: 69.6 KB

product_id       0
product_name     0
aisle_id         0
department_id    0
price            0
dtype: int64

In [5]:
for col in df.select_dtypes(include=np.number).columns:
    df[col] = df[col].fillna(df[col].median())

In [7]:
df = pd.get_dummies(df, columns=df.select_dtypes(include=['object','string']).columns)

In [9]:
target = "category"

if target in df.columns:
    X = df.drop(columns=[target])
    y = df[target]
else:
    print("Target column not found. Available columns:", df.columns)

Target column not found. Available columns: Index(['product_id', 'product_name', 'aisle_id', 'department_id', 'price'], dtype='str')

In [12]:
df.head()

   product_id  product_name  aisle_id  department_id  price
0           1           175        61             19  12.56
1           2            40       104             13  28.86
2           3           737        94              7  25.67
3           4           783        38              1  39.60
4           5           387         5             13  42.96

In [15]:
print("X_train" in globals())
print("y_test" in globals())

False
False