In [1]:
# Data handling
import pandas as pd
import numpy as np

# NLP
import re
import nltk
from nltk.corpus import stopwords
from nltk.stem import PorterStemmer

# Machine Learning
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.cluster import KMeans
from sklearn.decomposition import PCA
from sklearn.metrics import silhouette_score

# Visualization
import matplotlib.pyplot as plt

# Download NLP resources
nltk.download('stopwords')

[nltk_data] Downloading package stopwords to
[nltk_data]     /Users/adnanaltimeemy/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!

True

In [2]:
# Load CSV file
df = pd.read_csv("product_dataset.csv")

# Display first rows
df.head()

       PRODUCT NAME  RATING  SALES
0           banana        3      1
1   banana icecream       5      2
2     banana yogurt       2      0
3  banana face mask       4      1
4      banana chips       3      1

In [3]:
# Show columns
print(df.columns)

# Find text columns
text_columns = df.select_dtypes(include=['object']).columns

print("Text columns:", text_columns)

Index(['PRODUCT NAME', 'RATING', 'SALES'], dtype='str')
Text columns: Index(['PRODUCT NAME'], dtype='str')

/var/folders/88/w4w1n8l12kd_z42_6mrnndmw0000gn/T/ipykernel_7306/1876283280.py:5: Pandas4Warning: For backward compatibility, 'str' dtypes are included by select_dtypes when 'object' dtype is specified. This behavior is deprecated and will be removed in a future version. Explicitly pass 'str' to `include` to select them, or to `exclude` to remove them and silence this warning.
See https://pandas.pydata.org/docs/user_guide/migration-3-strings.html#string-migration-select-dtypes for details on how to write code that works with pandas 2 and 3.
  text_columns = df.select_dtypes(include=['object']).columns

In [5]:


df.head()

       PRODUCT NAME  RATING  SALES
0           banana        3      1
1   banana icecream       5      2
2     banana yogurt       2      0
3  banana face mask       4      1
4      banana chips       3      1

In [7]:
df.head()

       PRODUCT NAME  RATING  SALES
0           banana        3      1
1   banana icecream       5      2
2     banana yogurt       2      0
3  banana face mask       4      1
4      banana chips       3      1

In [8]:
df.to_csv(
    "product_dataset_clustered.csv",
    index=False
)

print("Saved successfully!")

Saved successfully!