In [1]:
import pandas as pd
import numpy as np

from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix

In [2]:
df = pd.read_csv("Rdatasets.csv")

df.head()

,Package,Item,Title,Rows,Cols,n_binary,n_character,n_factor,n_logical,n_numeric,CSV,Doc
0,AER,Affairs,Fair's Extramarital Affairs Data,601,9,2,0,2,0,7,https://vincentarelbundock.github.io/Rdatasets...,https://vincentarelbundock.github.io/Rdatasets...
1,AER,ArgentinaCPI,Consumer Price Index in Argentina,80,2,0,0,0,0,2,https://vincentarelbundock.github.io/Rdatasets...,https://vincentarelbundock.github.io/Rdatasets...
2,AER,BankWages,Bank Wages,474,4,2,0,3,0,1,https://vincentarelbundock.github.io/Rdatasets...,https://vincentarelbundock.github.io/Rdatasets...
3,AER,BenderlyZwick,"Benderly and Zwick Data: Inflation, Growth and...",31,5,0,0,0,0,5,https://vincentarelbundock.github.io/Rdatasets...,https://vincentarelbundock.github.io/Rdatasets...
4,AER,BondYield,Bond Yield Data,60,2,0,0,0,0,2,https://vincentarelbundock.github.io/Rdatasets...,https://vincentarelbundock.github.io/Rdatasets...

In [3]:
print(df.shape)
print(df.info())
print(df.isnull().sum())

(1478, 12)
<class 'pandas.DataFrame'>
RangeIndex: 1478 entries, 0 to 1477
Data columns (total 12 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   Package      1478 non-null   str
 1   Item         1478 non-null   str
 2   Title        1478 non-null   str
 3   Rows         1478 non-null   int64
 4   Cols         1478 non-null   int64
 5   n_binary     1478 non-null   int64
 6   n_character  1478 non-null   int64
 7   n_factor     1478 non-null   int64
 8   n_logical    1478 non-null   int64
 9   n_numeric    1478 non-null   int64
 10  CSV          1478 non-null   str
 11  Doc          1478 non-null   str
dtypes: int64(7), str(5)
memory usage: 414.4 KB
None
Package        0
Item           0
Title          0
Rows           0
Cols           0
n_binary       0
n_character    0
n_factor       0
n_logical      0
n_numeric      0
CSV            0
Doc            0
dtype: int64

In [4]:
df = df.dropna()

In [5]:
df.columns

Index(['Package', 'Item', 'Title', 'Rows', 'Cols', 'n_binary', 'n_character',
       'n_factor', 'n_logical', 'n_numeric', 'CSV', 'Doc'],
      dtype='str')

In [8]:
df.head()

,Package,Item,Title,Rows,Cols,n_binary,n_character,n_factor,n_logical,n_numeric,CSV,Doc
0,AER,Affairs,Fair's Extramarital Affairs Data,601,9,2,0,2,0,7,https://vincentarelbundock.github.io/Rdatasets...,https://vincentarelbundock.github.io/Rdatasets...
1,AER,ArgentinaCPI,Consumer Price Index in Argentina,80,2,0,0,0,0,2,https://vincentarelbundock.github.io/Rdatasets...,https://vincentarelbundock.github.io/Rdatasets...
2,AER,BankWages,Bank Wages,474,4,2,0,3,0,1,https://vincentarelbundock.github.io/Rdatasets...,https://vincentarelbundock.github.io/Rdatasets...
3,AER,BenderlyZwick,"Benderly and Zwick Data: Inflation, Growth and...",31,5,0,0,0,0,5,https://vincentarelbundock.github.io/Rdatasets...,https://vincentarelbundock.github.io/Rdatasets...
4,AER,BondYield,Bond Yield Data,60,2,0,0,0,0,2,https://vincentarelbundock.github.io/Rdatasets...,https://vincentarelbundock.github.io/Rdatasets...

In [10]:
print("y_test" in globals())
print("dt_pred" in globals())
print("rf_pred" in globals())

False
False
False