In [1]:
import pandas as pd
import numpy as np

from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.cluster import KMeans
from sklearn.decomposition import PCA

import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
df = pd.read_csv("recruiting_costs.csv")

# Preview data
df.head()

,Employment Source,January,February,March,April,May,June,July,August,September,October,November,December,Total
0,Billboard,520,520,520,520,0,0,612,612,729,749,910,500,6192
1,Careerbuilder,410,410,410,820,820,410,410,820,820,1230,820,410,7790
2,Company Intranet - Partner,0,0,0,0,0,0,0,0,0,0,0,0,0
3,Diversity Job Fair,0,5129,0,0,0,0,0,4892,0,0,0,0,10021
4,Employee Referral,0,0,0,0,0,0,0,0,0,0,0,0,0

In [4]:
print(df.columns)

Index(['Employment Source', 'January ', 'February', 'March', 'April', 'May',
       'June', 'July', 'August', 'September', 'October', 'November',
       'December', 'Total'],
      dtype='str')

In [6]:
print(df.columns.tolist())

['Employment Source', 'January ', 'February', 'March', 'April', 'May', 'June', 'July', 'August', 'September', 'October', 'November', 'December', 'Total']

In [7]:
df.head()

,Employment Source,January,February,March,April,May,June,July,August,September,October,November,December,Total
0,Billboard,520,520,520,520,0,0,612,612,729,749,910,500,6192
1,Careerbuilder,410,410,410,820,820,410,410,820,820,1230,820,410,7790
2,Company Intranet - Partner,0,0,0,0,0,0,0,0,0,0,0,0,0
3,Diversity Job Fair,0,5129,0,0,0,0,0,4892,0,0,0,0,10021
4,Employee Referral,0,0,0,0,0,0,0,0,0,0,0,0,0

In [9]:
print(df.columns.tolist())
print(df.head())

['Employment Source', 'January ', 'February', 'March', 'April', 'May', 'June', 'July', 'August', 'September', 'October', 'November', 'December', 'Total']
            Employment Source  January   February  March  April  May  June  \
0                   Billboard       520       520    520    520    0     0
1               Careerbuilder       410       410    410    820  820   410
2  Company Intranet - Partner         0         0      0      0    0     0
3          Diversity Job Fair         0      5129      0      0    0     0
4           Employee Referral         0         0      0      0    0     0

   July  August  September  October  November  December  Total
0   612     612        729      749       910       500   6192
1   410     820        820     1230       820       410   7790
2     0       0          0        0         0         0      0
3     0    4892          0        0         0         0  10021
4     0       0          0        0         0         0      0

In [11]:
print("X_text" in globals())
print("vectorizer" in globals())
print("kmeans" in globals())

False
True
False

In [13]:
print("X_text" in globals())
print("X_combined" in globals())

False
False