In [1]:
import pandas as pd
import numpy as np

# Load dataset
df = pd.read_csv("rmp_wit_comments.csv")

# Preview
df.head()

     course                                           comments
0  MATH1900  He is very enthusiastic to help students. His ...
1   MATH250  Great professor, really wants his students to ...
2  MATH2860  Lectures are clear and pretty easy to follow. ...
3  MATH2860  He is a great professor. He mixes humor into a...
4  MATH2025  i found him to be a good professor he keeps th...

In [2]:
import pandas as pd
import numpy as np

# Load dataset
df = pd.read_csv("rmp_wit_comments.csv")

# Preview
df.head()

     course                                           comments
0  MATH1900  He is very enthusiastic to help students. His ...
1   MATH250  Great professor, really wants his students to ...
2  MATH2860  Lectures are clear and pretty easy to follow. ...
3  MATH2860  He is a great professor. He mixes humor into a...
4  MATH2025  i found him to be a good professor he keeps th...

In [3]:
print(df.shape)
print(df.columns)
print(df.isnull().sum())

(18, 2)
Index(['course', 'comments'], dtype='str')
course      0
comments    0
dtype: int64

In [5]:
df.columns = df.columns.str.strip()
print(df.columns)

Index(['course', 'comments'], dtype='str')

In [8]:
print(df.columns)

Index(['course', 'comments'], dtype='str')

In [10]:
# Check columns
print(df.columns)

Index(['course', 'comments'], dtype='str')

In [16]:
print(df.columns)

Index(['course', 'comments'], dtype='str')

In [18]:
print(df.columns)

Index(['course', 'comments'], dtype='str')