In [1]:
import pandas as pd
import numpy as np

from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder
from sklearn.metrics import accuracy_score, classification_report

from sklearn.ensemble import RandomForestClassifier, ExtraTreesClassifier

In [2]:
df = pd.read_csv("runways.csv")

df.head()

       id  airport_ref  ... he_displaced_threshold_ft  Unnamed: 20
0  269408         6523  ...                       NaN          NaN
1  255155         6524  ...                       NaN          NaN
2  254165         6525  ...                       NaN          NaN
3  270932         6526  ...                       NaN          NaN
4  322128       322127  ...                       NaN          NaN

[5 rows x 21 columns]

In [3]:
print(df.shape)
print(df.info())
print(df.isnull().sum())

(40979, 21)
<class 'pandas.DataFrame'>
RangeIndex: 40979 entries, 0 to 40978
Data columns (total 21 columns):
 #   Column                     Non-Null Count  Dtype
---  ------                     --------------  -----
 0   id                         40979 non-null  int64
 1   airport_ref                40979 non-null  int64
 2   airport_ident              40979 non-null  str
 3   length_ft                  40810 non-null  float64
 4   width_ft                   38343 non-null  float64
 5   surface                    40721 non-null  str
 6   lighted                    40979 non-null  int64
 7   closed                     40979 non-null  int64
 8   le_ident                   40860 non-null  str
 9   le_latitude_deg            14242 non-null  float64
 10  le_longitude_deg           14239 non-null  float64
 11  le_elevation_ft            12117 non-null  float64
 12  le_heading_degT            14040 non-null  float64
 13  le_displaced_threshold_ft  2804 non-null   float64
 14  he_ident                   34838 non-null  str
 15  he_latitude_deg            14229 non-null  float64
 16  he_longitude_deg           14231 non-null  float64
 17  he_elevation_ft            12005 non-null  float64
 18  he_heading_degT            15853 non-null  float64
 19  he_displaced_threshold_ft  3116 non-null   float64
 20  Unnamed: 20                0 non-null      float64
dtypes: float64(13), int64(4), str(4)
memory usage: 7.0 MB
None
id                               0
airport_ref                      0
airport_ident                    0
length_ft                      169
width_ft                      2636
surface                        258
lighted                          0
closed                           0
le_ident                       119
le_latitude_deg              26737
le_longitude_deg             26740
le_elevation_ft              28862
le_heading_degT              26939
le_displaced_threshold_ft    38175
he_ident                      6141
he_latitude_deg              26750
he_longitude_deg             26748
he_elevation_ft              28974
he_heading_degT              25126
he_displaced_threshold_ft    37863
Unnamed: 20                  40979
dtype: int64

In [4]:
df = df.dropna()

In [6]:
df.select_dtypes(include=['object'])

Empty DataFrame
Columns: []
Index: []

In [7]:
X = df.iloc[:, :-1]   # all columns except last
y = df.iloc[:, -1]    # last column as target

In [9]:
print("X type:", type(X))
print("X shape:", getattr(X, "shape", None))

print("y type:", type(y))
print("y shape:", getattr(y, "shape", None))

X type: <class 'pandas.DataFrame'>
X shape: (0, 20)
y type: <class 'pandas.Series'>
y shape: (0,)

In [10]:
print(df.shape)
print(df.head())
print(df.columns)

(0, 21)
Empty DataFrame
Columns: [id, airport_ref, airport_ident, length_ft, width_ft, surface, lighted, closed, le_ident, le_latitude_deg, le_longitude_deg, le_elevation_ft, le_heading_degT, le_displaced_threshold_ft, he_ident, he_latitude_deg, he_longitude_deg, he_elevation_ft, he_heading_degT, he_displaced_threshold_ft, Unnamed: 20]
Index: []
Index(['id', 'airport_ref', 'airport_ident', 'length_ft', 'width_ft',
       'surface', 'lighted', 'closed', 'le_ident', 'le_latitude_deg',
       'le_longitude_deg', 'le_elevation_ft', 'le_heading_degT',
       'le_displaced_threshold_ft', 'he_ident', 'he_latitude_deg',
       'he_longitude_deg', 'he_elevation_ft', 'he_heading_degT',
       'he_displaced_threshold_ft', 'Unnamed: 20'],
      dtype='str')

In [14]:
for col in df.columns:
    print(col, df[col].nunique())

id 0
airport_ref 0
airport_ident 0
length_ft 0
width_ft 0
surface 0
lighted 0
closed 0
le_ident 0
le_latitude_deg 0
le_longitude_deg 0
le_elevation_ft 0
le_heading_degT 0
le_displaced_threshold_ft 0
he_ident 0
he_latitude_deg 0
he_longitude_deg 0
he_elevation_ft 0
he_heading_degT 0
he_displaced_threshold_ft 0
Unnamed: 20 0

In [17]:
'rf_model' in globals()

False

In [20]:
print(df.head())
print(df.columns)

Empty DataFrame
Columns: [id, airport_ref, airport_ident, length_ft, width_ft, surface, lighted, closed, le_ident, le_latitude_deg, le_longitude_deg, le_elevation_ft, le_heading_degT, le_displaced_threshold_ft, he_ident, he_latitude_deg, he_longitude_deg, he_elevation_ft, he_heading_degT, he_displaced_threshold_ft, Unnamed: 20]
Index: []
Index(['id', 'airport_ref', 'airport_ident', 'length_ft', 'width_ft',
       'surface', 'lighted', 'closed', 'le_ident', 'le_latitude_deg',
       'le_longitude_deg', 'le_elevation_ft', 'le_heading_degT',
       'le_displaced_threshold_ft', 'he_ident', 'he_latitude_deg',
       'he_longitude_deg', 'he_elevation_ft', 'he_heading_degT',
       'he_displaced_threshold_ft', 'Unnamed: 20'],
      dtype='str')