In [1]:
import pandas as pd
import numpy as np

from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder, StandardScaler
from sklearn.impute import SimpleImputer

from sklearn.linear_model import LogisticRegression
from sklearn.tree import DecisionTreeClassifier

from sklearn.metrics import accuracy_score, classification_report, confusion_matrix

In [2]:
df = pd.read_csv("SalCampChicken_Metadata.csv")

df.head()

/var/folders/88/w4w1n8l12kd_z42_6mrnndmw0000gn/T/ipykernel_6470/2187136233.py:1: DtypeWarning: Columns (0: Description, 1: Type) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv("SalCampChicken_Metadata.csv")

,Variable,Description,Type
0,EstablishmentID,A unique numeric identifier that is used to id...,Non-predictor
1,EstablishmentNumber,A letter/number combination uniquely identifyi...,Non-predictor
2,EstablishmentName,The name of an establishment on its FSIS grant...,Non-predictor
3,State,The state where the establishment is located.,Non-predictor
4,ProjectCode,A short name given to easily identify an FSIS ...,Non-predictor

In [3]:
print(df.shape)
print(df.info())
print(df.isnull().sum())

(1048575, 3)
<class 'pandas.DataFrame'>
RangeIndex: 1048575 entries, 0 to 1048574
Data columns (total 3 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   Variable     5965 non-null   str
 1   Description  43 non-null     str
 2   Type         43 non-null     str
dtypes: str(3)
memory usage: 24.5 MB
None
Variable       1042610
Description    1048532
Type           1048532
dtype: int64

In [5]:
print(df.columns)

Index(['Variable', 'Description', 'Type'], dtype='str')

In [7]:
df.head()

,Variable,Description,Type
0,EstablishmentID,A unique numeric identifier that is used to id...,Non-predictor
1,EstablishmentNumber,A letter/number combination uniquely identifyi...,Non-predictor
2,EstablishmentName,The name of an establishment on its FSIS grant...,Non-predictor
3,State,The state where the establishment is located.,Non-predictor
4,ProjectCode,A short name given to easily identify an FSIS ...,Non-predictor

In [9]:
print(df.columns.tolist())

['Variable', 'Description', 'Type']

In [10]:
print(df.columns.tolist())

['Variable', 'Description', 'Type']

In [13]:
df.columns

Index(['Variable', 'Description', 'Type'], dtype='str')

In [17]:
print(df.head())
print(df.columns)
print(df.shape)

              Variable                                        Description  \
0      EstablishmentID  A unique numeric identifier that is used to id...
1  EstablishmentNumber  A letter/number combination uniquely identifyi...
2    EstablishmentName  The name of an establishment on its FSIS grant...
3                State      The state where the establishment is located.
4          ProjectCode  A short name given to easily identify an FSIS ...

            Type
0  Non-predictor
1  Non-predictor
2  Non-predictor
3  Non-predictor
4  Non-predictor
Index(['Variable', 'Description', 'Type'], dtype='str')
(1048575, 3)

In [20]:
df.head()

,Variable,Description,Type
0,EstablishmentID,A unique numeric identifier that is used to id...,Non-predictor
1,EstablishmentNumber,A letter/number combination uniquely identifyi...,Non-predictor
2,EstablishmentName,The name of an establishment on its FSIS grant...,Non-predictor
3,State,The state where the establishment is located.,Non-predictor
4,ProjectCode,A short name given to easily identify an FSIS ...,Non-predictor