In [1]:
import pandas as pd
import numpy as np

from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier

from sklearn.metrics import accuracy_score, classification_report, confusion_matrix
import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
df = pd.read_csv("sea_stream.csv")

df.head()

    attrib1   attrib2   attrib3  class
0  0.080429  8.397187  7.074928      0
1  1.420740  7.504724  6.764101      0
2  0.960543  5.168416  8.298959      0
3  3.367279  6.797711  4.857875      1
4  9.265933  8.548432  2.460325      1

In [3]:
print(df.shape)
print(df.info())
print(df.describe())

# Check missing values
print(df.isnull().sum())

(40000, 4)
<class 'pandas.DataFrame'>
RangeIndex: 40000 entries, 0 to 39999
Data columns (total 4 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   attrib1  40000 non-null  float64
 1   attrib2  40000 non-null  float64
 2   attrib3  40000 non-null  float64
 3   class    40000 non-null  int64
dtypes: float64(3), int64(1)
memory usage: 1.2 MB
None
            attrib1       attrib2       attrib3         class
count  40000.000000  40000.000000  40000.000000  40000.000000
mean       5.010913      4.995735      5.009759      0.576625
std        2.887277      2.885928      2.885995      0.494100
min        0.000239      0.000096      0.000368      0.000000
25%        2.496638      2.512360      2.518148      0.000000
50%        5.018156      4.969724      5.011769      1.000000
75%        7.497381      7.492722      7.505984      1.000000
max        9.999905      9.999350      9.999982      1.000000
attrib1    0
attrib2    0
attrib3    0
class      0
dtype: int64

In [6]:
df.head()

    attrib1   attrib2   attrib3  class
0  0.080429  8.397187  7.074928      0
1  1.420740  7.504724  6.764101      0
2  0.960543  5.168416  8.298959      0
3  3.367279  6.797711  4.857875      1
4  9.265933  8.548432  2.460325      1

In [7]:
label_encoders = {}

for col in df.select_dtypes(include='object').columns:
    le = LabelEncoder()
    df[col] = le.fit_transform(df[col])
    label_encoders[col] = le

In [9]:
df.columns = df.columns.str.strip()

In [11]:
df.columns

Index(['attrib1', 'attrib2', 'attrib3', 'class'], dtype='str')

In [13]:
df.columns = df.columns.str.strip()
print(df.columns)

Index(['attrib1', 'attrib2', 'attrib3', 'class'], dtype='str')

In [15]:
df.columns = df.columns.str.strip()

In [17]:
print(df.columns)

Index(['attrib1', 'attrib2', 'attrib3', 'class'], dtype='str')