In [1]:
# NLP libraries
import pandas as pd
import numpy as np
import re

# Persian NLP
!pip install hazm

from hazm import Normalizer, word_tokenize, stopwords_list, Stemmer

# Machine Learning
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.cluster import KMeans
from sklearn.metrics import silhouette_score

# Visualization
import matplotlib.pyplot as plt
from sklearn.decomposition import PCA

Collecting hazm
  Downloading hazm-0.12.1-py3-none-any.whl.metadata (9.3 kB)
Collecting flashtext<3.0,>=2.7 (from hazm)
  Downloading flashtext-2.7.tar.gz (14 kB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
Requirement already satisfied: huggingface-hub>=0.25.0 in ./miniconda3/envs/coding/lib/python3.12/site-packages (from hazm) (0.36.0)
Requirement already satisfied: nltk<4.0.0,>=3.9.0 in ./miniconda3/envs/coding/lib/python3.12/site-packages (from hazm) (3.9.2)
Collecting python-crfsuite<0.10.0,>=0.9.12 (from hazm)
  Downloading python_crfsuite-0.9.12-cp312-cp312-macosx_11_0_arm64.whl.metadata (4.3 kB)
Collecting tqdm<5.0.0,>=4.67.3 (from hazm)
  Downloading tqdm-4.68.4-py3-none-any.whl.metadata (57 kB)
Requirement already satisfied: click in ./miniconda3/envs/coding/lib/python3.12/site-packages (from nltk<4.0.0,>=3.9.0->hazm) (8.1.8)
Requirement already satisfied: joblib in ./miniconda3/envs/coding/lib/python3.12/site-packages (from nltk<4.0.0,>=3.9.0->hazm) (1.5.3)
Requirement already satisfied: regex>=2021.8.3 in ./miniconda3/envs/coding/lib/python3.12/site-packages (from nltk<4.0.0,>=3.9.0->hazm) (2025.10.23)
Requirement already satisfied: filelock in ./miniconda3/envs/coding/lib/python3.12/site-packages (from huggingface-hub>=0.25.0->hazm) (3.20.0)
Requirement already satisfied: fsspec>=2023.5.0 in ./miniconda3/envs/coding/lib/python3.12/site-packages (from huggingface-hub>=0.25.0->hazm) (2025.9.0)
Requirement already satisfied: packaging>=20.9 in ./miniconda3/envs/coding/lib/python3.12/site-packages (from huggingface-hub>=0.25.0->hazm) (26.2)
Requirement already satisfied: pyyaml>=5.1 in ./miniconda3/envs/coding/lib/python3.12/site-packages (from huggingface-hub>=0.25.0->hazm) (6.0.3)
Requirement already satisfied: requests in ./miniconda3/envs/coding/lib/python3.12/site-packages (from huggingface-hub>=0.25.0->hazm) (2.34.2)
Requirement already satisfied: typing-extensions>=3.7.4.3 in ./miniconda3/envs/coding/lib/python3.12/site-packages (from huggingface-hub>=0.25.0->hazm) (4.16.0)
Requirement already satisfied: hf-xet<2.0.0,>=1.1.3 in ./miniconda3/envs/coding/lib/python3.12/site-packages (from huggingface-hub>=0.25.0->hazm) (1.2.0)
Requirement already satisfied: charset_normalizer<4,>=2 in ./miniconda3/envs/coding/lib/python3.12/site-packages (from requests->huggingface-hub>=0.25.0->hazm) (3.4.9)
Requirement already satisfied: idna<4,>=2.5 in ./miniconda3/envs/coding/lib/python3.12/site-packages (from requests->huggingface-hub>=0.25.0->hazm) (3.18)
Requirement already satisfied: urllib3<3,>=1.26 in ./miniconda3/envs/coding/lib/python3.12/site-packages (from requests->huggingface-hub>=0.25.0->hazm) (2.7.0)
Requirement already satisfied: certifi>=2023.5.7 in ./miniconda3/envs/coding/lib/python3.12/site-packages (from requests->huggingface-hub>=0.25.0->hazm) (2026.6.17)
Downloading hazm-0.12.1-py3-none-any.whl (887 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 887.2/887.2 kB 21.8 MB/s  0:00:00
Downloading python_crfsuite-0.9.12-cp312-cp312-macosx_11_0_arm64.whl (319 kB)
Downloading tqdm-4.68.4-py3-none-any.whl (676 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 676.6/676.6 kB 23.4 MB/s  0:00:00
Building wheels for collected packages: flashtext
  Building wheel for flashtext (pyproject.toml) ... done
  Created wheel for flashtext: filename=flashtext-2.7-py2.py3-none-any.whl size=9373 sha256=fd60eab483c3cc098617e6d0b606a2bef618947bc3dc59bc83e24ede83d36396
  Stored in directory: /Users/adnanaltimeemy/Library/Caches/pip/wheels/8c/24/da/4d994d7a27cfc73a4e513a669fbeec4a71f871fe245a81977f
Successfully built flashtext
Installing collected packages: flashtext, tqdm, python-crfsuite, hazm
  Attempting uninstall: tqdm
    Found existing installation: tqdm 4.67.1
    Uninstalling tqdm-4.67.1:
      Successfully uninstalled tqdm-4.67.1
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 4/4 [hazm]
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
fastbook 0.0.29 requires ipywidgets<8, but you have ipywidgets 8.1.8 which is incompatible.
Successfully installed flashtext-2.7 hazm-0.12.1 python-crfsuite-0.9.12 tqdm-4.68.4

In [2]:
# Load CSV file

df = pd.read_csv("Semantic_Persian.csv")

# Display first rows
df.head()

   Unnamed: 0                                               text  labels
0        2144  متاسفم که می شنوم حال شما خوب نیستید.آیا اتفاق...       0
1        2145  آیا اتفاق خاصی رخ داده است که باعث ناراحتی شما...       0
2        2146  متاسفم که این را شنیدمآیا یک چیز خاص وجود دارد...       0
3        2147  متشکرم.آیا اتفاق خاصی رخ داده است تا شما را نا...       0
4        2148  آیا اتفاقی افتاده است که این احساس را به وجود ...       0

In [3]:
# Dataset information

df.info()

<class 'pandas.DataFrame'>
RangeIndex: 2144 entries, 0 to 2143
Data columns (total 3 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   Unnamed: 0  2144 non-null   int64
 1   text        2144 non-null   str
 2   labels      2144 non-null   int64
dtypes: int64(2), str(1)
memory usage: 453.6 KB

In [4]:
# Detect object/string columns

text_columns = df.select_dtypes(include=['object']).columns

text_columns

/var/folders/88/w4w1n8l12kd_z42_6mrnndmw0000gn/T/ipykernel_93536/2450318917.py:3: Pandas4Warning: For backward compatibility, 'str' dtypes are included by select_dtypes when 'object' dtype is specified. This behavior is deprecated and will be removed in a future version. Explicitly pass 'str' to `include` to select them, or to `exclude` to remove them and silence this warning.
See https://pandas.pydata.org/docs/user_guide/migration-3-strings.html#string-migration-select-dtypes for details on how to write code that works with pandas 2 and 3.
  text_columns = df.select_dtypes(include=['object']).columns

Index(['text'], dtype='str')

In [5]:
normalizer = Normalizer()

stemmer = Stemmer()

persian_stopwords = set(stopwords_list())


def clean_persian_text(text):
    
    # Normalize Persian characters
    text = normalizer.normalize(text)
    
    # Remove URLs
    text = re.sub(r"http\S+", "", text)
    
    # Remove numbers
    text = re.sub(r"\d+", "", text)
    
    # Remove punctuation
    text = re.sub(r"[^\w\s]", "", text)
    
    # Tokenization
    tokens = word_tokenize(text)
    
    # Remove stopwords
    tokens = [
        word for word in tokens
        if word not in persian_stopwords
    ]
    
    # Stemming
    tokens = [
        stemmer.stem(word)
        for word in tokens
    ]
    
    return " ".join(tokens)

In [7]:
df.head()

   Unnamed: 0                                               text  labels
0        2144  متاسفم که می شنوم حال شما خوب نیستید.آیا اتفاق...       0
1        2145  آیا اتفاق خاصی رخ داده است که باعث ناراحتی شما...       0
2        2146  متاسفم که این را شنیدمآیا یک چیز خاص وجود دارد...       0
3        2147  متشکرم.آیا اتفاق خاصی رخ داده است تا شما را نا...       0
4        2148  آیا اتفاقی افتاده است که این احساس را به وجود ...       0

In [9]:
df.columns

Index(['Unnamed: 0', 'text', 'labels'], dtype='str')

In [11]:
from sklearn.cluster import KMeans
from sklearn.metrics import silhouette_score
import matplotlib.pyplot as plt

In [12]:
df.to_csv(
    "Semantic_Persian_KMeans_results.csv",
    index=False,
    encoding="utf-8-sig"
)

print("Saved successfully!")

Saved successfully!