In [1]:
# Data handling
import pandas as pd
import numpy as np

# NLP
import re
import nltk
from nltk.corpus import stopwords
from nltk.tokenize import word_tokenize

# Machine Learning
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.cluster import KMeans
from sklearn.preprocessing import StandardScaler
from sklearn.decomposition import PCA
from sklearn.metrics import silhouette_score

# Visualisation
import matplotlib.pyplot as plt
import seaborn as sns

import warnings
warnings.filterwarnings('ignore')

In [2]:
nltk.download('punkt')
nltk.download('stopwords')

[nltk_data] Downloading package punkt to
[nltk_data]     /Users/adnanaltimeemy/nltk_data...
[nltk_data]   Package punkt is already up-to-date!
[nltk_data] Downloading package stopwords to
[nltk_data]     /Users/adnanaltimeemy/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!

True

In [3]:
# Load CSV file

df = pd.read_csv("Sentiment_Analysis_Dataset.csv")

# Display first rows

df.head()

                                            sentence sentiment  label
0                     خیلی خوشحالم که تو را می‌بینم.     HAPPY      0
1       وقتی دل خوش است، همه چیز بهتر به نظر می‌رسد.     HAPPY      0
2  از خنده همیشه به عنوان یک هدیه قیمتی استفاده م...     HAPPY      0
3                            خوشحالی و امید بی‌پایان     HAPPY      0
4                   روزهای خوشبختی در انتظارم هستند.     HAPPY      0

In [4]:
# Dataset information

df.info()

<class 'pandas.DataFrame'>
RangeIndex: 6168 entries, 0 to 6167
Data columns (total 3 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   sentence   6168 non-null   str
 1   sentiment  6168 non-null   str
 2   label      6168 non-null   int64
dtypes: int64(1), str(2)
memory usage: 655.0 KB

In [5]:
df.head()

                                            sentence sentiment  label
0                     خیلی خوشحالم که تو را می‌بینم.     HAPPY      0
1       وقتی دل خوش است، همه چیز بهتر به نظر می‌رسد.     HAPPY      0
2  از خنده همیشه به عنوان یک هدیه قیمتی استفاده م...     HAPPY      0
3                            خوشحالی و امید بی‌پایان     HAPPY      0
4                   روزهای خوشبختی در انتظارم هستند.     HAPPY      0

In [6]:
stop_words = set(stopwords.words('english'))

def clean_text(text):
    
    # Lowercase
    text = text.lower()
    
    # Remove URLs
    text = re.sub(r'http\S+', '', text)
    
    # Remove punctuation and numbers
    text = re.sub('[^a-zA-Z]', ' ', text)
    
    # Tokenization
    tokens = word_tokenize(text)
    
    # Remove stopwords
    tokens = [
        word for word in tokens 
        if word not in stop_words and len(word) > 2
    ]
    
    return " ".join(tokens)

In [8]:

df.head()

                                            sentence sentiment  label
0                     خیلی خوشحالم که تو را می‌بینم.     HAPPY      0
1       وقتی دل خوش است، همه چیز بهتر به نظر می‌رسد.     HAPPY      0
2  از خنده همیشه به عنوان یک هدیه قیمتی استفاده م...     HAPPY      0
3                            خوشحالی و امید بی‌پایان     HAPPY      0
4                   روزهای خوشبختی در انتظارم هستند.     HAPPY      0

In [11]:

df.columns

Index(['sentence', 'sentiment', 'label'], dtype='str')

In [12]:
df.to_csv(
    "Sentiment_Analysis_KMeans_Results.csv",
    index=False
)

print("File saved successfully!")

File saved successfully!