In [1]:
import pandas as pd
import numpy as np

from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier

from sklearn.metrics import accuracy_score, classification_report, confusion_matrix

In [2]:
df = pd.read_csv("Shifts.csv")

df.head()

  shift_id day_of_week start_time  end_time
0   sh0001      Monday   10:30:00  14:00:00
1   sh0002      Monday   18:30:00  23:00:00
2   sh0003     Tuesday   10:30:00  14:00:00
3   sh0004     Tuesday   18:30:00  23:00:00
4   sh0005   Wednesday   10:30:00  14:00:00

In [3]:
print(df.shape)
print(df.info())
print(df.describe())
print(df.isnull().sum())

(14, 4)
<class 'pandas.DataFrame'>
RangeIndex: 14 entries, 0 to 13
Data columns (total 4 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   shift_id     14 non-null     str
 1   day_of_week  14 non-null     str
 2   start_time   14 non-null     str
 3   end_time     14 non-null     str
dtypes: str(4)
memory usage: 988.0 bytes
None
       shift_id day_of_week start_time  end_time
count        14          14         14        14
unique       14           7          2         2
top      sh0001      Monday   10:30:00  14:00:00
freq          1           2          7         7
shift_id       0
day_of_week    0
start_time     0
end_time       0
dtype: int64

In [4]:
df = df.dropna()  # or use fillna depending on dataset

In [6]:
df.select_dtypes(include=["object"])

Empty DataFrame
Columns: []
Index: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13]

In [8]:
df.columns = df.columns.str.strip()

In [10]:
df.head

<bound method NDFrame.head of     shift_id  day_of_week  start_time  end_time
0          0            1           0         0
1          1            1           1         1
2          2            5           0         0
3          3            5           1         1
4          4            6           0         0
5          5            6           1         1
6          6            4           0         0
7          7            4           1         1
8          8            0           0         0
9          9            0           1         1
10        10            2           0         0
11        11            2           1         1
12        12            3           0         0
13        13            3           1         1>

In [12]:
print(df.columns)

Index(['shift_id', 'day_of_week', 'start_time', 'end_time'], dtype='str')

In [14]:
print(df.columns)

Index(['shift_id', 'day_of_week', 'start_time', 'end_time'], dtype='str')

In [19]:
 df.columns

Index(['shift_id', 'day_of_week', 'start_time', 'end_time'], dtype='str')

In [22]:
dir()

['DecisionTreeClassifier',
 'In',
 'LabelEncoder',
 'Out',
 'RandomForestClassifier',
 '_',
 '_10',
 '_19',
 '_2',
 '_6',
 '__',
 '___',
 '__builtin__',
 '__builtins__',
 '__doc__',
 '__loader__',
 '__name__',
 '__package__',
 '__session__',
 '__spec__',
 '_dh',
 '_i',
 '_i1',
 '_i10',
 '_i11',
 '_i12',
 '_i13',
 '_i14',
 '_i15',
 '_i16',
 '_i17',
 '_i18',
 '_i19',
 '_i2',
 '_i20',
 '_i21',
 '_i22',
 '_i3',
 '_i4',
 '_i5',
 '_i6',
 '_i7',
 '_i8',
 '_i9',
 '_ih',
 '_ii',
 '_iii',
 '_oh',
 'accuracy_score',
 'classification_report',
 'column',
 'confusion_matrix',
 'df',
 'dt_model',
 'exit',
 'get_ipython',
 'label_encoders',
 'le',
 'np',
 'open',
 'pd',
 'plt',
 'quit',
 'rf_model',
 'train_test_split']

In [25]:
print("y_test" in globals())

False