In [1]:
# If needed (run once)
!pip install pandas numpy scikit-learn matplotlib seaborn nltk

Requirement already satisfied: pandas in ./miniconda3/envs/coding/lib/python3.12/site-packages (3.0.3)
Requirement already satisfied: numpy in ./miniconda3/envs/coding/lib/python3.12/site-packages (2.4.5)
Requirement already satisfied: scikit-learn in ./miniconda3/envs/coding/lib/python3.12/site-packages (1.8.0)
Requirement already satisfied: matplotlib in ./miniconda3/envs/coding/lib/python3.12/site-packages (3.10.9)
Requirement already satisfied: seaborn in ./miniconda3/envs/coding/lib/python3.12/site-packages (0.13.2)
Requirement already satisfied: nltk in ./miniconda3/envs/coding/lib/python3.12/site-packages (3.9.2)
Requirement already satisfied: python-dateutil>=2.8.2 in ./miniconda3/envs/coding/lib/python3.12/site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: scipy>=1.10.0 in ./miniconda3/envs/coding/lib/python3.12/site-packages (from scikit-learn) (1.17.1)
Requirement already satisfied: joblib>=1.3.0 in ./miniconda3/envs/coding/lib/python3.12/site-packages (from scikit-learn) (1.5.3)
Requirement already satisfied: threadpoolctl>=3.2.0 in ./miniconda3/envs/coding/lib/python3.12/site-packages (from scikit-learn) (3.6.0)
Requirement already satisfied: contourpy>=1.0.1 in ./miniconda3/envs/coding/lib/python3.12/site-packages (from matplotlib) (1.3.3)
Requirement already satisfied: cycler>=0.10 in ./miniconda3/envs/coding/lib/python3.12/site-packages (from matplotlib) (0.12.1)
Requirement already satisfied: fonttools>=4.22.0 in ./miniconda3/envs/coding/lib/python3.12/site-packages (from matplotlib) (4.63.0)
Requirement already satisfied: kiwisolver>=1.3.1 in ./miniconda3/envs/coding/lib/python3.12/site-packages (from matplotlib) (1.5.0)
Requirement already satisfied: packaging>=20.0 in ./miniconda3/envs/coding/lib/python3.12/site-packages (from matplotlib) (26.2)
Requirement already satisfied: pillow>=8 in ./miniconda3/envs/coding/lib/python3.12/site-packages (from matplotlib) (12.2.0)
Requirement already satisfied: pyparsing>=3 in ./miniconda3/envs/coding/lib/python3.12/site-packages (from matplotlib) (3.3.2)
Requirement already satisfied: click in ./miniconda3/envs/coding/lib/python3.12/site-packages (from nltk) (8.1.8)
Requirement already satisfied: regex>=2021.8.3 in ./miniconda3/envs/coding/lib/python3.12/site-packages (from nltk) (2025.10.23)
Requirement already satisfied: tqdm in ./miniconda3/envs/coding/lib/python3.12/site-packages (from nltk) (4.67.1)
Requirement already satisfied: six>=1.5 in ./miniconda3/envs/coding/lib/python3.12/site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)

In [2]:
import pandas as pd
import numpy as np

import re
import nltk
nltk.download('stopwords')

from nltk.corpus import stopwords

from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.cluster import KMeans
from sklearn.decomposition import PCA

import matplotlib.pyplot as plt
import seaborn as sns

[nltk_data] Downloading package stopwords to
[nltk_data]     /Users/adnanaltimeemy/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!

In [4]:
df = pd.read_csv(
    "SI_1_training datasets.csv",
    engine='python',
    sep=None,
    on_bad_lines='skip'
)

In [6]:
print(df.columns)

Index(['﻿Classes', 'Genus', 'Species', 'UUID', 'Dataset name',
       'Number events after cleaning', 'Poleno', 'Location', 'Country',
       'Holography only', 'Holography + fluorescence',
       'Holography only + holography + fluorescence', 'Filtered datasets: \n'],
      dtype='str')

In [9]:


print(df.head())

                                                                                                          ﻿Classes  \
download link ssabox.ch/datasets_meteoswiss.tar" Download link - unflitered data NaN NaN NaN NaN NaN NaN       NaN

                                                                                                          Genus  \
download link ssabox.ch/datasets_meteoswiss.tar" Download link - unflitered data NaN NaN NaN NaN NaN NaN    NaN

                                                                                                          Species  \
download link ssabox.ch/datasets_meteoswiss.tar" Download link - unflitered data NaN NaN NaN NaN NaN NaN      NaN

                                                                                                          UUID  \
download link ssabox.ch/datasets_meteoswiss.tar" Download link - unflitered data NaN NaN NaN NaN NaN NaN   NaN

                                                                                                          Dataset name  \
download link ssabox.ch/datasets_meteoswiss.tar" Download link - unflitered data NaN NaN NaN NaN NaN NaN           NaN

                                                                                                          Number events after cleaning  \
download link ssabox.ch/datasets_meteoswiss.tar" Download link - unflitered data NaN NaN NaN NaN NaN NaN                           NaN

                                                                                                          Poleno  \
download link ssabox.ch/datasets_meteoswiss.tar" Download link - unflitered data NaN NaN NaN NaN NaN NaN     NaN

                                                                                                          Location  \
download link ssabox.ch/datasets_meteoswiss.tar" Download link - unflitered data NaN NaN NaN NaN NaN NaN       NaN

                                                                                                          Country  \
download link ssabox.ch/datasets_meteoswiss.tar" Download link - unflitered data NaN NaN NaN NaN NaN NaN      NaN

                                                                                                          Holography only  \
download link ssabox.ch/datasets_meteoswiss.tar" Download link - unflitered data NaN NaN NaN NaN NaN NaN              NaN

                                                                                                          Holography + fluorescence  \
download link ssabox.ch/datasets_meteoswiss.tar" Download link - unflitered data NaN NaN NaN NaN NaN NaN                        NaN

                                                                                                          Holography only + holography + fluorescence  \
download link ssabox.ch/datasets_meteoswiss.tar" Download link - unflitered data NaN NaN NaN NaN NaN NaN                                          NaN

                                                                                                          Filtered datasets: \n
download link ssabox.ch/datasets_meteoswiss.tar" Download link - unflitered data NaN NaN NaN NaN NaN NaN                    NaN

In [10]:

print(df.columns.tolist())

['\ufeffClasses', 'Genus', 'Species', 'UUID', 'Dataset name', 'Number events after cleaning', 'Poleno', 'Location', 'Country', 'Holography only', 'Holography + fluorescence', 'Holography only + holography + fluorescence', 'Filtered datasets: \n']

In [12]:
if "clean_text" in df.columns:
    print("Column exists")
else:
    print("Column missing")

Column missing

In [15]:
print(inertia)

[]

In [17]:


df.head()

,,,,,,,,﻿Classes,Genus,Species,UUID,Dataset name,Number events after cleaning,Poleno,Location,Country,Holography only,Holography + fluorescence,Holography only + holography + fluorescence,Filtered datasets: \n
"download link ssabox.ch/datasets_meteoswiss.tar""",Download link - unflitered data,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [21]:
df.head()

,,,,,,,,﻿Classes,Genus,Species,UUID,Dataset name,Number events after cleaning,Poleno,Location,Country,Holography only,Holography + fluorescence,Holography only + holography + fluorescence,Filtered datasets: \n
"download link ssabox.ch/datasets_meteoswiss.tar""",Download link - unflitered data,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [22]:
df.to_csv("clustered_output.csv", index=False)
print("Saved successfully!")

Saved successfully!