In [1]:
# Data handling
import pandas as pd
import numpy as np

# NLP
import re
import nltk
from nltk.corpus import stopwords
from sklearn.feature_extraction.text import TfidfVectorizer

# Machine learning
from sklearn.cluster import KMeans
from sklearn.metrics import silhouette_score

# Visualization
import matplotlib.pyplot as plt
from sklearn.decomposition import PCA

# Download stopwords
nltk.download('stopwords')

[nltk_data] Downloading package stopwords to
[nltk_data]     /Users/adnanaltimeemy/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!

True

In [2]:
# Load CSV file
df = pd.read_csv("snsdata.csv")

# Display first rows
df.head()

,gradyear,gender,age,friends,basketball,football,soccer,softball,volleyball,swimming,...,blonde,mall,shopping,clothes,hollister,abercrombie,die,death,drunk,drugs
0,2006,M,18.982,7,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1,2006,F,18.801,0,0,1,0,0,0,0,...,0,1,0,0,0,0,0,0,0,0
2,2006,M,18.335,69,0,1,0,0,0,0,...,0,0,0,0,0,0,0,1,0,0
3,2006,F,18.875,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4,2006,NaN,18.995,10,0,0,0,0,0,0,...,0,0,2,0,0,0,0,0,1,1

In [3]:
df.info()

# Check missing values
df.isnull().sum()

<class 'pandas.DataFrame'>
RangeIndex: 30000 entries, 0 to 29999
Data columns (total 40 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   gradyear      30000 non-null  int64
 1   gender        27276 non-null  str
 2   age           24914 non-null  float64
 3   friends       30000 non-null  int64
 4   basketball    30000 non-null  int64
 5   football      30000 non-null  int64
 6   soccer        30000 non-null  int64
 7   softball      30000 non-null  int64
 8   volleyball    30000 non-null  int64
 9   swimming      30000 non-null  int64
 10  cheerleading  30000 non-null  int64
 11  baseball      30000 non-null  int64
 12  tennis        30000 non-null  int64
 13  sports        30000 non-null  int64
 14  cute          30000 non-null  int64
 15  sex           30000 non-null  int64
 16  sexy          30000 non-null  int64
 17  hot           30000 non-null  int64
 18  kissed        30000 non-null  int64
 19  dance         30000 non-null  int64
 20  band          30000 non-null  int64
 21  marching      30000 non-null  int64
 22  music         30000 non-null  int64
 23  rock          30000 non-null  int64
 24  god           30000 non-null  int64
 25  church        30000 non-null  int64
 26  jesus         30000 non-null  int64
 27  bible         30000 non-null  int64
 28  hair          30000 non-null  int64
 29  dress         30000 non-null  int64
 30  blonde        30000 non-null  int64
 31  mall          30000 non-null  int64
 32  shopping      30000 non-null  int64
 33  clothes       30000 non-null  int64
 34  hollister     30000 non-null  int64
 35  abercrombie   30000 non-null  int64
 36  die           30000 non-null  int64
 37  death         30000 non-null  int64
 38  drunk         30000 non-null  int64
 39  drugs         30000 non-null  int64
dtypes: float64(1), int64(38), str(1)
memory usage: 9.2 MB

gradyear           0
gender          2724
age             5086
friends            0
basketball         0
football           0
soccer             0
softball           0
volleyball         0
swimming           0
cheerleading       0
baseball           0
tennis             0
sports             0
cute               0
sex                0
sexy               0
hot                0
kissed             0
dance              0
band               0
marching           0
music              0
rock               0
god                0
church             0
jesus              0
bible              0
hair               0
dress              0
blonde             0
mall               0
shopping           0
clothes            0
hollister          0
abercrombie        0
die                0
death              0
drunk              0
drugs              0
dtype: int64

In [4]:
df.columns

Index(['gradyear', 'gender', 'age', 'friends', 'basketball', 'football',
       'soccer', 'softball', 'volleyball', 'swimming', 'cheerleading',
       'baseball', 'tennis', 'sports', 'cute', 'sex', 'sexy', 'hot', 'kissed',
       'dance', 'band', 'marching', 'music', 'rock', 'god', 'church', 'jesus',
       'bible', 'hair', 'dress', 'blonde', 'mall', 'shopping', 'clothes',
       'hollister', 'abercrombie', 'die', 'death', 'drunk', 'drugs'],
      dtype='str')

In [6]:
df.head()

,gradyear,gender,age,friends,basketball,football,soccer,softball,volleyball,swimming,...,blonde,mall,shopping,clothes,hollister,abercrombie,die,death,drunk,drugs
0,2006,M,18.982,7,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1,2006,F,18.801,0,0,1,0,0,0,0,...,0,1,0,0,0,0,0,0,0,0
2,2006,M,18.335,69,0,1,0,0,0,0,...,0,0,0,0,0,0,0,1,0,0
3,2006,F,18.875,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4,2006,NaN,18.995,10,0,0,0,0,0,0,...,0,0,2,0,0,0,0,0,1,1

In [7]:
df.to_csv(
    "snsdata_clustered.csv",
    index=False
)

print("File saved successfully")

File saved successfully