In [1]:
import pandas as pd
import numpy as np

from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier

from sklearn.metrics import accuracy_score, classification_report, confusion_matrix

In [2]:
df = pd.read_csv("topic_songs.csv")

df.head()

  Artist Song                                             Lyrics
0      A   A1  I found myself dreaming\nIn silver and gold\nL...
1      B   B1  This was all you, none of it me\nYou put your ...
2      C   C1  Love of mine, someday you will die\nBut I'll b...

In [3]:
print(df.shape)
print(df.info())
print(df.isnull().sum())

(3, 3)
<class 'pandas.DataFrame'>
RangeIndex: 3 entries, 0 to 2
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Artist  3 non-null      str
 1   Song    3 non-null      str
 2   Lyrics  3 non-null      str
dtypes: str(3)
memory usage: 4.3 KB
None
Artist    0
Song      0
Lyrics    0
dtype: int64

In [4]:
df = df.dropna()   # or use imputation if needed

In [9]:
df.head()

  Artist Song                                             Lyrics
0      A   A1  I found myself dreaming\nIn silver and gold\nL...
1      B   B1  This was all you, none of it me\nYou put your ...
2      C   C1  Love of mine, someday you will die\nBut I'll b...

In [11]:
x = df.iloc[:, :-1]

In [13]:
print(globals().keys())

dict_keys(['__name__', '__doc__', '__package__', '__loader__', '__spec__', '__builtin__', '__builtins__', '_ih', '_oh', '_dh', 'In', 'Out', 'get_ipython', 'exit', 'quit', 'open', '_', '__', '___', '__session__', '_i', '_ii', '_iii', '_i1', 'pd', 'np', 'train_test_split', 'LabelEncoder', 'DecisionTreeClassifier', 'RandomForestClassifier', 'accuracy_score', 'classification_report', 'confusion_matrix', '_i2', 'df', '_2', '_i3', '_i4', '_i5', 'target_column', 'le', '_i6', '_i7', '_i8', '_i9', '_9', '_i10', '_i11', 'x', '_i12', 'dt_model', '_i13'])

In [15]:
df.head()

  Artist Song                                             Lyrics
0      A   A1  I found myself dreaming\nIn silver and gold\nL...
1      B   B1  This was all you, none of it me\nYou put your ...
2      C   C1  Love of mine, someday you will die\nBut I'll b...