In [1]:
# Data handling
import pandas as pd
import numpy as np

# Visualization
import matplotlib.pyplot as plt
import seaborn as sns

# Preprocessing
from sklearn.preprocessing import LabelEncoder, StandardScaler

# NLP tools
from sklearn.feature_extraction.text import TfidfVectorizer

# K-means clustering
from sklearn.cluster import KMeans
from sklearn.metrics import silhouette_score

# Dimension reduction for visualization
from sklearn.decomposition import PCA

In [2]:
# Load dataset
df = pd.read_csv("Soybean.csv")

# Display first rows
df.head()

,Class,date,plant.stand,precip,temp,hail,crop.hist,area.dam,sever,seed.tmt,...,int.discolor,sclerotia,fruit.pods,fruit.spots,seed,mold.growth,seed.discolor,seed.size,shriveling,roots
0,diaporthe-stem-canker,6.0,0.0,2.0,1.0,0.0,1.0,1.0,1.0,0.0,...,0.0,0.0,0.0,4.0,0.0,0.0,0.0,0.0,0.0,0.0
1,diaporthe-stem-canker,4.0,0.0,2.0,1.0,0.0,2.0,0.0,2.0,1.0,...,0.0,0.0,0.0,4.0,0.0,0.0,0.0,0.0,0.0,0.0
2,diaporthe-stem-canker,3.0,0.0,2.0,1.0,0.0,1.0,0.0,2.0,1.0,...,0.0,0.0,0.0,4.0,0.0,0.0,0.0,0.0,0.0,0.0
3,diaporthe-stem-canker,3.0,0.0,2.0,1.0,0.0,1.0,0.0,2.0,0.0,...,0.0,0.0,0.0,4.0,0.0,0.0,0.0,0.0,0.0,0.0
4,diaporthe-stem-canker,6.0,0.0,2.0,1.0,0.0,2.0,0.0,1.0,0.0,...,0.0,0.0,0.0,4.0,0.0,0.0,0.0,0.0,0.0,0.0

In [3]:
# Dataset shape
print(df.shape)

# Column information
df.info()

# Missing values
df.isnull().sum()

(683, 36)
<class 'pandas.DataFrame'>
RangeIndex: 683 entries, 0 to 682
Data columns (total 36 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   Class            683 non-null    str
 1   date             682 non-null    float64
 2   plant.stand      647 non-null    float64
 3   precip           645 non-null    float64
 4   temp             653 non-null    float64
 5   hail             562 non-null    float64
 6   crop.hist        667 non-null    float64
 7   area.dam         682 non-null    float64
 8   sever            562 non-null    float64
 9   seed.tmt         562 non-null    float64
 10  germ             571 non-null    float64
 11  plant.growth     667 non-null    float64
 12  leaves           683 non-null    int64
 13  leaf.halo        599 non-null    float64
 14  leaf.marg        599 non-null    float64
 15  leaf.size        599 non-null    float64
 16  leaf.shread      583 non-null    float64
 17  leaf.malf        599 non-null    float64
 18  leaf.mild        575 non-null    float64
 19  stem             667 non-null    float64
 20  lodging          562 non-null    float64
 21  stem.cankers     645 non-null    float64
 22  canker.lesion    645 non-null    float64
 23  fruiting.bodies  577 non-null    float64
 24  ext.decay        645 non-null    float64
 25  mycelium         645 non-null    float64
 26  int.discolor     645 non-null    float64
 27  sclerotia        645 non-null    float64
 28  fruit.pods       599 non-null    float64
 29  fruit.spots      577 non-null    float64
 30  seed             591 non-null    float64
 31  mold.growth      591 non-null    float64
 32  seed.discolor    577 non-null    float64
 33  seed.size        591 non-null    float64
 34  shriveling       577 non-null    float64
 35  roots            652 non-null    float64
dtypes: float64(34), int64(1), str(1)
memory usage: 202.7 KB

Class                0
date                 1
plant.stand         36
precip              38
temp                30
hail               121
crop.hist           16
area.dam             1
sever              121
seed.tmt           121
germ               112
plant.growth        16
leaves               0
leaf.halo           84
leaf.marg           84
leaf.size           84
leaf.shread        100
leaf.malf           84
leaf.mild          108
stem                16
lodging            121
stem.cankers        38
canker.lesion       38
fruiting.bodies    106
ext.decay           38
mycelium            38
int.discolor        38
sclerotia           38
fruit.pods          84
fruit.spots        106
seed                92
mold.growth         92
seed.discolor      106
seed.size           92
shriveling         106
roots               31
dtype: int64

In [5]:
df.head()

,Class,date,plant.stand,precip,temp,hail,crop.hist,area.dam,sever,seed.tmt,...,int.discolor,sclerotia,fruit.pods,fruit.spots,seed,mold.growth,seed.discolor,seed.size,shriveling,roots
0,diaporthe-stem-canker,6.0,0.0,2.0,1.0,0.0,1.0,1.0,1.0,0.0,...,0.0,0.0,0.0,4.0,0.0,0.0,0.0,0.0,0.0,0.0
1,diaporthe-stem-canker,4.0,0.0,2.0,1.0,0.0,2.0,0.0,2.0,1.0,...,0.0,0.0,0.0,4.0,0.0,0.0,0.0,0.0,0.0,0.0
2,diaporthe-stem-canker,3.0,0.0,2.0,1.0,0.0,1.0,0.0,2.0,1.0,...,0.0,0.0,0.0,4.0,0.0,0.0,0.0,0.0,0.0,0.0
3,diaporthe-stem-canker,3.0,0.0,2.0,1.0,0.0,1.0,0.0,2.0,0.0,...,0.0,0.0,0.0,4.0,0.0,0.0,0.0,0.0,0.0,0.0
4,diaporthe-stem-canker,6.0,0.0,2.0,1.0,0.0,2.0,0.0,1.0,0.0,...,0.0,0.0,0.0,4.0,0.0,0.0,0.0,0.0,0.0,0.0

In [6]:
df.head()

,Class,date,plant.stand,precip,temp,hail,crop.hist,area.dam,sever,seed.tmt,...,int.discolor,sclerotia,fruit.pods,fruit.spots,seed,mold.growth,seed.discolor,seed.size,shriveling,roots
0,diaporthe-stem-canker,6.0,0.0,2.0,1.0,0.0,1.0,1.0,1.0,0.0,...,0.0,0.0,0.0,4.0,0.0,0.0,0.0,0.0,0.0,0.0
1,diaporthe-stem-canker,4.0,0.0,2.0,1.0,0.0,2.0,0.0,2.0,1.0,...,0.0,0.0,0.0,4.0,0.0,0.0,0.0,0.0,0.0,0.0
2,diaporthe-stem-canker,3.0,0.0,2.0,1.0,0.0,1.0,0.0,2.0,1.0,...,0.0,0.0,0.0,4.0,0.0,0.0,0.0,0.0,0.0,0.0
3,diaporthe-stem-canker,3.0,0.0,2.0,1.0,0.0,1.0,0.0,2.0,0.0,...,0.0,0.0,0.0,4.0,0.0,0.0,0.0,0.0,0.0,0.0
4,diaporthe-stem-canker,6.0,0.0,2.0,1.0,0.0,2.0,0.0,1.0,0.0,...,0.0,0.0,0.0,4.0,0.0,0.0,0.0,0.0,0.0,0.0

In [11]:
print(df.columns.tolist())

['Class', 'date', 'plant.stand', 'precip', 'temp', 'hail', 'crop.hist', 'area.dam', 'sever', 'seed.tmt', 'germ', 'plant.growth', 'leaves', 'leaf.halo', 'leaf.marg', 'leaf.size', 'leaf.shread', 'leaf.malf', 'leaf.mild', 'stem', 'lodging', 'stem.cankers', 'canker.lesion', 'fruiting.bodies', 'ext.decay', 'mycelium', 'int.discolor', 'sclerotia', 'fruit.pods', 'fruit.spots', 'seed', 'mold.growth', 'seed.discolor', 'seed.size', 'shriveling', 'roots']

In [12]:
df.to_csv(
    "Soybean_KMeans_Result.csv",
    index=False
)

print("File saved successfully!")

File saved successfully!