In [1]:
# Data handling
import pandas as pd
import numpy as np

# NLP
import nltk
import re
from nltk.corpus import stopwords
from nltk.stem import WordNetLemmatizer

# Machine Learning
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.cluster import KMeans
from sklearn.decomposition import PCA

# Visualization
import matplotlib.pyplot as plt

# Download NLP resources
nltk.download('stopwords')
nltk.download('wordnet')

[nltk_data] Downloading package stopwords to
[nltk_data]     /Users/adnanaltimeemy/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!
[nltk_data] Downloading package wordnet to
[nltk_data]     /Users/adnanaltimeemy/nltk_data...
[nltk_data]   Package wordnet is already up-to-date!

True

In [6]:
df = pd.read_csv(
    "Sheet6.csv",
    engine="python",
    on_bad_lines="skip"
)

In [8]:
df.head()

                         import pandas as pd
0                            # Read CSV file
1             df = pd.read_csv("Sheet6.csv")
2      # Write all CSV data into a text file
3      file.write(df.to_string(index=False))
4      print("Sheet6.txt has been created.")

In [10]:


df.head()

                         import pandas as pd
0                            # Read CSV file
1             df = pd.read_csv("Sheet6.csv")
2      # Write all CSV data into a text file
3      file.write(df.to_string(index=False))
4      print("Sheet6.txt has been created.")

In [12]:
df.columns
df.head()

                         import pandas as pd
0                            # Read CSV file
1             df = pd.read_csv("Sheet6.csv")
2      # Write all CSV data into a text file
3      file.write(df.to_string(index=False))
4      print("Sheet6.txt has been created.")

In [13]:
df.head()

                         import pandas as pd
0                            # Read CSV file
1             df = pd.read_csv("Sheet6.csv")
2      # Write all CSV data into a text file
3      file.write(df.to_string(index=False))
4      print("Sheet6.txt has been created.")

In [15]:
print(df.shape)
print(df.columns.tolist())
print(df.head())

(5, 1)
['import pandas as pd']
                         import pandas as pd
0                            # Read CSV file
1             df = pd.read_csv("Sheet6.csv")
2      # Write all CSV data into a text file
3      file.write(df.to_string(index=False))
4      print("Sheet6.txt has been created.")

In [16]:
df.to_csv(
    "StarWars_KMeans_results.csv",
    index=False
)