In [1]:
import pandas as pd
import numpy as np

from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder, StandardScaler
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier

from sklearn.metrics import accuracy_score, classification_report, confusion_matrix

In [2]:
df = pd.read_csv("Starbucks satisfactory survey encode cleaned.csv")

df.head()

   Id  gender  age  ...  promoMethodBillboard  promoMethodOthers  loyal
0   1       1    1  ...                     1                  1      0
1   2       1    1  ...                     1                  1      0
2   3       0    1  ...                     1                  1      0
3   4       1    1  ...                     1                  1      1
4   5       0    1  ...                     1                  1      0

[5 rows x 33 columns]

In [3]:
# Check structure
print(df.info())
print(df.isnull().sum())

# Drop duplicates if any
df = df.drop_duplicates()

# Fill missing values (simple strategy)
df = df.fillna(df.median(numeric_only=True))
df = df.fillna("Unknown")

<class 'pandas.DataFrame'>
RangeIndex: 113 entries, 0 to 112
Data columns (total 33 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   Id                      113 non-null    int64
 1   gender                  113 non-null    int64
 2   age                     113 non-null    int64
 3   status                  113 non-null    int64
 4   income                  113 non-null    int64
 5   visitNo                 113 non-null    int64
 6   method                  113 non-null    int64
 7   timeSpend               113 non-null    int64
 8   location                113 non-null    int64
 9   membershipCard          113 non-null    int64
 10  itemPurchaseCoffee      113 non-null    int64
 11  itempurchaseCold        113 non-null    int64
 12  itemPurchasePastries    113 non-null    int64
 13  itemPurchaseJuices      113 non-null    int64
 14  itemPurchaseSandwiches  113 non-null    int64
 15  itemPurchaseOthers      113 non-null    int64
 16  spendPurchase           113 non-null    int64
 17  productRate             113 non-null    int64
 18  priceRate               113 non-null    int64
 19  promoRate               113 non-null    int64
 20  ambianceRate            113 non-null    int64
 21  wifiRate                113 non-null    int64
 22  serviceRate             113 non-null    int64
 23  chooseRate              113 non-null    int64
 24  promoMethodApp          113 non-null    int64
 25  promoMethodSoc          113 non-null    int64
 26  promoMethodEmail        113 non-null    int64
 27  promoMethodDeal         113 non-null    int64
 28  promoMethodFriend       113 non-null    int64
 29  promoMethodDisplay      113 non-null    int64
 30  promoMethodBillboard    113 non-null    int64
 31  promoMethodOthers       113 non-null    int64
 32  loyal                   113 non-null    int64
dtypes: int64(33)
memory usage: 29.3 KB
None
Id                        0
gender                    0
age                       0
status                    0
income                    0
visitNo                   0
method                    0
timeSpend                 0
location                  0
membershipCard            0
itemPurchaseCoffee        0
itempurchaseCold          0
itemPurchasePastries      0
itemPurchaseJuices        0
itemPurchaseSandwiches    0
itemPurchaseOthers        0
spendPurchase             0
productRate               0
priceRate                 0
promoRate                 0
ambianceRate              0
wifiRate                  0
serviceRate               0
chooseRate                0
promoMethodApp            0
promoMethodSoc            0
promoMethodEmail          0
promoMethodDeal           0
promoMethodFriend         0
promoMethodDisplay        0
promoMethodBillboard      0
promoMethodOthers         0
loyal                     0
dtype: int64

In [5]:
df.head()

   Id  gender  age  ...  promoMethodBillboard  promoMethodOthers  loyal
0   1       1    1  ...                     1                  1      0
1   2       1    1  ...                     1                  1      0
2   3       0    1  ...                     1                  1      0
3   4       1    1  ...                     1                  1      1
4   5       0    1  ...                     1                  1      0

[5 rows x 33 columns]

In [8]:
print(df.columns.tolist())

['Id', 'gender', 'age', 'status', 'income', 'visitNo', 'method', 'timeSpend', 'location', 'membershipCard', 'itemPurchaseCoffee', 'itempurchaseCold', 'itemPurchasePastries', 'itemPurchaseJuices', 'itemPurchaseSandwiches', 'itemPurchaseOthers', 'spendPurchase', 'productRate', 'priceRate', 'promoRate', 'ambianceRate', 'wifiRate', 'serviceRate', 'chooseRate', 'promoMethodApp', 'promoMethodSoc', 'promoMethodEmail', 'promoMethodDeal', 'promoMethodFriend', 'promoMethodDisplay', 'promoMethodBillboard', 'promoMethodOthers', 'loyal']

In [10]:
print(df.columns.tolist())

['Id', 'gender', 'age', 'status', 'income', 'visitNo', 'method', 'timeSpend', 'location', 'membershipCard', 'itemPurchaseCoffee', 'itempurchaseCold', 'itemPurchasePastries', 'itemPurchaseJuices', 'itemPurchaseSandwiches', 'itemPurchaseOthers', 'spendPurchase', 'productRate', 'priceRate', 'promoRate', 'ambianceRate', 'wifiRate', 'serviceRate', 'chooseRate', 'promoMethodApp', 'promoMethodSoc', 'promoMethodEmail', 'promoMethodDeal', 'promoMethodFriend', 'promoMethodDisplay', 'promoMethodBillboard', 'promoMethodOthers', 'loyal']

In [12]:
print("rf_model" in globals())
print("X_train" in globals())

False
False