In [1]:
import pandas as pd
import numpy as np

import re
import string

from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.cluster import KMeans
from sklearn.decomposition import PCA

import matplotlib.pyplot as plt

In [2]:
df = pd.read_csv("stb47.csv")

df.head()

,og:type,og:title,og:description,og:image,og:url
0,article,[新商品情報] 北海道 とうきび クリーミー フラペチーノ®｜スターバックス コーヒー ジャ...,北海道のパートナーが『なまらLOVE HOKKAIDO』をテーマに、「スターバックスと北海...,https://www.starbucks.co.jp/static/cafe/jimoto...,https://www.starbucks.co.jp/cafe/jimoto_frappu...
1,article,[新商品情報] 青森 じゃわめく りんご ストロベリー フラペチーノ®｜スターバックス コー...,青森のテーマは「躍動の青森 騒めく（じゃわめぐ）瞬間を！」。りんごシロップとミルクで、雪景色...,https://www.starbucks.co.jp/static/cafe/jimoto...,https://www.starbucks.co.jp/cafe/jimoto_frappu...
2,article,[新商品情報] 岩手 めんこい 抹茶 ＆ ゴマ フラペチーノ®｜スターバックス コーヒー ジ...,岩手県は「ALL IWATE de めんこいつながり じっくりと、これからも。」をテーマ。シ...,https://www.starbucks.co.jp/static/cafe/jimoto...,https://www.starbucks.co.jp/cafe/jimoto_frappu...
3,article,[新商品情報] 宮城 だっちゃ ずんだ抹茶 フラペチーノ®｜スターバックス コーヒー ジャパ...,『いぎなり感謝してるっちゃ！ ～みんなで杜をはぐくもう～』をテーマに、これまでの感謝の気持ち...,https://www.starbucks.co.jp/static/cafe/jimoto...,https://www.starbucks.co.jp/cafe/jimoto_frappu...
4,article,[新商品情報] 秋田 あまじょっぺ 塩キャラメル フラペチーノ®｜スターバックス コーヒー ...,秋田県は『やっぱすげな～!!おらほのあきた ＃秋田はおらほのタカラモノ』 をテーマに、パート...,https://www.starbucks.co.jp/static/cafe/jimoto...,https://www.starbucks.co.jp/cafe/jimoto_frappu...

In [3]:
print(df.info())
print(df.isnull().sum())

<class 'pandas.DataFrame'>
RangeIndex: 47 entries, 0 to 46
Data columns (total 5 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   og:type         47 non-null     str
 1   og:title        47 non-null     str
 2   og:description  47 non-null     str
 3   og:image        47 non-null     str
 4   og:url          47 non-null     str
dtypes: str(5)
memory usage: 53.9 KB
None
og:type           0
og:title          0
og:description    0
og:image          0
og:url            0
dtype: int64

In [6]:
print(df.columns.tolist())

['og:type', 'og:title', 'og:description', 'og:image', 'og:url']

In [8]:
print(df.columns.tolist())

['og:type', 'og:title', 'og:description', 'og:image', 'og:url']

In [10]:
print(df.columns.tolist())
print(df.head())

['og:type', 'og:title', 'og:description', 'og:image', 'og:url']
   og:type                                           og:title  \
0  article  [新商品情報] 北海道 とうきび クリーミー フラペチーノ®｜スターバックス コーヒー ジャ...
1  article  [新商品情報] 青森 じゃわめく りんご ストロベリー フラペチーノ®｜スターバックス コー...
2  article  [新商品情報] 岩手 めんこい 抹茶 ＆ ゴマ フラペチーノ®｜スターバックス コーヒー ジ...
3  article  [新商品情報] 宮城 だっちゃ ずんだ抹茶 フラペチーノ®｜スターバックス コーヒー ジャパ...
4  article  [新商品情報] 秋田 あまじょっぺ 塩キャラメル フラペチーノ®｜スターバックス コーヒー ...

                                      og:description  \
0  北海道のパートナーが『なまらLOVE  HOKKAIDO』をテーマに、「スターバックスと北海...
1  青森のテーマは「躍動の青森　騒めく（じゃわめぐ）瞬間を！」。りんごシロップとミルクで、雪景色...
2  岩手県は「ALL IWATE de めんこいつながり　じっくりと、これからも。」をテーマ。シ...
3  『いぎなり感謝してるっちゃ！ ～みんなで杜をはぐくもう～』をテーマに、これまでの感謝の気持ち...
4  秋田県は『やっぱすげな～!!おらほのあきた ＃秋田はおらほのタカラモノ』　をテーマに、パート...

                                            og:image  \
0  https://www.starbucks.co.jp/static/cafe/jimoto...
1  https://www.starbucks.co.jp/static/cafe/jimoto...
2  https://www.starbucks.co.jp/static/cafe/jimoto...
3  https://www.starbucks.co.jp/static/cafe/jimoto...
4  https://www.starbucks.co.jp/static/cafe/jimoto...

                                              og:url
0  https://www.starbucks.co.jp/cafe/jimoto_frappu...
1  https://www.starbucks.co.jp/cafe/jimoto_frappu...
2  https://www.starbucks.co.jp/cafe/jimoto_frappu...
3  https://www.starbucks.co.jp/cafe/jimoto_frappu...
4  https://www.starbucks.co.jp/cafe/jimoto_frappu...

In [11]:
df.head()

,og:type,og:title,og:description,og:image,og:url
0,article,[新商品情報] 北海道 とうきび クリーミー フラペチーノ®｜スターバックス コーヒー ジャ...,北海道のパートナーが『なまらLOVE HOKKAIDO』をテーマに、「スターバックスと北海...,https://www.starbucks.co.jp/static/cafe/jimoto...,https://www.starbucks.co.jp/cafe/jimoto_frappu...
1,article,[新商品情報] 青森 じゃわめく りんご ストロベリー フラペチーノ®｜スターバックス コー...,青森のテーマは「躍動の青森 騒めく（じゃわめぐ）瞬間を！」。りんごシロップとミルクで、雪景色...,https://www.starbucks.co.jp/static/cafe/jimoto...,https://www.starbucks.co.jp/cafe/jimoto_frappu...
2,article,[新商品情報] 岩手 めんこい 抹茶 ＆ ゴマ フラペチーノ®｜スターバックス コーヒー ジ...,岩手県は「ALL IWATE de めんこいつながり じっくりと、これからも。」をテーマ。シ...,https://www.starbucks.co.jp/static/cafe/jimoto...,https://www.starbucks.co.jp/cafe/jimoto_frappu...
3,article,[新商品情報] 宮城 だっちゃ ずんだ抹茶 フラペチーノ®｜スターバックス コーヒー ジャパ...,『いぎなり感謝してるっちゃ！ ～みんなで杜をはぐくもう～』をテーマに、これまでの感謝の気持ち...,https://www.starbucks.co.jp/static/cafe/jimoto...,https://www.starbucks.co.jp/cafe/jimoto_frappu...
4,article,[新商品情報] 秋田 あまじょっぺ 塩キャラメル フラペチーノ®｜スターバックス コーヒー ...,秋田県は『やっぱすげな～!!おらほのあきた ＃秋田はおらほのタカラモノ』 をテーマに、パート...,https://www.starbucks.co.jp/static/cafe/jimoto...,https://www.starbucks.co.jp/cafe/jimoto_frappu...