In [1]:
import pandas as pd
import numpy as np

from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier

from sklearn.metrics import accuracy_score, classification_report, confusion_matrix
import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
df = pd.read_csv("street-tree-data-TO.csv")
df.head()

,_id,OBJECTID,STRUCTID,ADDRESS,STREETNAME,CROSSSTREET1,CROSSSTREET2,SUFFIX,UNIT_NUMBER,TREE_POSITION_NUMBER,SITE,WARD,BOTANICAL_NAME,COMMON_NAME,DBH_TRUNK,geometry
0,1,1,TO105087,145,ST GEORGE ST TORONTO,PRINCE ARTHUR AVE,LOWTHER AVE,NaN,0,30.0,NaN,11.0,Gleditsia triacanthos,Honey locust,19.0,"{""type"": ""Point"", ""coordinates"": [-79.40031615..."
1,34,35,TO18965,330,CLINTON ST,NANCY POCOCK PL,CLINTON PL,NaN,0,10.0,NaN,11.0,Acer platanoides,"Maple, Norway",72.0,"{""type"": ""Point"", ""coordinates"": [-79.41687449..."
2,37,38,TO16750,161,CHAPLIN CRES,AVENUE RD,BRAEMAR AVE,NaN,0,10.0,NaN,12.0,Betula papyrifera,"Birch, white",45.0,"{""type"": ""Point"", ""coordinates"": [-79.40731236..."
3,48,49,TO37844,1669,GERRARD ST E,GAINSBOROUGH RD,WEMBLEY DR,NaN,0,10.0,NaN,19.0,Tilia,Linden,61.0,"{""type"": ""Point"", ""coordinates"": [-79.31830349..."
4,64,65,TO16574,9,CHANNEL AVE,NaN,NaN,NaN,0,10.0,NaN,10.0,Fraxinus,Ash,44.0,"{""type"": ""Point"", ""coordinates"": [-79.35499777..."

In [3]:
print(df.shape)
print(df.info())
print(df.describe(include='all'))

(51156, 16)
<class 'pandas.DataFrame'>
RangeIndex: 51156 entries, 0 to 51155
Data columns (total 16 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   _id                   51156 non-null  int64
 1   OBJECTID              51156 non-null  int64
 2   STRUCTID              51156 non-null  str
 3   ADDRESS               51156 non-null  int64
 4   STREETNAME            51155 non-null  str
 5   CROSSSTREET1          49582 non-null  str
 6   CROSSSTREET2          48656 non-null  str
 7   SUFFIX                407 non-null    str
 8   UNIT_NUMBER           51156 non-null  int64
 9   TREE_POSITION_NUMBER  51152 non-null  float64
 10  SITE                  2113 non-null   str
 11  WARD                  51155 non-null  float64
 12  BOTANICAL_NAME        51156 non-null  str
 13  COMMON_NAME           51156 non-null  str
 14  DBH_TRUNK             51155 non-null  float64
 15  geometry              51156 non-null  str
dtypes: float64(3), int64(4), str(9)
memory usage: 13.6 MB
None
                  _id       OBJECTID  STRUCTID       ADDRESS  \
count    51156.000000   51156.000000     51156  51156.000000
unique            NaN            NaN     51156           NaN
top               NaN            NaN  TO105087           NaN
freq              NaN            NaN         1           NaN
mean    345067.769020  345115.067069       NaN    219.719661
std     199436.461783  199462.820511       NaN    344.168132
min          1.000000       1.000000       NaN      1.000000
25%     171207.750000  171230.750000       NaN     40.000000
50%     344849.000000  344894.000000       NaN    100.000000
75%     519158.750000  519229.750000       NaN    254.000000
max     689359.000000  689450.000000       NaN   3444.000000

                STREETNAME       CROSSSTREET1       CROSSSTREET2 SUFFIX  \
count                51155              49582              48656    407
unique                1584               2953               2837      5
top     OLD FOREST HILL RD  MOUNT PLEASANT RD  MOUNT PLEASANT RD      A
freq                   352                728                643    312
mean                   NaN                NaN                NaN    NaN
std                    NaN                NaN                NaN    NaN
min                    NaN                NaN                NaN    NaN
25%                    NaN                NaN                NaN    NaN
50%                    NaN                NaN                NaN    NaN
75%                    NaN                NaN                NaN    NaN
max                    NaN                NaN                NaN    NaN

        UNIT_NUMBER  TREE_POSITION_NUMBER       SITE          WARD  \
count       51156.0          51152.000000       2113  51155.000000
unique          NaN                   NaN        215           NaN
top             NaN                   NaN  MOSS PARK           NaN
freq            NaN                   NaN        120           NaN
mean            0.0            833.759071        NaN     11.156544
std             0.0           8779.562394        NaN      4.208132
min             0.0              1.000000        NaN      4.000000
25%             0.0             10.000000        NaN      9.000000
50%             0.0             10.000000        NaN     11.000000
75%             0.0             30.000000        NaN     14.000000
max             0.0          99999.000000        NaN     24.000000

          BOTANICAL_NAME    COMMON_NAME     DBH_TRUNK  \
count              51156          51156  51155.000000
unique               217            218           NaN
top     Acer platanoides  Maple, Norway           NaN
freq                9506           9506           NaN
mean                 NaN            NaN     44.858157
std                  NaN            NaN     25.948259
min                  NaN            NaN      1.000000
25%                  NaN            NaN     25.000000
50%                  NaN            NaN     40.000000
75%                  NaN            NaN     61.000000
max                  NaN            NaN    540.000000

                                                 geometry
count                                               51156
unique                                              46397
top     {"type": "Point", "coordinates": [-79.37039696...
freq                                                   97
mean                                                  NaN
std                                                   NaN
min                                                   NaN
25%                                                   NaN
50%                                                   NaN
75%                                                   NaN
max                                                   NaN

In [4]:
df = df.dropna()  # simple approach (you can improve later)

In [5]:
target = "TREE_CONDITION"   # CHANGE THIS if your dataset uses another name

In [7]:
categorical_cols = df.select_dtypes(include=['object', 'string', 'category']).columns

In [10]:
df.index.name
df.index

RangeIndex(start=0, stop=0, step=1)

In [12]:
df.head(0)

Empty DataFrame
Columns: [_id, OBJECTID, STRUCTID, ADDRESS, STREETNAME, CROSSSTREET1, CROSSSTREET2, SUFFIX, UNIT_NUMBER, TREE_POSITION_NUMBER, SITE, WARD, BOTANICAL_NAME, COMMON_NAME, DBH_TRUNK, geometry]
Index: []

In [15]:
(df.columns)

Index(['_id', 'OBJECTID', 'STRUCTID', 'ADDRESS', 'STREETNAME', 'CROSSSTREET1',
       'CROSSSTREET2', 'SUFFIX', 'UNIT_NUMBER', 'TREE_POSITION_NUMBER', 'SITE',
       'WARD', 'BOTANICAL_NAME', 'COMMON_NAME', 'DBH_TRUNK', 'geometry'],
      dtype='str')