In [1]:
import pandas as pd
import numpy as np

from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder, StandardScaler
from sklearn.linear_model import LogisticRegression
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix

In [2]:
# Load CSV file
df = pd.read_csv("team_details.csv")

# View first rows
df.head()

,club_id,club_slug,club_name,logo_url,country_name,season_id,competition_id,competition_slug,competition_name,club_division,source_url,_last_modified_at
0,100335,cd-mafra-sub-23,CD Mafra U23 (100335),https://tmssl.akamaized.net//images/wappen/hea...,Portugal,2023,NaN,NaN,NaN,NaN,https://www.transfermarkt.com/cd-mafra-sub-23/...,2025-09-11 20:20:19
1,100431,napoli-under-18,Napoli Under 18 (100431),https://tmssl.akamaized.net//images/wappen/hea...,Italy,2021,ITJ7,campionato-nazionale-under-18,Campionato Under 18,Campionato Under 18,https://www.transfermarkt.com/napoli-under-18/...,2025-09-13 09:55:03
2,101416,venezia-under-18,Venezia Under 18 (101416),https://tmssl.akamaized.net//images/wappen/hea...,Italy,2022,NaN,NaN,NaN,NaN,https://www.transfermarkt.com/venezia-under-18...,2025-09-13 09:37:05
3,100461,lecce-under-18,Lecce Under 18 (100461),https://tmssl.akamaized.net//images/wappen/hea...,Italy,2015,ITJ7,campionato-nazionale-under-18,Campionato Under 18,Campionato Under 18,https://www.transfermarkt.com/lecce-under-18/s...,2025-09-13 09:52:59
4,10010,esporte-clube-bahia,Esporte Clube Bahia (10010),https://tmssl.akamaized.net//images/wappen/hea...,Brazil,2006,BRA1,campeonato-brasileiro-serie-a,Campeonato Brasileiro Série A,Campeonato Brasileiro Série A,https://www.transfermarkt.com/esporte-clube-ba...,2025-09-13 11:59:31

In [3]:
print(df.shape)
print(df.info())
print(df.describe())

# Check missing values
print(df.isnull().sum())

(2175, 12)
<class 'pandas.DataFrame'>
RangeIndex: 2175 entries, 0 to 2174
Data columns (total 12 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   club_id            2175 non-null   int64
 1   club_slug          2175 non-null   str
 2   club_name          2175 non-null   str
 3   logo_url           2175 non-null   str
 4   country_name       2175 non-null   str
 5   season_id          2175 non-null   int64
 6   competition_id     1669 non-null   str
 7   competition_slug   1669 non-null   str
 8   competition_name   1669 non-null   str
 9   club_division      1669 non-null   str
 10  source_url         2175 non-null   str
 11  _last_modified_at  2175 non-null   str
dtypes: int64(2), str(10)
memory usage: 757.3 KB
None
             club_id    season_id
count    2175.000000  2175.000000
mean    17617.836322  2013.741149
std     25064.372202     7.739410
min         1.000000  2000.000000
25%      1304.500000  2007.000000
50%      6502.000000  2014.000000
75%     22662.000000  2021.000000
max    133273.000000  2025.000000
club_id                0
club_slug              0
club_name              0
logo_url               0
country_name           0
season_id              0
competition_id       506
competition_slug     506
competition_name     506
club_division        506
source_url             0
_last_modified_at      0
dtype: int64

In [4]:
df = df.dropna()   # simple approach (you can also impute if needed)

In [6]:
pd.get_dummies(df, drop_first=True)

,club_id,club_slug,club_name,logo_url,country_name,season_id,competition_id,competition_slug,competition_name,club_division,source_url,_last_modified_at
1,100431,1073,1039,7,16,2021,94,42,41,41,1073,290
3,100461,974,918,8,16,2015,94,42,41,41,974,277
4,10010,510,515,3,5,2006,22,31,31,31,510,945
5,101282,357,455,16,36,2021,106,92,90,90,356,1221
6,1,5,5,0,13,2002,102,22,16,16,5,530
...,...,...,...,...,...,...,...,...,...,...,...,...
2170,999,1090,1028,1668,8,2018,98,1,154,154,1090,641
2171,9982,845,791,1667,7,2000,49,59,63,63,845,778
2172,995,639,595,1664,12,2004,64,89,88,88,640,395
2173,99764,796,739,1666,26,2005,128,88,86,86,796,302
2174,968,954,867,1635,4,2020,17,75,74,74,954,584

In [8]:
df.head()

,club_id,club_slug,club_name,logo_url,country_name,season_id,competition_id,competition_slug,competition_name,club_division,source_url,_last_modified_at
1,100431,1073,1039,7,16,2021,94,42,41,41,1073,290
3,100461,974,918,8,16,2015,94,42,41,41,974,277
4,10010,510,515,3,5,2006,22,31,31,31,510,945
5,101282,357,455,16,36,2021,106,92,90,90,356,1221
6,1,5,5,0,13,2002,102,22,16,16,5,530