In [1]:
import pandas as pd
import numpy as np

from sklearn.model_selection import train_test_split
from sklearn.feature_extraction.text import TfidfVectorizer

from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier

from sklearn.metrics import accuracy_score, classification_report, confusion_matrix
import seaborn as sns
import matplotlib.pyplot as plt

In [2]:
df = pd.read_csv("relation_message.csv")

df.head()

  subject  object relation
0   tonys   rhody   friend
1   tonys   hawke   friend
2   tonys  stever   friend
3   tonys  falcon   friend
4   tonys   nickf   friend

In [5]:
print("Shape:", df.shape)
print("\nColumns:", df.columns)
print("\nMissing values:\n", df.isnull().sum())

df.info()

Shape: (1144, 3)

Columns: Index(['subject', 'object', 'relation'], dtype='str')

Missing values:
 subject     0
object      0
relation    0
dtype: int64
<class 'pandas.DataFrame'>
RangeIndex: 1144 entries, 0 to 1143
Data columns (total 3 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   subject   1144 non-null   str
 1   object    1144 non-null   str
 2   relation  1144 non-null   str
dtypes: str(3)
memory usage: 46.0 KB

In [6]:
df.head()

  subject  object relation
0   tonys   rhody   friend
1   tonys   hawke   friend
2   tonys  stever   friend
3   tonys  falcon   friend
4   tonys   nickf   friend

In [8]:
print(df.columns)

Index(['subject', 'object', 'relation'], dtype='str')

In [11]:
df.head()

  subject  object relation
0   tonys   rhody   friend
1   tonys   hawke   friend
2   tonys  stever   friend
3   tonys  falcon   friend
4   tonys   nickf   friend

In [17]:
df.head()
df.columns

Index(['subject', 'object', 'relation'], dtype='str')