In [1]:
import pandas as pd
import numpy as np

from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix

In [2]:
df = pd.read_csv("titanic-00.csv")

df.head()

                                            Name  PClass    Age  Sex  Survived
0                   Allen, Miss Elisabeth Walton       1  29.00    1         1
1                    Allison, Miss Helen Loraine       1   2.00    1         0
2            Allison, Mr Hudson Joshua Creighton       1  30.00    0         0
3  Allison, Mrs Hudson JC (Bessie Waldo Daniels)       1  25.00    1         0
4                  Allison, Master Hudson Trevor       1   0.92    0         1

In [5]:
print(df.columns)

Index(['Name', 'PClass', 'Age', 'Sex', 'Survived'], dtype='str')

In [8]:
df.head()

                                            Name  PClass    Age  Sex  Survived
0                   Allen, Miss Elisabeth Walton       1  29.00    1         1
1                    Allison, Miss Helen Loraine       1   2.00    1         0
2            Allison, Mr Hudson Joshua Creighton       1  30.00    0         0
3  Allison, Mrs Hudson JC (Bessie Waldo Daniels)       1  25.00    1         0
4                  Allison, Master Hudson Trevor       1   0.92    0         1

In [9]:
X = df.drop("Survived", axis=1)
y = df["Survived"]

In [10]:
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42
)

In [12]:
X_train = X_train.drop(columns=['Name'])
X_test = X_test.drop(columns=['Name'])

In [13]:
rf_model = RandomForestClassifier(
    n_estimators=100,
    max_depth=5,
    random_state=42
)

rf_model.fit(X_train, y_train)

rf_pred = rf_model.predict(X_test)

print("Random Forest Accuracy:", accuracy_score(y_test, rf_pred))
print(confusion_matrix(y_test, rf_pred))
print(classification_report(y_test, rf_pred))

Random Forest Accuracy: 0.8026315789473685
[[81  8]
 [22 41]]
              precision    recall  f1-score   support

           0       0.79      0.91      0.84        89
           1       0.84      0.65      0.73        63

    accuracy                           0.80       152
   macro avg       0.81      0.78      0.79       152
weighted avg       0.81      0.80      0.80       152

In [15]:
print(len(X.columns))
print(len(rf_model.feature_importances_))

4
3