In [1]:
import pandas as pd
import numpy as np

from sklearn.model_selection import train_test_split
from sklearn.tree import DecisionTreeRegressor
from sklearn.ensemble import RandomForestRegressor

from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score

In [2]:
df = pd.read_csv("ToyotaCorolla.csv")

df.head()

                                           model  ...  tow_bar
0  TOYOTA Corolla 2.0 D4D HATCHB TERRA 2/3-Doors  ...        0
1  TOYOTA Corolla 2.0 D4D HATCHB TERRA 2/3-Doors  ...        0
2  TOYOTA Corolla 2.0 D4D HATCHB TERRA 2/3-Doors  ...        0
3  TOYOTA Corolla 2.0 D4D HATCHB TERRA 2/3-Doors  ...        0
4    TOYOTA Corolla 2.0 D4D HATCHB SOL 2/3-Doors  ...        0

[5 rows x 38 columns]

In [3]:
print(df.shape)
print(df.info())
print(df.describe())

(1436, 38)
<class 'pandas.DataFrame'>
RangeIndex: 1436 entries, 0 to 1435
Data columns (total 38 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   model              1436 non-null   str
 1   price              1436 non-null   int64
 2   age_08_04          1436 non-null   int64
 3   mfg_month          1436 non-null   int64
 4   mfg_year           1436 non-null   int64
 5   km                 1436 non-null   int64
 6   fuel_type          1436 non-null   str
 7   hp                 1436 non-null   int64
 8   met_color          1436 non-null   int64
 9   color              1436 non-null   str
 10  automatic          1436 non-null   int64
 11  cc                 1436 non-null   int64
 12  doors              1436 non-null   int64
 13  cylinders          1436 non-null   int64
 14  gears              1436 non-null   int64
 15  quarterly_tax      1436 non-null   int64
 16  weight             1436 non-null   int64
 17  mfr_guarantee      1436 non-null   int64
 18  bovag_guarantee    1436 non-null   int64
 19  guarantee_period   1436 non-null   int64
 20  abs                1436 non-null   int64
 21  airbag_1           1436 non-null   int64
 22  airbag_2           1436 non-null   int64
 23  airco              1436 non-null   int64
 24  automatic_airco    1436 non-null   int64
 25  boardcomputer      1436 non-null   int64
 26  cd_player          1436 non-null   int64
 27  central_lock       1436 non-null   int64
 28  powered_windows    1436 non-null   int64
 29  power_steering     1436 non-null   int64
 30  radio              1436 non-null   int64
 31  mistlamps          1436 non-null   int64
 32  sport_model        1436 non-null   int64
 33  backseat_divider   1436 non-null   int64
 34  metallic_rim       1436 non-null   int64
 35  radio_cassette     1436 non-null   int64
 36  parking_assistant  1436 non-null   int64
 37  tow_bar            1436 non-null   int64
dtypes: int64(35), str(3)
memory usage: 509.1 KB
None
              price    age_08_04  ...  parking_assistant      tow_bar
count   1436.000000  1436.000000  ...        1436.000000  1436.000000
mean   10730.824513    55.947075  ...           0.002786     0.277855
std     3626.964585    18.599988  ...           0.052723     0.448098
min     4350.000000     1.000000  ...           0.000000     0.000000
25%     8450.000000    44.000000  ...           0.000000     0.000000
50%     9900.000000    61.000000  ...           0.000000     0.000000
75%    11950.000000    70.000000  ...           0.000000     1.000000
max    32500.000000    80.000000  ...           1.000000     1.000000

[8 rows x 35 columns]

In [4]:
df.isnull().sum()

# Option: drop missing rows (simple approach)
df = df.dropna()

In [6]:
df.columns = df.columns.str.strip()

In [8]:
print(df.columns)

Index(['price', 'age_08_04', 'mfg_month', 'mfg_year', 'km', 'hp', 'met_color',
       'automatic', 'cc', 'doors',
       ...
       'fuel_type_Petrol', 'color_Black', 'color_Blue', 'color_Green',
       'color_Grey', 'color_Red', 'color_Silver', 'color_Violet',
       'color_White', 'color_Yellow'],
      dtype='str', length=364)

In [10]:
print("y_test exists:", "y_test" in globals())
print("dt_preds exists:", "dt_preds" in globals())

y_test exists: False
dt_preds exists: False

In [12]:
print(locals().keys())

dict_keys(['__name__', '__doc__', '__package__', '__loader__', '__spec__', '__builtin__', '__builtins__', '_ih', '_oh', '_dh', 'In', 'Out', 'get_ipython', 'exit', 'quit', 'open', '_', '__', '___', '__session__', '_i', '_ii', '_iii', '_i1', 'pd', 'np', 'train_test_split', 'DecisionTreeRegressor', 'RandomForestRegressor', 'mean_absolute_error', 'mean_squared_error', 'r2_score', '_i2', 'df', '_2', '_i3', '_i4', '_i5', 'target', '_i6', '_i7', '_i8', '_i9', 'evaluate_model', '_i10', '_i11', '_i12'])

In [17]:
df.head()

   price  age_08_04  mfg_month  ...  color_Violet  color_White  color_Yellow
0  13500         23         10  ...         False        False         False
1  13750         23         10  ...         False        False         False
2  13950         24          9  ...         False        False         False
3  14950         26          7  ...         False        False         False
4  13750         30          3  ...         False        False         False

[5 rows x 364 columns]

In [19]:
print("y_test" in globals())

False