In [1]:
import pandas as pd
import numpy as np

from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier

from sklearn.metrics import accuracy_score, classification_report, confusion_matrix
import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
df = pd.read_csv("trafficMN.csv")

df.head()

,holiday,temp,rain_1h,snow_1h,clouds_all,weather_main,weather_description,date_time,traffic_volume
0,NaN,288.28,0.0,0.0,40,Clouds,scattered clouds,2012-10-02 09:00:00,5545
1,NaN,289.36,0.0,0.0,75,Clouds,broken clouds,2012-10-02 10:00:00,4516
2,NaN,289.58,0.0,0.0,90,Clouds,overcast clouds,2012-10-02 11:00:00,4767
3,NaN,290.13,0.0,0.0,90,Clouds,overcast clouds,2012-10-02 12:00:00,5026
4,NaN,291.14,0.0,0.0,75,Clouds,broken clouds,2012-10-02 13:00:00,4918

In [3]:
print(df.shape)
print(df.info())
print(df.describe())

# Check missing values
print(df.isnull().sum())

(48204, 9)
<class 'pandas.DataFrame'>
RangeIndex: 48204 entries, 0 to 48203
Data columns (total 9 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   holiday              61 non-null     str
 1   temp                 48204 non-null  float64
 2   rain_1h              48204 non-null  float64
 3   snow_1h              48204 non-null  float64
 4   clouds_all           48204 non-null  int64
 5   weather_main         48204 non-null  str
 6   weather_description  48204 non-null  str
 7   date_time            48204 non-null  str
 8   traffic_volume       48204 non-null  int64
dtypes: float64(3), int64(2), str(4)
memory usage: 5.0 MB
None
               temp       rain_1h       snow_1h    clouds_all  traffic_volume
count  48204.000000  48204.000000  48204.000000  48204.000000    48204.000000
mean     281.205870      0.334264      0.000222     49.362231     3259.818355
std       13.338232     44.789133      0.008168     39.015750     1986.860670
min        0.000000      0.000000      0.000000      0.000000        0.000000
25%      272.160000      0.000000      0.000000      1.000000     1193.000000
50%      282.450000      0.000000      0.000000     64.000000     3380.000000
75%      291.806000      0.000000      0.000000     90.000000     4933.000000
max      310.070000   9831.300000      0.510000    100.000000     7280.000000
holiday                48143
temp                       0
rain_1h                    0
snow_1h                    0
clouds_all                 0
weather_main               0
weather_description        0
date_time                  0
traffic_volume             0
dtype: int64

In [4]:
# Simple approach: drop missing values
df = df.dropna()

In [6]:
print(df.select_dtypes(include=["object", "string"]).dtypes)

Series([], dtype: object)

In [8]:
print(df.head())
print(df.columns)

      holiday    temp  rain_1h  snow_1h  clouds_all  weather_main  \
126         1  273.08      0.0      0.0          20             1
1123        9  288.12      0.0      0.0          87             0
1370        8  278.54      0.0      0.0          20             3
2360        0  264.40      0.0      0.0          90             1
2559        6  263.49      0.0      0.0          58             1

      weather_description  date_time  traffic_volume
126                     2          0             455
1123                   11          1            1000
1370                    6          2             919
2360                    8          3             803
2559                    1          4            1439
Index(['holiday', 'temp', 'rain_1h', 'snow_1h', 'clouds_all', 'weather_main',
       'weather_description', 'date_time', 'traffic_volume'],
      dtype='str')

In [10]:
df.columns

Index(['holiday', 'temp', 'rain_1h', 'snow_1h', 'clouds_all', 'weather_main',
       'weather_description', 'date_time', 'traffic_volume'],
      dtype='str')

In [12]:
df.columns
df.head()

,holiday,temp,rain_1h,snow_1h,clouds_all,weather_main,weather_description,date_time,traffic_volume
126,1,273.08,0.0,0.0,20,1,2,0,455
1123,9,288.12,0.0,0.0,87,0,11,1,1000
1370,8,278.54,0.0,0.0,20,3,6,2,919
2360,0,264.40,0.0,0.0,90,1,8,3,803
2559,6,263.49,0.0,0.0,58,1,1,4,1439