In [1]:
# Data handling
import pandas as pd
import numpy as np

# NLP
import re
import nltk
from nltk.corpus import stopwords
from nltk.tokenize import word_tokenize

# Machine Learning
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.cluster import KMeans
from sklearn.decomposition import PCA

# Visualization
import matplotlib.pyplot as plt
import seaborn as sns

# Download NLP resources
nltk.download('punkt')
nltk.download('stopwords')

[nltk_data] Downloading package punkt to
[nltk_data]     /Users/adnanaltimeemy/nltk_data...
[nltk_data]   Package punkt is already up-to-date!
[nltk_data] Downloading package stopwords to
[nltk_data]     /Users/adnanaltimeemy/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!

True

In [2]:
# Load CSV file
df = pd.read_csv("volcano.csv")

# Display first rows
df.head()

,V1,V2,V3,V4,V5,V6,V7,V8,V9,V10,...,V52,V53,V54,V55,V56,V57,V58,V59,V60,V61
0,100,100,101,101,101,101,101,100,100,100,...,107,107,107,106,106,105,105,104,104,103
1,101,101,102,102,102,102,102,101,101,101,...,108,108,107,107,106,106,105,105,104,104
2,102,102,103,103,103,103,103,102,102,102,...,109,108,108,107,107,106,106,105,105,104
3,103,103,104,104,104,104,104,103,103,103,...,109,109,108,108,107,107,106,106,105,105
4,104,104,105,105,105,105,105,104,104,103,...,110,109,109,108,107,107,107,106,106,105

In [3]:
# Dataset information
df.info()

# Check missing values
df.isnull().sum()

# View column names
df.columns

<class 'pandas.DataFrame'>
RangeIndex: 87 entries, 0 to 86
Data columns (total 61 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   V1      87 non-null     int64
 1   V2      87 non-null     int64
 2   V3      87 non-null     int64
 3   V4      87 non-null     int64
 4   V5      87 non-null     int64
 5   V6      87 non-null     int64
 6   V7      87 non-null     int64
 7   V8      87 non-null     int64
 8   V9      87 non-null     int64
 9   V10     87 non-null     int64
 10  V11     87 non-null     int64
 11  V12     87 non-null     int64
 12  V13     87 non-null     int64
 13  V14     87 non-null     int64
 14  V15     87 non-null     int64
 15  V16     87 non-null     int64
 16  V17     87 non-null     int64
 17  V18     87 non-null     int64
 18  V19     87 non-null     int64
 19  V20     87 non-null     int64
 20  V21     87 non-null     int64
 21  V22     87 non-null     int64
 22  V23     87 non-null     int64
 23  V24     87 non-null     int64
 24  V25     87 non-null     int64
 25  V26     87 non-null     int64
 26  V27     87 non-null     int64
 27  V28     87 non-null     int64
 28  V29     87 non-null     int64
 29  V30     87 non-null     int64
 30  V31     87 non-null     int64
 31  V32     87 non-null     int64
 32  V33     87 non-null     int64
 33  V34     87 non-null     int64
 34  V35     87 non-null     int64
 35  V36     87 non-null     int64
 36  V37     87 non-null     int64
 37  V38     87 non-null     int64
 38  V39     87 non-null     int64
 39  V40     87 non-null     int64
 40  V41     87 non-null     int64
 41  V42     87 non-null     int64
 42  V43     87 non-null     int64
 43  V44     87 non-null     int64
 44  V45     87 non-null     int64
 45  V46     87 non-null     int64
 46  V47     87 non-null     int64
 47  V48     87 non-null     int64
 48  V49     87 non-null     int64
 49  V50     87 non-null     int64
 50  V51     87 non-null     int64
 51  V52     87 non-null     int64
 52  V53     87 non-null     int64
 53  V54     87 non-null     int64
 54  V55     87 non-null     int64
 55  V56     87 non-null     int64
 56  V57     87 non-null     int64
 57  V58     87 non-null     int64
 58  V59     87 non-null     int64
 59  V60     87 non-null     int64
 60  V61     87 non-null     int64
dtypes: int64(61)
memory usage: 41.6 KB

Index(['V1', 'V2', 'V3', 'V4', 'V5', 'V6', 'V7', 'V8', 'V9', 'V10', 'V11',
       'V12', 'V13', 'V14', 'V15', 'V16', 'V17', 'V18', 'V19', 'V20', 'V21',
       'V22', 'V23', 'V24', 'V25', 'V26', 'V27', 'V28', 'V29', 'V30', 'V31',
       'V32', 'V33', 'V34', 'V35', 'V36', 'V37', 'V38', 'V39', 'V40', 'V41',
       'V42', 'V43', 'V44', 'V45', 'V46', 'V47', 'V48', 'V49', 'V50', 'V51',
       'V52', 'V53', 'V54', 'V55', 'V56', 'V57', 'V58', 'V59', 'V60', 'V61'],
      dtype='str')

In [5]:
print(df.columns.tolist())

['V1', 'V2', 'V3', 'V4', 'V5', 'V6', 'V7', 'V8', 'V9', 'V10', 'V11', 'V12', 'V13', 'V14', 'V15', 'V16', 'V17', 'V18', 'V19', 'V20', 'V21', 'V22', 'V23', 'V24', 'V25', 'V26', 'V27', 'V28', 'V29', 'V30', 'V31', 'V32', 'V33', 'V34', 'V35', 'V36', 'V37', 'V38', 'V39', 'V40', 'V41', 'V42', 'V43', 'V44', 'V45', 'V46', 'V47', 'V48', 'V49', 'V50', 'V51', 'V52', 'V53', 'V54', 'V55', 'V56', 'V57', 'V58', 'V59', 'V60', 'V61']

In [7]:
df.head()

,V1,V2,V3,V4,V5,V6,V7,V8,V9,V10,...,V52,V53,V54,V55,V56,V57,V58,V59,V60,V61
0,100,100,101,101,101,101,101,100,100,100,...,107,107,107,106,106,105,105,104,104,103
1,101,101,102,102,102,102,102,101,101,101,...,108,108,107,107,106,106,105,105,104,104
2,102,102,103,103,103,103,103,102,102,102,...,109,108,108,107,107,106,106,105,105,104
3,103,103,104,104,104,104,104,103,103,103,...,109,109,108,108,107,107,106,106,105,105
4,104,104,105,105,105,105,105,104,104,103,...,110,109,109,108,107,107,107,106,106,105

In [8]:
df.to_csv(
    "volcano_clustered.csv",
    index=False
)

print("File saved successfully")

File saved successfully