In [1]:
import pandas as pd
import numpy as np

from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier

from sklearn.metrics import accuracy_score, classification_report, confusion_matrix

In [2]:
df = pd.read_csv("WorldWideDishes_2024_June_World_Wide_Dishes.csv")

df.head()

    id  ... uploaded_image_caption
0  748  ...                    NaN
1  745  ...                    NaN
2  899  ...                    NaN
3  897  ...                    NaN
4  889  ...                    NaN

[5 rows x 25 columns]

In [3]:
print(df.shape)
print(df.info())
print(df.describe(include='all'))

(765, 25)
<class 'pandas.DataFrame'>
RangeIndex: 765 entries, 0 to 764
Data columns (total 25 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   id                       765 non-null    int64
 1   local_name               765 non-null    str
 2   english_name             559 non-null    str
 3   language                 765 non-null    str
 4   language_code            765 non-null    str
 5   countries                765 non-null    str
 6   continent                765 non-null    str
 7   regions                  497 non-null    str
 8   cultures                 291 non-null    str
 9   time_of_day              765 non-null    str
 10  time_of_day_more         28 non-null     str
 11  type_of_dish             765 non-null    str
 12  type_of_dish_more        50 non-null     str
 13  utensils                 613 non-null    str
 14  drink                    257 non-null    str
 15  occasions                765 non-null    str
 16  occasions_more           173 non-null    str
 17  ingredients              765 non-null    str
 18  recipe                   468 non-null    str
 19  more_details             237 non-null    str
 20  public_cc_image_url      432 non-null    str
 21  public_cc_image_caption  301 non-null    str
 22  uploaded_image_name      71 non-null     str
 23  uploaded_image_url       71 non-null     str
 24  uploaded_image_caption   71 non-null     str
dtypes: int64(1), str(24)
memory usage: 483.4 KB
None
                id  ...                             uploaded_image_caption
count   765.000000  ...                                                 71
unique         NaN  ...                                                 70
top            NaN  ...  Crumbly maize meal porridge in a bowl with sou...
freq           NaN  ...                                                  2
mean    510.521569  ...                                                NaN
std     271.547555  ...                                                NaN
min      24.000000  ...                                                NaN
25%     280.000000  ...                                                NaN
50%     514.000000  ...                                                NaN
75%     750.000000  ...                                                NaN
max     977.000000  ...                                                NaN

[11 rows x 25 columns]

In [4]:
df = df.dropna()   # simple approach (you can improve later)

In [6]:
label_encoders[column] = le

In [8]:
print(df.columns)

Index(['id', 'local_name', 'english_name', 'language', 'language_code',
       'countries', 'continent', 'regions', 'cultures', 'time_of_day',
       'time_of_day_more', 'type_of_dish', 'type_of_dish_more', 'utensils',
       'drink', 'occasions', 'occasions_more', 'ingredients', 'recipe',
       'more_details', 'public_cc_image_url', 'public_cc_image_caption',
       'uploaded_image_name', 'uploaded_image_url', 'uploaded_image_caption'],
      dtype='str')

In [12]:
df.columns

Index(['id', 'local_name', 'english_name', 'language', 'language_code',
       'countries', 'continent', 'regions', 'cultures', 'time_of_day',
       'time_of_day_more', 'type_of_dish', 'type_of_dish_more', 'utensils',
       'drink', 'occasions', 'occasions_more', 'ingredients', 'recipe',
       'more_details', 'public_cc_image_url', 'public_cc_image_caption',
       'uploaded_image_name', 'uploaded_image_url', 'uploaded_image_caption'],
      dtype='str')

In [15]:
print("X_train exists?", "X_train" in globals())
print("y_train exists?", "y_train" in globals())

X_train exists? False
y_train exists? False

In [17]:
print("X exists:", "X" in globals())
print("y exists:", "y" in globals())
print("X_train exists:", "X_train" in globals())

X exists: False
y exists: False
X_train exists: False

In [21]:
print("y_test exists:", "y_test" in globals())
print("y_pred_rf exists:", "y_pred_rf" in globals())

y_test exists: False
y_pred_rf exists: False

In [31]:
df.head(10)

Empty DataFrame
Columns: [id, local_name, english_name, language, language_code, countries, continent, regions, cultures, time_of_day, time_of_day_more, type_of_dish, type_of_dish_more, utensils, drink, occasions, occasions_more, ingredients, recipe, more_details, public_cc_image_url, public_cc_image_caption, uploaded_image_name, uploaded_image_url, uploaded_image_caption]
Index: []