In [1]:
# Data handling
import pandas as pd
import numpy as np

# NLP
import re
import nltk
from nltk.corpus import stopwords
from sklearn.feature_extraction.text import TfidfVectorizer

# Machine Learning
from sklearn.cluster import KMeans
from sklearn.preprocessing import StandardScaler

# Visualisation
import matplotlib.pyplot as plt
from sklearn.decomposition import PCA

# Download stopwords
nltk.download('stopwords')

[nltk_data] Downloading package stopwords to
[nltk_data]     /Users/adnanaltimeemy/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!

True

In [2]:
# Load CSV file

df = pd.read_csv("wwwusage.csv")

# Display first rows

df.head()

    x
0  88
1  84
2  85
3  85
4  84

In [3]:
# Dataset information

df.info()

<class 'pandas.DataFrame'>
RangeIndex: 100 entries, 0 to 99
Data columns (total 1 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   x       100 non-null    int64
dtypes: int64(1)
memory usage: 932.0 bytes

In [4]:
# Remove duplicate rows

df = df.drop_duplicates()

# Fill missing values

df = df.fillna("")

In [5]:
# Select text columns

text_columns = df.select_dtypes(include=['object']).columns

text_columns

Index([], dtype='str')

In [6]:
# Combine all text columns into one NLP column

df['text_data'] = df[text_columns].astype(str).agg(' '.join, axis=1)

df[['text_data']].head()

  text_data
0
1
2
6
9

In [7]:
stop_words = set(stopwords.words('english'))

def clean_text(text):
    
    # Lowercase
    text = text.lower()
    
    # Remove special characters
    text = re.sub(r'[^a-zA-Z\s]', '', text)
    
    # Tokenization
    words = text.split()
    
    # Remove stopwords
    words = [
        word for word in words 
        if word not in stop_words
    ]
    
    return " ".join(words)


df['clean_text'] = df['text_data'].apply(clean_text)

df[['clean_text']].head()

  clean_text
0
1
2
6
9

In [9]:
df.to_csv(
    "wwwusage_kmeans_clusters.csv",
    index=False
)