In [1]:
!pip install pandas numpy matplotlib seaborn scikit-learn nltk

Requirement already satisfied: pandas in ./miniconda3/envs/coding/lib/python3.12/site-packages (3.0.4)
Requirement already satisfied: numpy in ./miniconda3/envs/coding/lib/python3.12/site-packages (2.5.0)
Requirement already satisfied: matplotlib in ./miniconda3/envs/coding/lib/python3.12/site-packages (3.11.0)
Requirement already satisfied: seaborn in ./miniconda3/envs/coding/lib/python3.12/site-packages (0.13.2)
Requirement already satisfied: scikit-learn in ./miniconda3/envs/coding/lib/python3.12/site-packages (1.9.0)
Requirement already satisfied: nltk in ./miniconda3/envs/coding/lib/python3.12/site-packages (3.9.2)
Requirement already satisfied: python-dateutil>=2.8.2 in ./miniconda3/envs/coding/lib/python3.12/site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: contourpy>=1.0.1 in ./miniconda3/envs/coding/lib/python3.12/site-packages (from matplotlib) (1.3.3)
Requirement already satisfied: cycler>=0.10 in ./miniconda3/envs/coding/lib/python3.12/site-packages (from matplotlib) (0.12.1)
Requirement already satisfied: fonttools>=4.22.0 in ./miniconda3/envs/coding/lib/python3.12/site-packages (from matplotlib) (4.63.0)
Requirement already satisfied: kiwisolver>=1.3.1 in ./miniconda3/envs/coding/lib/python3.12/site-packages (from matplotlib) (1.5.0)
Requirement already satisfied: packaging>=20.0 in ./miniconda3/envs/coding/lib/python3.12/site-packages (from matplotlib) (26.2)
Requirement already satisfied: pillow>=9 in ./miniconda3/envs/coding/lib/python3.12/site-packages (from matplotlib) (12.3.0)
Requirement already satisfied: pyparsing>=3 in ./miniconda3/envs/coding/lib/python3.12/site-packages (from matplotlib) (3.3.2)
Requirement already satisfied: scipy>=1.10.0 in ./miniconda3/envs/coding/lib/python3.12/site-packages (from scikit-learn) (1.18.0)
Requirement already satisfied: joblib>=1.4.0 in ./miniconda3/envs/coding/lib/python3.12/site-packages (from scikit-learn) (1.5.3)
Requirement already satisfied: narwhals>=2.0.1 in ./miniconda3/envs/coding/lib/python3.12/site-packages (from scikit-learn) (2.23.0)
Requirement already satisfied: threadpoolctl>=3.5.0 in ./miniconda3/envs/coding/lib/python3.12/site-packages (from scikit-learn) (3.6.0)
Requirement already satisfied: click in ./miniconda3/envs/coding/lib/python3.12/site-packages (from nltk) (8.1.8)
Requirement already satisfied: regex>=2021.8.3 in ./miniconda3/envs/coding/lib/python3.12/site-packages (from nltk) (2025.10.23)
Requirement already satisfied: tqdm in ./miniconda3/envs/coding/lib/python3.12/site-packages (from nltk) (4.67.1)
Requirement already satisfied: six>=1.5 in ./miniconda3/envs/coding/lib/python3.12/site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)

In [2]:
import pandas as pd
import numpy as np

import matplotlib.pyplot as plt
import seaborn as sns

from sklearn.cluster import KMeans
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.preprocessing import StandardScaler
from sklearn.decomposition import PCA

import nltk
nltk.download('stopwords')
from nltk.corpus import stopwords

[nltk_data] Downloading package stopwords to
[nltk_data]     /Users/adnanaltimeemy/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!

In [3]:
df = pd.read_csv("pizza_sales (1).csv")

df.head()

,pizza_id,order_id,pizza_name_id,quantity,order_date,order_time,unit_price,total_price,pizza_size,pizza_category,pizza_ingredients,pizza_name
0,1,1,hawaiian_m,1,01-01-2015,11:38:36,13.25,13.25,M,Classic,"Sliced Ham, Pineapple, Mozzarella Cheese",The Hawaiian Pizza
1,2,2,classic_dlx_m,1,01-01-2015,11:57:40,16.00,16.00,M,Classic,"Pepperoni, Mushrooms, Red Onions, Red Peppers,...",The Classic Deluxe Pizza
2,3,2,five_cheese_l,1,01-01-2015,11:57:40,18.50,18.50,L,Veggie,"Mozzarella Cheese, Provolone Cheese, Smoked Go...",The Five Cheese Pizza
3,4,2,ital_supr_l,1,01-01-2015,11:57:40,20.75,20.75,L,Supreme,"Calabrese Salami, Capocollo, Tomatoes, Red Oni...",The Italian Supreme Pizza
4,5,2,mexicana_m,1,01-01-2015,11:57:40,16.00,16.00,M,Veggie,"Tomatoes, Red Peppers, Jalapeno Peppers, Red O...",The Mexicana Pizza

In [4]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 48620 entries, 0 to 48619
Data columns (total 12 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   pizza_id           48620 non-null  int64
 1   order_id           48620 non-null  int64
 2   pizza_name_id      48620 non-null  str
 3   quantity           48620 non-null  int64
 4   order_date         48620 non-null  str
 5   order_time         48620 non-null  str
 6   unit_price         48620 non-null  float64
 7   total_price        48620 non-null  float64
 8   pizza_size         48620 non-null  str
 9   pizza_category     48620 non-null  str
 10  pizza_ingredients  48620 non-null  str
 11  pizza_name         48620 non-null  str
dtypes: float64(2), int64(3), str(7)
memory usage: 10.4 MB

In [6]:
print(df.columns)

Index(['pizza_id', 'order_id', 'pizza_name_id', 'quantity', 'order_date',
       'order_time', 'unit_price', 'total_price', 'pizza_size',
       'pizza_category', 'pizza_ingredients', 'pizza_name'],
      dtype='str')

In [7]:
stop_words = set(stopwords.words('english'))

def clean_text(text):
    text = str(text).lower()
    text = ''.join([c for c in text if c.isalpha() or c == ' '])
    words = text.split()
    words = [w for w in words if w not in stop_words]
    return ' '.join(words)

In [10]:
print(df.columns)

Index(['pizza_id', 'order_id', 'pizza_name_id', 'quantity', 'order_date',
       'order_time', 'unit_price', 'total_price', 'pizza_size',
       'pizza_category', 'pizza_ingredients', 'pizza_name'],
      dtype='str')

In [13]:
df.head()

,pizza_id,order_id,pizza_name_id,quantity,order_date,order_time,unit_price,total_price,pizza_size,pizza_category,pizza_ingredients,pizza_name
0,1,1,hawaiian_m,1,01-01-2015,11:38:36,13.25,13.25,M,Classic,"Sliced Ham, Pineapple, Mozzarella Cheese",The Hawaiian Pizza
1,2,2,classic_dlx_m,1,01-01-2015,11:57:40,16.00,16.00,M,Classic,"Pepperoni, Mushrooms, Red Onions, Red Peppers,...",The Classic Deluxe Pizza
2,3,2,five_cheese_l,1,01-01-2015,11:57:40,18.50,18.50,L,Veggie,"Mozzarella Cheese, Provolone Cheese, Smoked Go...",The Five Cheese Pizza
3,4,2,ital_supr_l,1,01-01-2015,11:57:40,20.75,20.75,L,Supreme,"Calabrese Salami, Capocollo, Tomatoes, Red Oni...",The Italian Supreme Pizza
4,5,2,mexicana_m,1,01-01-2015,11:57:40,16.00,16.00,M,Veggie,"Tomatoes, Red Peppers, Jalapeno Peppers, Red O...",The Mexicana Pizza

In [16]:
print(df.columns)

print('sales_scaled' in globals())
print('X_text' in globals())

Index(['pizza_id', 'order_id', 'pizza_name_id', 'quantity', 'order_date',
       'order_time', 'unit_price', 'total_price', 'pizza_size',
       'pizza_category', 'pizza_ingredients', 'pizza_name'],
      dtype='str')
False
False